terascope/teraslice

job.json, jobSchema.js, lib/processors/elasticsearch_index_selector.js, lib/readers/elasticsearch_reader.js, lib/readers/file_import.js, lib/readers/kafka_simple_reader.js, lib/senders/elasticsearch_bulk_insert.js, lib/senders/file_export.js, lib/senders/kafka_simple_sender.js, lib/utils/config.js, lib/utils/convict_utils.js, package.json
btw convict format validations can be a bit finiky, they will need some explanation and once its explained its pretty easy to use
=> added job configuration validation

lib/readers/elasticsearch_reader.js, lib/utils/elastic_utils.js, spec/readers/elasticsearch_reader-spec.js
should handle errors in both once and persistent, added tests to verify
=> handles date errors resolves #99

lib/cluster/services/cluster.js, lib/cluster/services/jobs.js, lib/utils/queue.js
if starting teraslice from scratch with no ES job indicies it throws an error, i hid that on start up so when people trying this for the first time wont have errors thrown at them for something that doesnt exist yet
=> Cluster service

lib/cluster/services/api.js, lib/cluster/services/jobs.js, lib/config/validators/job.js, lib/processors/file_chunker.js, lib/readers/elasticsearch_reader.js, lib/senders/hdfs_file_append.js
For some reason the Number type does not work. Switched schemas to use "integer" instead fixes #145
=> Adding validation to job submission. 

lib/cluster/slicer.js, lib/cluster/storage/analytics.js, lib/cluster/worker.js
=> Adding error handling to state and analytics storage

lib/cluster/services/api.js, lib/cluster/services/cluster.js, lib/cluster/services/jobs.js
sorry, i reformated the code as i was working so a lot of it is code style changes
=> fixed _notifyCluster naming collision to send messages

lib/cluster/services/cluster.js, lib/cluster/slicer.js, lib/config/schemas/job.js, lib/readers/elasticsearch_reader.js, lib/utils/elastic_utils.js
at the job level, new configuration option:
slicers: 1 is the default
=> first pass on slicer refactor

lib/cluster/node_master.js, lib/cluster/runners/job.js, lib/cluster/services/api.js, lib/cluster/services/cluster.js, lib/cluster/services/jobs.js, lib/cluster/slicer.js, lib/cluster/storage/backends/elasticsearch.js, lib/cluster/storage/state.js, lib/cluster/worker.js, lib/config/schemas/system.js, lib/config/validators/job.js, lib/readers/elasticsearch_data_generator.js, lib/readers/elasticsearch_reader.js, lib/readers/file_import.js, lib/utils/elastic_utils.js, lib/utils/queue.js
I still need to verify how multiple slicers react in persistent mode, I also need to go through later and bring file_import and elasticsearch_data_generator up to work in slicers > 1
=> Slicer changes

lib/cluster/slicer.js, lib/readers/elasticsearch_reader.js, spec/readers/elasticsearch_reader-spec.js
this will reduce the amount of zero slices that it will consume, there will still exist some zero slices based off data distribution and how its split up between the slicers
=> Slicer zero

lib/cluster/cluster_master.js, lib/cluster/node_master.js, lib/cluster/services/api.js, lib/cluster/services/cluster.js, lib/cluster/services/jobs.js, lib/cluster/slicer.js, lib/readers/elasticsearch_date_range/slicer.js
api endpoints:
/cluster/_slicers
/jobs/:id/_slicer-stats
data tracked : {
available_workers: 0,
active_workers: 0,
failed_slices: 0,
subslice: 0,
slices_enqueued: 0,
zero_slice_reduction: 0,
slices_processed: 0,
total_slicers: 0,
all_data_sliced: false
};
=> Slicer stats

lib/cluster/node_master.js, lib/cluster/services/cluster.js, lib/cluster/services/jobs.js, lib/cluster/slicer.js, lib/config/schemas/job.js, lib/config/schemas/system.js, lib/config/validators/job.js, lib/processors/elasticsearch_index_selector.js, lib/processors/file_chunker.js, lib/processors/script.js, lib/readers/elasticsearch_data_generator.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/elasticsearch_reader.js, lib/senders/elasticsearch_bulk.js, lib/utils/convict_utils.js, service.js
this need to be used in tandem with the terafoundation changes, which ever  open PR eventually gets merged first, i will have to rebase the other
=> Validations

lib/cluster/storage/backends/elasticsearch.js, lib/cluster/worker.js, lib/senders/elasticsearch_bulk.js, lib/utils/elastic_utils.js
this works only for elasticsearch_sender, i have yet to apply this logic towards the other systems that send to elasticsearch
=> elasticsearch_sender should handle queue overload

lib/readers/elasticsearch_data_generator.js
added new config to job for elasticsearch_data_generator:
stress_test: true
it defaults to false
=> add stress_test support

lib/cluster/slicer.js, lib/cluster/worker.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/id_reader.js
added additional logging in several spots, let me know if its too much or not enough in certain circumstances.
Also i changed the error msg on worker failure, it will take on the original error at the end
=> increased logging for transperency

lib/processors/elasticsearch_index_selector.js
added a create key to opConfig, defaults to false
=> added create key for index_selector

lib/cluster/node_master.js, lib/cluster/services/api.js, lib/cluster/services/cluster.js, lib/cluster/slicer.js, lib/cluster/storage/analytics.js, lib/cluster/storage/backends/elasticsearch.js, lib/cluster/worker.js, lib/readers/elasticsearch_date_range/slicer.js
example curl request to add:
$curl -XPOST localhost:5678/jobs/6e380d6c-132c-4a1a-aba2-5b22b0e55d2e/_workers?add=2
example curl request to remove:
$curl -XPOST localhost:5678/jobs/6e380d6c-132c-4a1a-aba2-5b22b0e55d2e/_workers?remove=2
example curl request for total(will add or remove, just declare total):
$curl -XPOST localhost:5678/jobs/6e380d6c-132c-4a1a-aba2-5b22b0e55d2e/_workers?total=10
=> Job workers

docs/reference.md, lib/cluster/runners/job.js, lib/cluster/runners/op.js, lib/cluster/services/jobs.js, lib/cluster/slicer.js, lib/config/validators/job.js, lib/processors/elasticsearch_index_selector.js, lib/readers/elasticsearch_data_generator.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/elasticsearch_reader.js, lib/readers/file_import.js, lib/readers/id_reader.js, lib/senders/elasticsearch_bulk.js, lib/senders/file_export.js, lib/senders/hdfs_file_append.js, lib/senders/noop.js, lib/senders/stdout.js, lib/utils/config.js
removed duplicate validations
removed unused code
unified dirs under ops_directory
refactored senders to use newProcessor
** need to determine if we should move senders into processor folder, or keep them separate
added  op_validation and post_validation functions for all ops,
op_validation(job)
post_validation(job, sysconfig)
added additional guard logic around elasticsearch_index_selector and elasticsearch_bulk
=> Validation

lib/processors/elasticsearch_bulk.js
changed behaviour or send, please talk to me first
=> updated sender to work with different metadata resolves #299

README.md, docs/reference.md, lib/cluster/storage/backends/elasticsearch.js, lib/processors/elasticsearch_bulk.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/elasticsearch_reader.js, service.js
adds subslice_by_key parameter to elasticsearch reader, defaults to false, determines if it should run logic to sublice by key, now you dont need to set threshold really high to never hit this
type is now optional
updated docs
has changes needed for terafoundation changes
=> Key slice fix

docs/reference.md
This may be more trouble than it's worth at this point without a systematic way of keeping the TOC up to date.  I guess I am saying, I don't know that this is worth it now that I have thought about it.  At least not until there is a serious push to maintain quality documentation.
=> Added TOC to refernces.md

.travis.yml, README.md, package.json
Adding travis.yml to configure travisci
=> Adding travis ci

lib/readers/elasticsearch_date_range/slicer.js, lib/readers/elasticsearch_reader.js, lib/utils/elastic_utils.js, spec/readers/elasticsearch_reader-spec.js, spec/utils/elastic_utils-spec.js
if interval is bigger than index date range, then the interval is changed to be as big as the actual date range. fixed error naming of sublice_by_key
=> Date reader fixes

lib/cluster/slicer.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/elasticsearch_reader.js, lib/readers/id_slicer.js
added proper error handlers to id_slicer and to the sublice by key option for the date range slicer.
It also defaults to false
=> Id slicer init errors

lib/cluster/node_master.js, lib/cluster/services/cluster.js, lib/cluster/services/messaging.js
encapsulated and debounce node_state messaging calls
=> debounced node state updates

docs/api.md, docs/configuration.md, docs/reference.md
Various fixes and cleanup
* Cleaned up some headers
* Added limit option to stdout I failed to add earlier
* added connection option to elasticsearch_reader that was missing
* Cleaned up table on elasticsearch_bulk accidentally
I avoided cleaning too much up though.  Will do that later.
refs #385
=> Issue#385 doc improvements

lib/cluster/runners/job.js, lib/cluster/runners/op.js, lib/cluster/services/messaging.js, lib/cluster/slicer.js, lib/cluster/worker.js, lib/processors/fakeProc.js, lib/readers/fakeReader.js
This pr is to help the job fail properly when a reader or slicer has errors
=> Worker exit

lib/cluster/worker.js
removed unneeded checks in isReady
made sure state_store logging of error happens before marking isDone
used slice_id as marker for error retries
=> added guards to marking slice as failed

lib/cluster/services/api.js
original error did not occur for me, I had refactored the api after this was shown. I tightened up the other endpoints for POST and PUT
=> improved POST and PUT error handling resolves #417

docs/ops-reference.md, lib/processors/noop.js, spec/processors/noop-spec.js
To support an upcoming change in the teraslice test harness I have added a `noop` operator/processor for teraslice.  There are no changes to other teraslice code so this can probably just be accepted
=> adding a noop processor

lib/cluster/services/jobs.js
this need to go in tandem with the pull request in the queue module
=> changed the wrong method name

lib/cluster/runners/op.js
=> instead of just name, walk to find name or codeName

lib/cluster/runners/op.js
Fixed bug and optimized code to prevent duplicate file path walking
=> fixed asset loading bug resolves #479

README.md, docs/services.md, lib/cluster/services/jobs.js, lib/config/schemas/job.js, lib/config/schemas/system.js
- Improved documentation
- Ensured consistent moderator key values listed on jobs
=> Moderator docs

integration-tests/Makefile
Remove the accidentally added internal npm registry.
=> removing internal registry

lib/cluster/runners/job.js, lib/cluster/slicer.js, lib/cluster/worker.js
- this commit allows op to do async work as setup before it returns the running function that actually processes the slice/data
- Cleaned up slicer shutdown interval so it does not call multiple times
=> Async op loading

lib/cluster/services/jobs.js, lib/cluster/storage/backends/elasticsearch_store.js
this helps alleviate a shutdown issue with cluster master itself. It does not necessarily resolve the stop job timeouts
=> Stop timeouts

integration-tests/spec/cases/cluster/api.js, integration-tests/spec/cases/cluster/job-state.js, integration-tests/spec/setup.js, lib/cluster/services/jobs.js
needs to be in conjunction with teraslice client changes
=> fixed PUT /jobs/:job_id endpoint resolves #533

lib/cluster/slicer.js, lib/cluster/storage/assets.js, lib/cluster/worker.js
Requires terascope/terafoundation#93 to be merged
=> Updating the assets API setup based on foundation API changes. 

docs/ops-reference.md, integration-tests/spec/cases/data/id-reader.js, lib/readers/id_reader.js, lib/readers/id_slicer.js, spec/readers/id_slicer-spec.js
this add the `starting_key_depth` setting on the opConfig of the id_reader
=> added minimum key depth paramter resolves #551

.eslintrc, lib/cluster/slicer.js, lib/readers/elasticsearch_date_range/slicer.js, lib/readers/id_slicer.js, spec/readers/elasticsearch_reader-spec.js
- fixed subslice by keys functionality
- fixed an internal compare Interval function to return correct interval
- updated job after interval was made so that it shows up in the ex
- tested recursive slicing down to smallest number
- tested expansion of slices
- tested proper slice creation
- tested slicer does not break on query with no results
- tested proper updates with when opConfig has start/end and start & end as well as auto
=> Teraslice testing

lib/cluster/execution_controller/engine.js, lib/cluster/execution_controller/index.js, lib/cluster/runners/execution.js, spec/runners/execution-spec.js
This addresses the initialize bug as well as the analytics bug on retries adding to much data than the steps. There are tests for the analytics bug
=> Execution fix

package.json
This release fixes an issue with starting the cluster_master that only effects the k8s integration which is currently in development.  There is no other impact.
=> updating version to 0.32.0

lib/config/validators/config.js
to be paired with code changes in terafoundation
=> removed warning logs from updated convict lib resolves #709

package.json
This release includes the following improvements:
* Upgraded dependencies and code to be compatible with Node 8 #645
* Introducing API versioning #702
* Added JSON API endpoint for assets
* Improved handling of failing processor #706
=> Release 0.36.0

package.json
This release contains the following improvements:
* First usable release of the kubernetes clustering mechanism.
=> Release 0.38.0

.travis.yml, packages/teraslice-worker/package.json, packages/teraslice/package.json
This releases 0.39.0.
There were lots of changes in this release, much of is a structural reorganization of our repositories.
=> Releasing 0.39.0

docs/k8s-clustering.md
=> Updated docs with kubernetes_namespace

packages/teraslice-worker/package.json, packages/teraslice/package.json
Update teraslice version to `v0.40.1`
=> Update teraslice version to v0.40.1

README.md
Updated README to reflect the need for the job sub-command with tjm.
=> Update readme for new teraslice cli

packages/teraslice/package.json, scripts/bump.js
- Reduce variations in `native` and `kubernetes` clustering
- Faster docker builds, and include kafka connector in the docker image
- Preload assets in `native` clustering
- Many internal fixes and file organization changes
=> v0.41.0 reduce variations in native and kubernetes clustering

e2e/test/misc.js, packages/teraslice-messaging/src/messenger/client.ts, packages/teraslice/lib/workers/execution-controller/index.js, packages/teraslice/lib/workers/worker/index.js, packages/teraslice/lib/workers/worker/slice.js, packages/teraslice/package.json, packages/teraslice/test/workers/execution-controller/recovery-spec.js, packages/teraslice/test/workers/worker/worker-spec.js
=> v0.41.4 worker memory leak fix

packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, yarn.lock
`package.json` version was not updated in #843.  
Updated teraslice-cli version to v0.3.1 to use client v0.4.0.
=> Updated teraslice-client-js version to v0.4.0.

.dockerignore, .gitignore, .travis.yml, e2e/README.md, e2e/config/teraslice-master.yaml, e2e/config/teraslice-worker.yaml, e2e/docker-compose.yml, e2e/package.json, e2e/test/cases/cluster/worker-allocation-spec.js, e2e/test/download-assets.js, e2e/test/fixtures/jobs/generator.json, e2e/test/fixtures/jobs/id.json, e2e/test/fixtures/jobs/multisend.json, e2e/test/fixtures/jobs/reindex.json, e2e/test/global.setup.js, e2e/test/scripts/fetch-assets.sh, packages/job-components/package.json, packages/job-components/src/operations/data-entity.ts, packages/job-components/test/operations/data-entity-spec.ts, packages/teraslice-op-test-harness/package.json, packages/teraslice/lib/cluster/services/assets.js, packages/teraslice/lib/cluster/storage/assets.js, packages/teraslice/lib/config/schemas/system.js, packages/teraslice/lib/processors/elasticsearch_bulk.js, packages/teraslice/lib/readers/elasticsearch_data_generator.js, packages/teraslice/lib/readers/elasticsearch_reader/index.js, packages/teraslice/lib/utils/file_utils.js, packages/teraslice/package.json, yarn.lock
This PR adds support for autoloading assets from directory,
in order to better support asset bundles.
TODO:
=> v0.43.1: Autoload assets in e2e tests

e2e/package.json, package.json, packages/docker-compose-js/package.json, packages/elasticsearch-api/package.json, packages/job-components/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, yarn.lock
[CHORE]: Update packages with bug fix level changes.
[CHORE]: Fix linting issues in op-test-harness and teraslice-cli
NOTE: I did not update teraslice-cli since I am not sure of the state of that project.
=> v0.42.4 update packages

packages/teraslice/package.json
Faster DataEntity creation and bug fixes
=> v0.44.0 - Faster DataEntity creation and bug fixes

package.json, packages/job-components/package.json, packages/job-components/src/test-helpers.ts, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice-test-harness/src/worker-test-harness.ts, packages/teraslice-test-harness/test/worker-test-harness-spec.ts, packages/teraslice/lib/workers/helpers/op-analytics.js, packages/teraslice/lib/workers/helpers/worker-shutdown.js, packages/teraslice/lib/workers/worker/slice.js, packages/teraslice/package.json, packages/teraslice/test/workers/worker/slice-spec.js, yarn.lock
Fixes:
- Issue when retries only try
- log level when shutting down
- logging of op stats, see #865 
Add support for slice tries to the test harness
=> v0.44.2 a few fixes

packages/job-components/package.json, packages/job-components/src/interfaces/context.ts, packages/job-components/src/test-helpers.ts, packages/job-components/test/test-helpers-spec.ts, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/lib/workers/context/terafoundation-context.js, packages/teraslice/package.json, packages/teraslice/test/workers/context/terafoundation-context-spec.js
=> Fix `context.sysconfig._nodeName`

.travis.yml, packages/ts-transforms/package.json, packages/ts-transforms/src/command.ts, packages/ts-transforms/src/operations/index.ts, packages/ts-transforms/src/operations/lib/validations/isdn.ts, packages/ts-transforms/test/operations/validations/isdn-spec.ts
bumped version and changed name of phone number validation to isdn
=> Phone validation name fixes

packages/teraslice-cli/package.json
We fat fingered something here that breaks package install.
=> fix index.js in teraslice-cli package.json

packages/ts-transforms/package.json, packages/ts-transforms/src/command.ts, packages/ts-transforms/src/loader/index.ts, packages/ts-transforms/src/operations/lib/transforms/extraction.ts, packages/ts-transforms/src/phases/extraction_phase.ts, packages/ts-transforms/src/phases/output_phase.ts, packages/ts-transforms/test/fixtures/transformRules24.txt, packages/ts-transforms/test/loader-spec.ts, packages/ts-transforms/test/transform-spec.ts
- you can now put a selector on a `other_match_required` config to narrow its extraction
=> Other match feature

packages/ts-transforms/package.json, packages/ts-transforms/src/operations/lib/validations/email.ts, packages/ts-transforms/test/operations/validations/email-spec.ts
=> fix to validate uppercase email addresses

docs/packages/chunked-file-reader/overview.md, packages/chunked-file-reader/lib/formatters.js, packages/chunked-file-reader/lib/index.js, packages/chunked-file-reader/package.json, packages/chunked-file-reader/test/chunked-file-reader-spec.js
This lays the groundwork for changes in the `file-assets` that fix terascope/file-assets#24
=> added more format support in chunked file reader

docs/development/contributing.md, docs/development/e2e-tests.md, docs/development/overview.md, docs/development/packages.md, docs/development/releases.md, docs/development/tests.md, docs/examples.md, docs/packages.md, docs/packages/data-access-plugin/overview.md, docs/packages/data-access/overview.md, docs/packages/elasticsearch-api/overview.md, docs/packages/elasticsearch-store/overview.md, docs/packages/error-parser/overview.md, docs/packages/job-components/overview.md, docs/packages/queue/overview.md, docs/packages/teraslice-messaging/overview.md, docs/packages/teraslice-op-test-harness/overview.md, docs/packages/ts-transforms/operations.md, docs/packages/ts-transforms/overview.md, docs/packages/ts-transforms/plugins.md, docs/packages/utils/overview.md, docs/packages/xlucene-evaluator/overview.md, scripts/update-docs.sh, website/sidebars.json
=> Documentation Fixes

docs/clustering/k8s.md, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
Extending Teraslice job targets to add support for k8s preferred affinity and tolerations.
=> Improve k8s targets

packages/data-access-plugin/package.json, packages/data-access/package.json, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/xlucene-evaluator/package.json, packages/xlucene-evaluator/peg/lucene.pegjs, packages/xlucene-evaluator/src/document-matcher/index.ts, packages/xlucene-evaluator/src/index.ts, packages/xlucene-evaluator/src/interfaces.ts, packages/xlucene-evaluator/src/lucene-query-access/index.ts, packages/xlucene-evaluator/src/lucene-query-parser/index.ts, packages/xlucene-evaluator/src/translator/utils.ts, packages/xlucene-evaluator/test/document-matcher-spec.ts, packages/xlucene-evaluator/test/lucene-query-access-spec.ts, packages/xlucene-evaluator/test/lucene-query-parser-spec.ts, packages/xlucene-evaluator/test/translator-spec.ts
@jsnoble and I fixed an issue with handling chained NOT expressions. Additionally, I added another option to the luncene query access library for allowing implicit querie and I found and fixed problems with nested queries in the translator.
=> Important fixes to NOT handling in xlucene

docs/packages/ts-transforms/operations.md, packages/ts-transforms/package.json, packages/ts-transforms/src/interfaces.ts, packages/ts-transforms/src/loader/rules-loader.ts, packages/ts-transforms/src/loader/utils.ts, packages/ts-transforms/src/operations/lib/transforms/array.ts, packages/ts-transforms/test/fixtures/sameSourceDifferentSelector.txt, packages/ts-transforms/test/fixtures/transformRules8.txt, packages/ts-transforms/test/operations/transforms/array-spec.ts, packages/ts-transforms/test/transform-spec.ts
- fixed whitespace issue when loading rules
- fixed one-to-one op expansion bug
=> Transform bug fixes

packages/teraslice-cli/lib/asset-src.js, packages/teraslice-cli/test/lib/assetSrc-spec.js
I didn't manage to get these to fail locally, so I've re-enabled the tests and added a remove of a file.  Maybe something will turn up in CI.
=> re-enable asset specs

docs/packages/ts-transforms/operations.md, packages/ts-transforms/package.json, packages/ts-transforms/src/command.ts, packages/ts-transforms/src/interfaces.ts, packages/ts-transforms/src/operations/lib/transforms/extraction.ts, packages/ts-transforms/src/operations/lib/validations/validator.ts, packages/ts-transforms/src/phases/extraction_phase.ts, packages/ts-transforms/src/phases/output_phase.ts, packages/ts-transforms/src/phases/post_process_phase.ts, packages/ts-transforms/src/phases/utils.ts, packages/ts-transforms/test/operations/validations/validator_lib-spec.ts
- added -i options for cli to ignore bad data
- extractions do not always use expensive _.get
-some speed refactors for post_process phase and output phase
=> Transform cli fixes

packages/data-access-plugin/package.json, packages/data-access-plugin/src/search/index.ts, packages/data-access/package.json, packages/data-access/src/search-access.ts, packages/data-access/test/search-access-spec.ts, packages/data-types/package.json, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/ui-components/package.json, packages/ui-data-access/package.json, packages/xlucene-evaluator/package.json, packages/xlucene-evaluator/src/query-access/interfaces.ts, packages/xlucene-evaluator/src/query-access/query-access.ts, packages/xlucene-evaluator/test/query-access-spec.ts, yarn.lock
=> Fix require query in search

packages/data-access-plugin/package.json, packages/data-access-plugin/src/spaces/dynamic-schema.ts, packages/data-access-plugin/src/spaces/resolvers/index.ts, packages/data-access/package.json, packages/data-types/bin/data-types.js, packages/data-types/package.json, packages/data-types/src/command.ts, packages/data-types/src/datatype.ts, packages/data-types/src/graphql-helper.ts, packages/data-types/src/interfaces.ts, packages/data-types/src/types/versions/v1/date.ts, packages/data-types/src/types/versions/v1/object.ts, packages/data-types/test/data-type-spec.ts, packages/data-types/test/graphql-types-spec.ts, packages/data-types/test/types/v1/date-spec.ts, packages/data-types/test/types/v1/object-spec.ts, packages/ui-data-access/package.json
this provides a basic cli for using data-types
-h shows commands, parameters and examples
=> Data type cli

packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/ui-components/package.json, packages/ui-components/src/DataTable/DataTable.tsx, packages/ui-components/src/DataTable/Toolbar.tsx, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/xlucene-evaluator/package.json, packages/xlucene-evaluator/peg/lucene.pegjs, packages/xlucene-evaluator/test/cases/parser/geo.ts
=> Misc data access fixes

packages/data-access-plugin/package.json, packages/teraslice/package.json, yarn.lock
This release doesn't include any notable changes
=> Release v0.53.0

packages/data-access-plugin/package.json, packages/job-components/package.json, packages/job-components/src/execution-context/api.ts, packages/job-components/src/execution-context/worker.ts, packages/job-components/src/operation-loader.ts, packages/job-components/src/operations/core/operation-core.ts, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json
This will ensure apis are loaded before the processors. Additionally this has development improvements.
=> v0.53.2 - Fix job components

packages/data-access-plugin/package.json, packages/data-access-plugin/src/manager/types/user.ts, packages/data-access-plugin/src/spaces/types/user.ts, packages/data-access/package.json, packages/data-access/src/acl-manager.ts, packages/data-access/src/interfaces.ts, packages/data-access/src/models/config/spaces.ts, packages/data-access/src/models/config/users.ts, packages/data-access/src/models/users.ts, packages/data-access/test/acl-manager-permissions-spec.ts, packages/data-access/test/acl-manager-spec.ts, packages/ui-components/package.json, packages/ui-components/src/interfaces.ts, packages/ui-components/src/utils.ts, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/ui-data-access/src/DataType/routes.ts, packages/ui-data-access/src/Space/Form/index.tsx, packages/ui-data-access/src/Space/routes.ts, packages/ui-data-access/src/View/routes.ts
This PR adds support for the `DATAADMIN` user type.
=> Add DATAADMIN user type 

.travis.yml, packages/data-access-plugin/package.json, packages/job-components/package.json, packages/teraslice-cli/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/teraslice/test/test.setup.js, scripts/build-cleanup.sh, scripts/publish-packages.sh, scripts/run-tests.sh, yarn.lock
Ensure we keep node:8 compatibility
=> Run node 8 in travis

packages/data-access-plugin/package.json, packages/data-access-plugin/src/manager/resolvers/view.ts, packages/data-access-plugin/src/manager/types/view.ts, packages/data-access-plugin/test/manager-plugin-spec.ts, packages/data-access/package.json, packages/data-access/src/acl-manager.ts, packages/data-access/src/models/views.ts, packages/data-access/test/acl-manager-spec.ts, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-model.ts, packages/elasticsearch-store/test/index-model-spec.ts, packages/teraslice-cli/generators/new-asset/templates/asset/package.json, packages/ui-components/package.json, packages/ui-components/src/RecordForm/index.tsx, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/ui-data-access/src/ModelList/LinkList.tsx, packages/ui-data-access/src/Space/config.ts, packages/ui-data-access/src/User/config.ts, packages/ui-data-access/src/View/Form/index.tsx, packages/ui-data-access/src/View/config.ts, packages/ui-data-access/src/View/interfaces.ts, packages/utils/src/utils.ts
Resolves #1172 
Resolves #1173
=> Fix data access issues

packages/ui-components/package.json, packages/ui-components/src/PluginService.ts, packages/ui-core/index.js, packages/ui-core/package.json, packages/ui-core/src/index.tsx, packages/ui-data-access/package.json, packages/ui-data-access/src/utils.ts
Fix multiple reloads when plugins loaded too late.
Fix the data type field validation (allow 1 or 2 characters)
=> Fixes to ui core

packages/chunked-file-reader/package.json, packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/job-components/package.json, packages/terafoundation/package.json, packages/teraslice-messaging/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/ts-transforms/src/interfaces.ts, packages/ts-transforms/src/operations/lib/transforms/extraction.ts, packages/ts-transforms/src/operations/lib/validations/email.ts, packages/ts-transforms/test/operations/transforms/extraction-spec.ts, packages/ts-transforms/test/operations/validations/email-spec.ts, packages/ui-components/package.json, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/utils/package.json, packages/utils/src/interfaces.ts, packages/utils/src/strings.ts, packages/xlucene-evaluator/package.json
To use multiple capturing regex groups you need to specify multivalue:true on the ts-transforms config.
=> Ts transforms updates

packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/data-types/src/interfaces.ts, packages/elasticsearch-store/package.json, packages/ui-core/package.json, packages/ui-data-access/package.json
The new data types were missing from the UI now they should be there
=> Build UI with new data types

packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/utils.js, packages/teraslice/package.json, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/utils-spec.js
Fix issue where we set max old spaces to bytes instead of the expected megabytes
=> v0.54.10 Fixes to max old space

packages/chunked-file-reader/package.json, packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-messaging/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-state-storage/src/cached-state-storage/index.ts, packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts, packages/teraslice-state-storage/src/interfaces.ts, packages/teraslice-state-storage/test/cache-state-storage-spec.ts, packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/ui-components/package.json, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/utils/bench/map-suite.js, packages/utils/package.json, packages/utils/src/big-map.ts, packages/utils/src/data-entity.ts, packages/utils/src/index.ts, packages/utils/test/big-map-spec.ts, packages/xlucene-evaluator/package.json
Add a `BigMap` class that will use multiple `Map`s to `@terascope/utils` and use it within `teraslice-state-storage`
=> Add BigMap util to allow cache allocation to above 16million keys

packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-access/src/search-access.ts, packages/data-access/test/search-access-spec.ts, packages/ui-components/package.json, packages/ui-data-access/package.json
Fix issue when setting `max_query_size` to `0` but it gets converted to the default `100000`
Resolves #1314
=> Fix max query size

packages/scripts/package.json, packages/scripts/src/cmds/bump.ts, packages/scripts/src/cmds/publish.ts, packages/scripts/src/cmds/test.ts, packages/scripts/src/command.ts, packages/scripts/src/helpers/args.ts, packages/scripts/src/helpers/bump/index.ts, packages/scripts/src/helpers/misc.ts, packages/scripts/src/helpers/publish/index.ts, packages/scripts/src/helpers/publish/utils.ts, packages/scripts/src/helpers/sync/index.ts
Fix missing `daily` prefix in daily docker builds
Improved script error messages
Fix script examples
Slight improvements to scripts usage and help
=> Fix daily builds and improved scripts

packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/data-types/src/types/versions/v1/hostname.ts, packages/data-types/src/types/versions/v1/keyword-path-analyzer.ts, packages/data-types/test/types/v1/hostname-spec.ts, packages/data-types/test/types/v1/keyword-path-analyzer-spec.ts, packages/elasticsearch-store/package.json, packages/ui-data-access/package.json
* removed pattern from path_analyzer and changed it's name to path_analyzer from path tokenizer
* added lowercase_keyword_analyzer to analyzers and changed type of hostname from keyword to text
* updated tests
addresses issue #1376
=> Keyword path analyzer fix

packages/data-access-plugin/package.json, packages/job-components/package.json, packages/job-components/src/register-apis.ts, packages/job-components/test/register-apis-spec.ts, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json
Fail loudly on job-components `getClient`, fixes #1390
=> Fail loudly on getClient

packages/chunked-file-reader/package.json, packages/data-access-plugin/package.json, packages/data-access/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/generator-templates/new-asset/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/ui-components/package.json, packages/ui-core/package.json, packages/ui-data-access/package.json, packages/utils/package.json, packages/utils/src/arrays.ts, packages/utils/src/entities/data-entity.ts, packages/utils/src/entities/interfaces.ts, packages/utils/src/entities/utils.ts, packages/utils/src/objects.ts, packages/utils/test/data-entity-spec.ts, packages/xlucene-evaluator/package.json
Fix issue when using `cloneDeep` and the `DataEntity`. These changes have a slight performance decrease but it probably won't be noticable.
=> v0.56.2 - Fixes to DataEntity changes

packages/teraslice/lib/cluster/services/cluster/backends/native/index.js, packages/teraslice/package.json
Fix unhandled promises in native clustering
=> v0.56.3 - Minor fixes to native clustering

packages/scripts/package.json, packages/scripts/src/cmds/test.ts, packages/scripts/src/helpers/test-runner/index.ts, packages/scripts/src/helpers/test-runner/utils.ts, packages/scripts/test/test-runner-spec.ts
=> Fix test scripts when running in watch mode

package.json, packages/eslint-config/package.json, yarn.lock
Bump eslint-typescript packages and bump eslint-config
=> Bump eslint-typescript packages

packages/data-types/package.json, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
certain packages where not bumped with the xlucene changes
=> bump version for previous xlucene changes

packages/eslint-config/package.json, yarn.lock
Bump eslint packages to include the latest `eslint-plugin-react` with specific bug fixes for our react projects.
=> Bump eslint packages

package.json, yarn.lock
Fix dependency security issues and weird duplicate dependency issues
=> Fix dependency security issues

packages/data-types/package.json, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/xlucene-evaluator/package.json, packages/xlucene-evaluator/peg/lucene.pegjs, packages/xlucene-evaluator/src/translator/utils.ts, packages/xlucene-evaluator/test/cases/parser/terms.ts, packages/xlucene-evaluator/test/cases/translator/term.ts, packages/xlucene-evaluator/test/query-access-spec.ts, packages/xlucene-evaluator/test/translator-spec.ts
- can now parse values with quotes at the start and end
=> quoted values parser fixes

e2e/package.json, packages/chunked-file-reader/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-model.ts, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/strings.ts, packages/utils/test/strings-spec.ts, packages/xlucene-evaluator/package.json, packages/xlucene-evaluator/peg/lucene.pegjs, packages/xlucene-evaluator/src/interfaces.ts, packages/xlucene-evaluator/src/utils.ts, packages/xlucene-evaluator/test/cases/parser/terms.ts, packages/xlucene-evaluator/test/cases/translator/term.ts, yarn.lock
Fixes issues with escaping xlucene values and adds a `createJoinQuery` utility.
=> xLucene escape/join fixes

.travis.yml, Dockerfile, package.json, packages/teraslice/package.json
See https://github.com/terascope/kafka-assets/pull/138
=> v0.59.1 - update terafoundation kafka connector

packages/data-types/package.json, packages/data-types/src/data-type.ts, packages/data-types/src/graphql-helper.ts, packages/data-types/src/interfaces.ts, packages/data-types/src/types/versions/base-type.ts, packages/data-types/test/data-type-spec.ts, packages/elasticsearch-store/package.json
- Fixes Data Type GraphQL validation
- Add a description to data type field config
- Add a description option for a data type
=> Add descriptions to DataType

packages/data-types/package.json, packages/data-types/src/data-type.ts, packages/data-types/src/utils.ts, packages/data-types/test/data-type-spec.ts, packages/elasticsearch-store/package.json
=> Fix multi-line graphql comments in data-types

docs/configuration/clustering-k8s.md, e2e/package.json, examples/k8s/Makefile, examples/k8s/example-job-labels.json, examples/k8s/example-job-targets.json, examples/k8s/teraslice-master.yaml.tpl, examples/k8s/teraslice-worker.yaml.tpl, package.json, packages/job-components/package.json, packages/job-components/src/interfaces/context.ts, packages/job-components/src/interfaces/jobs.ts, packages/job-components/src/job-schemas.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/lib/config/schemas/system.js, packages/teraslice/package.json, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
This MR addresses the following issues:
* #1546
=> K8s winter 2019 b1

package.json, packages/teraslice/lib/cluster/services/api.js, packages/teraslice/lib/cluster/services/jobs.js, packages/teraslice/lib/storage/analytics.js, packages/teraslice/lib/storage/backends/elasticsearch_store.js, packages/teraslice/lib/storage/execution.js, packages/teraslice/lib/storage/jobs.js, packages/teraslice/lib/storage/state.js, packages/teraslice/lib/utils/api_utils.js, packages/teraslice/package.json, packages/utils/src/numbers.ts
- Fix parsing and defaults for size and from query params
- Be consistent with store/service search / get methods
=> v0.62.2 - Fix size queries

packages/teraslice-test-harness/package.json, packages/teraslice-test-harness/src/slicer-test-harness.ts, packages/teraslice-test-harness/test/slicer-test-harness-spec.ts
- makes test harness work with autorecover changes to recoveryData lastSlice
=> Test harness fix

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/deps.ts, packages/utils/test/data-entity-spec.ts, packages/utils/test/promises-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json
- fix metadata keys that were enumerable when clonedeeping dataentities
=> patch of dataentity clonedeep keys

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/deps.ts, packages/utils/src/objects.ts, packages/utils/test/data-entity-spec.ts, packages/utils/test/deps-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json
Objects created via `Object.create(null)` we not being cloned properly and checked properly in `isPlainObject`. Classes weren't cloned properly either since the constructor was initialized without an arguments.
=> Fix clone deep

packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-manager.ts, packages/elasticsearch-store/src/index-model.ts, packages/elasticsearch-store/src/index-store.ts, packages/elasticsearch-store/src/interfaces.ts, packages/teraslice/lib/storage/execution.js, packages/teraslice/lib/storage/jobs.js, scripts/upgrade.sh, tsconfig.json
- disabled by default - unless `process.env.NODE_ENV === test`
=> Add option to elasticsearch-store to enable index mutation

packages/data-mate/package.json, packages/data-mate/src/interfaces.ts, packages/data-mate/src/transforms/field-transform.ts, packages/data-mate/src/transforms/record-transform.ts, packages/data-mate/src/validations/field-validator.ts, packages/data-mate/src/validations/record-validator.ts, packages/data-mate/test/record_transform-spec.ts, packages/data-types/package.json, packages/data-types/src/interfaces.ts, packages/data-types/src/types/mapping.ts, packages/data-types/src/types/v1/any.ts, packages/data-types/test/types/v1/any-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/types/src/elasticsearch-interfaces.ts
- added "Any" data-type
- initial changes for directive support in spaces
=> Directive support in data-mate

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/logger.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xlucene-translator/src/translator/utils.ts, packages/xlucene-translator/test/cases/translator/term.ts
- Fix handling of wildcard queries on analyzed fields
- Fix debugLogger to not create repeating namespaces for loggers
=> Fix xlucene case sensitivity

package.json, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8s.js, packages/teraslice/package.json
This should address the undefined response from the API ... refs: #1827
=> test for undefined responses

packages/data-mate/package.json, packages/data-mate/test/lib/cases/document-matcher/basic-terms-and-logic.ts, packages/data-mate/test/lib/cases/document-matcher/complex-queries.ts, packages/data-mate/test/lib/cases/document-matcher/dates.ts, packages/data-mate/test/lib/cases/document-matcher/geo.ts, packages/data-mate/test/lib/cases/document-matcher/interfaces.ts, packages/data-mate/test/lib/cases/document-matcher/ip.ts, packages/data-mate/test/lib/cases/document-matcher/range.ts, packages/data-mate/test/lib/cases/document-matcher/regexp.ts, packages/data-mate/test/lib/cases/document-matcher/wildcard.ts, packages/data-mate/test/lib/document-matcher-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json, packages/xlucene-parser/package.json, packages/xlucene-parser/src/context.ts, packages/xlucene-parser/test/cases/parser/wildcard.ts, packages/xlucene-translator/package.json
- adds better differentiation of string variable values to better detect regex and wildcard values.
- adds tests to DocumentMatcher to verify changes there
=> xLucene parser fix for wildcard variable values

e2e/yarn.lock, package.json, packages/eslint-config/lib/overrides.js, packages/eslint-config/package.json, packages/eslint-config/test/index-spec.js, yarn.lock
This will help use find issues when using [react hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)
=> Use the recommended react hook linting

packages/elasticsearch-api/index.js, packages/elasticsearch-api/package.json, packages/elasticsearch-api/test/api-spec.js, packages/teraslice-state-storage/package.json, packages/teraslice/package.json
* added track_total_hits to _buildRangeQuery
* bumped version
* updated tests
=> Elasticsearch api track total hits

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/deps.ts, packages/utils/src/promises.ts, packages/utils/test/deps-spec.ts, packages/utils/test/promises-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, yarn.lock
The `pMap` util I wrote didn't handle concurrency correctly, this just switches to using https://www.npmjs.com/package/p-map
=> Fix pMap in utils

e2e/test/cases/data/recovery-spec.js
- this fixes the old inconsistent way of making a slice of data-generator
=> fix data generator slices from old inconsistent ways to current object

.travis.yml, Dockerfile, docs/development/releases.md, e2e/test/download-assets.js, package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/job-components/package.json, packages/teraslice-messaging/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json
We will keep this PR open until we verify node 12 works in productions and is stable. New version can be released in parallel, this will just have to rebase and bump again when it changes.
Close https://github.com/terascope/teraslice/issues/1500
=> v0.67.0 - Teraslice with Node 12

packages/job-components/package.json, packages/job-components/src/interfaces/misc.ts, packages/job-components/src/operations/api-factory.ts, packages/job-components/src/operations/index.ts, packages/job-components/test/fixtures/api-factory/api.ts, packages/job-components/test/fixtures/api-factory/schema.ts, packages/job-components/test/operations/api-factory-spec.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json
- added the APIFactory class to job-components
=> Api factory

docs/jobs/types-of-operations.md, packages/job-components/package.json, packages/job-components/src/execution-context/slicer.ts, packages/job-components/src/execution-context/worker.ts, packages/job-components/src/operations/core/api-core.ts, packages/job-components/src/operations/core/operation-core.ts, packages/job-components/src/operations/core/schema-core.ts, packages/job-components/src/operations/core/slicer-core.ts, packages/job-components/test/operations/core/slicer-core-spec.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice-test-harness/src/slicer-test-harness.ts, packages/teraslice/package.json
- added apis to slice-core
- some type updates
- added api access to test-harness for slicers
=> Slicer api lifecycles

packages/scripts/package.json, packages/scripts/src/helpers/docs/sidebar.ts, packages/scripts/src/helpers/packages.ts, website/sidebars.json
This fixes `ts-scripts` to properly add missing package docs to the sidebar
=> Fix missing package docs

packages/data-mate/package.json, packages/elasticsearch-store/package.json, packages/job-components/package.json, packages/job-components/src/execution-context/base.ts, packages/job-components/src/execution-context/slicer.ts, packages/job-components/src/execution-context/worker.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/xlucene-parser/bench/parser-suite.js, packages/xlucene-parser/package.json, packages/xlucene-parser/scripts/test-query.js, packages/xlucene-parser/src/context.ts, packages/xlucene-parser/src/interfaces.ts, packages/xlucene-parser/src/parser.ts, packages/xlucene-parser/src/utils.ts, packages/xlucene-parser/test/parser-spec.ts, packages/xlucene-translator/package.json, packages/xlucene-translator/src/query-access/query-access.ts, packages/xlucene-translator/src/translator/translator.ts
- Log operation start/shutdown
- Fix xLucene benchmark
- Fix xLucene error message
- Reduce xLucene logs via Bunyan (so it trace doesn't become unusable)
=> Log operation start/shutdown

packages/teraslice-state-storage/package.json, packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts, packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts
* addresses issue #2158 
* bumped version to 0.18.3
* added test case for evicting keys in the incoming slice
=> State storage eviction fix

packages/scripts/package.json, packages/scripts/src/cmds/test.ts, packages/scripts/src/helpers/bump/index.ts, packages/scripts/src/helpers/bump/utils.ts, packages/scripts/src/helpers/config.ts, packages/scripts/src/helpers/interfaces.ts, packages/scripts/src/helpers/publish/utils.ts, packages/scripts/src/helpers/scripts.ts, packages/scripts/src/helpers/sync/utils.ts, packages/scripts/src/helpers/test-runner/interfaces.ts, packages/scripts/src/helpers/test-runner/services.ts, packages/utils/src/promises.ts, packages/utils/test/promises-spec.ts
- Adds MinIO service support to ts-scripts
- Adds `linkToMain` package.json config to keep version in sync with main package
=> Add MinIO and linkToMain to ts-scripts

packages/scripts/package.json, packages/scripts/src/helpers/sync/configs.ts, packages/scripts/src/helpers/test-runner/utils.ts
I forgot forward the env for MinIO to the tests in my last PR https://github.com/terascope/teraslice/pull/2174
=> Expose MinIO config to tests

packages/ts-transforms/package.json, packages/ts-transforms/src/operations/plugins/data-mate/FieldValidator.ts, packages/ts-transforms/test/data-mate-integration-spec.ts
* adresses issue #2183  
* refactored data-mate plugin
* bumped ts-transforms to v0.42.1
=> Ts transforms data mate integration fix

.travis.yml, Dockerfile, package.json, packages/teraslice/package.json
- bump node to 12.19.0
- release: (patch) teraslice@0.71.1
=> v0.71.1 - Update node to 12.19 in Dockerfile

packages/data-mate/src/data-frame/DataFrame.ts, packages/data-mate/test/data-frame-spec.ts
- Fix issue with DataFrame.limit
- Add DataFrame->toArray
- Fix unnecessary call to Object.entries() in getRow
=> Fix DataFrame->limit and other fixes

packages/data-mate/package.json, packages/data-mate/src/column/aggregations.ts, packages/data-mate/test/aggregation-frame-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
DataFrames `count` aggregations will counting null values, this is incorrect as it breaks unique value counts
=> Fix dataframe count with null values

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/geo.ts, packages/utils/test/geo-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-parser/src/functions/geo/box.ts, packages/xlucene-parser/src/functions/geo/contains-point.ts, packages/xlucene-parser/src/functions/geo/distance.ts, packages/xlucene-parser/src/functions/geo/polygon.ts, packages/xlucene-parser/src/functions/index.ts, packages/xlucene-parser/src/parser.ts, packages/xlucene-translator/package.json
- Improves error message geo shape input
- Fixes error when given an invalid geo function
- Adds `forEachTermNode` to xlucene Parser
=> Improve xLucene geo shape validation

packages/scripts/package.json, packages/scripts/src/helpers/test-runner/services.ts
- increase the script timeout for setting up elasticsearch and minio
=> Script timeout

packages/data-mate/package.json, packages/data-mate/src/aggregation-frame/AggregationFrame.ts, packages/data-mate/src/aggregation-frame/utils.ts, packages/data-mate/src/vector/utils.ts, packages/data-mate/test/aggregation-frame-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
Fixes the use value aggregations on Tuple field types
=> DataFrame Aggs now work with Tuples

Dockerfile, package.json, packages/eslint-config/package.json, packages/scripts/package.json, packages/scripts/src/helpers/docs/typedoc.ts, packages/teraslice/package.json, packages/xlucene-parser/package.json, yarn.lock
Update dependencies, fix building docs and docker image to use node `v12.20.1` which has some security fixes
=> v0.71.2 - Update deps and docker image

e2e/package.json, packages/scripts/package.json, packages/scripts/src/helpers/scripts.ts, packages/scripts/src/helpers/test-runner/services.ts, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-cli/src/cmds/assets/build.ts, packages/teraslice-cli/src/cmds/assets/deploy.ts, packages/teraslice-cli/src/helpers/asset-src.ts, packages/teraslice-cli/test/lib/aliases-spec.ts, packages/teraslice-cli/test/lib/assetsrc-spec.ts, yarn.lock
Changes teraslice-cli zip command to follow symlinks which will improve compatibility with monorepos
=> Change teraslice-cli asset zip to follow symlinks

packages/data-mate/package.json, packages/data-mate/src/aggregation-frame/AggregationFrame.ts, packages/data-mate/src/column/Column.ts, packages/data-mate/src/data-frame/DataFrame.ts, packages/data-mate/test/data-frame-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
- Fixes #2388 since it was only issue because there were multiple copies of data-mate being used.
- Adds additional tests for DataFrame.concat
- Improves some of the debug info
=> Better error in DataFrame.concat

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/types/src/data-types.ts, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
Add is_primary_date and time_resolution to DataTypeFieldConfig
=> add primary date and time resolution to data type field config

packages/ts-transforms/package.json, packages/ts-transforms/src/loader/utils.ts, packages/ts-transforms/test/fixtures/transformRules41.txt, packages/ts-transforms/test/transform-spec.ts
* fixes undefined value in matchRequirements for post_process rules
* added test
* bumped version to 0.51.2
=> ts_transforms fix for post process and other_match_required

package.json, packages/teraslice/lib/storage/backends/mappings/asset.json, packages/teraslice/package.json
- change elasticsearch schema of the asset mapping, changed blob keyword => binary
=> v0.72.0 - Asset schema change

e2e/package.json, package.json, packages/data-types/package.json, packages/eslint-config/lib/overrides.js, packages/eslint-config/package.json, packages/eslint-config/test/index-spec.js, packages/generator-teraslice/package.json, packages/scripts/package.json, packages/scripts/src/helpers/bump/index.ts, packages/scripts/src/helpers/hooks.ts, packages/scripts/src/helpers/interfaces.ts, packages/scripts/src/helpers/sync/index.ts, packages/scripts/src/index.ts, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-test-harness/package.json, packages/teraslice-test-harness/test/dowload-external-asset-spec.ts, packages/teraslice/package.json, yarn.lock
- Add hook to support to ts-scripts to extend the release process
- Ensure using `.mjs` files works with our eslint-config
=> Add hook support to scripts

docs/configuration/clustering-k8s.md, examples/k8s/Makefile, examples/k8s/example-job.json, package.json, packages/job-components/package.json, packages/job-components/src/interfaces/context.ts, packages/job-components/src/interfaces/jobs.ts, packages/job-components/src/job-schemas.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/lib/config/schemas/system.js, packages/teraslice/package.json, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
I've not written the code yet, just finally gotten the build working again.  WIP.
=> Add ephemeral volume

package.json, packages/teraslice/lib/workers/execution-controller/index.js, packages/teraslice/package.json
- Fix marking execution as failed when initializing to prevent jobs from being stuck in the initializing state
=> v0.73.2 - Execution Controller initialize fix

packages/eslint-config/package.json, packages/scripts/package.json, packages/scripts/src/helpers/bump/index.ts, packages/scripts/src/helpers/hooks.ts, packages/scripts/src/helpers/packages.ts, packages/scripts/src/helpers/sync/configs.ts, packages/scripts/src/helpers/sync/index.ts, packages/scripts/src/helpers/sync/utils.ts, packages/scripts/test/sync-spec.ts
=> Fixes to ts-scripts syncing and hooks

packages/data-mate/package.json, packages/data-mate/src/validations/field-validator.ts, packages/data-mate/test/field_validator-spec.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/numbers.ts, packages/utils/test/number-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
* fixed false positive bug in isBase64 field validation
* fixed inNumberRange bug where if 0 is min or max sets limit to infinity
* bumped utils version to  0.34.2
* bumped data-mate version to 0.25.1
=> data-mate and utils update

package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/data-types/src/interfaces.ts, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/eslint-config/lib/rules/typescript.js, packages/eslint-config/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/scripts/src/helpers/sync/configs.ts, packages/terafoundation/package.json, packages/terafoundation/test/index-spec.ts, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/interfaces.ts, packages/xlucene-parser/package.json, packages/xlucene-parser/test/utils-spec.ts, packages/xlucene-translator/package.json, packages/xpressions/package.json, tsconfig.json, yarn.lock
Updates a couple dependencies since they're blocked in other dependabot PRs
=> Updates dependencies

packages/data-mate/package.json, packages/data-mate/src/validations/field-validator.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
* moved ip range parsing outside of function so they are parsed once
* bumped version
=> Ip routing check speed up

packages/data-mate/package.json, packages/data-mate/src/builder/types/ObjectBuilder.ts, packages/data-mate/src/builder/types/TupleBuilder.ts, packages/data-mate/src/column/Column.ts, packages/data-mate/src/data-frame/DataFrame.ts, packages/data-mate/src/data-frame/utils.ts, packages/data-mate/src/vector/Vector.ts, packages/data-mate/test/data-frame-spec.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/types/src/data-types.ts, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Fix `DataFrame.deepSelect` to not all of object values in some cases
- Add `DataFrame.removeEmptyRows` which is a performance optimized was of removing empty objects for a given output
- Add `Vector.has` to see a non-nil value exists in a `Vector`
=> Fix DataFrame.deepSelect and add DataFrame.removeEmptyRows

packages/data-mate/package.json, packages/data-mate/src/data-frame/DataFrame.ts, packages/data-mate/test/data-frame-spec.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
Fix `DataFrame.appendAll` when the input frame is empty
=> Fix DataFrame.appendAll

packages/data-mate/src/function-configs/date/index.ts, packages/data-mate/src/function-configs/date/isAfter.ts, packages/data-mate/src/function-configs/date/isBefore.ts, packages/data-mate/src/function-configs/date/isBetween.ts, packages/utils/src/dates.ts, packages/utils/test/dates-spec.ts
* date-mate/ utils functions isBefore, isAfter, isBetween
=> IsBefore, isAfter,  isBetween

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-messaging/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-state-storage/src/cached-state-storage/index.ts, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/big-lru-map.ts, packages/utils/src/index.ts, packages/utils/test/big-lru-map-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json, yarn.lock
- Added new class `BigLruMap` that extends `LRUMap` to include `BigMap` and a flexible array to avoid running out of memory with 11.8 million items in the map.
Closes https://github.com/terascope/teraslice/issues/2703
=> Add big lru map to utils

packages/data-mate/src/function-configs/date/addToDate.ts, packages/data-mate/src/function-configs/date/index.ts, packages/data-mate/src/function-configs/date/isFriday.ts, packages/data-mate/src/function-configs/date/isFuture.ts, packages/data-mate/src/function-configs/date/isLeapYear.ts, packages/data-mate/src/function-configs/date/isMonday.ts, packages/data-mate/src/function-configs/date/isPast.ts, packages/data-mate/src/function-configs/date/isSaturday.ts, packages/data-mate/src/function-configs/date/isSunday.ts, packages/data-mate/src/function-configs/date/isThursday.ts, packages/data-mate/src/function-configs/date/isToday.ts, packages/data-mate/src/function-configs/date/isTomorrow.ts, packages/data-mate/src/function-configs/date/isTuesday.ts, packages/data-mate/src/function-configs/date/isWednesday.ts, packages/data-mate/src/function-configs/date/isWeekday.ts, packages/data-mate/src/function-configs/date/isWeekend.ts, packages/data-mate/src/function-configs/date/isYesterday.ts, packages/data-mate/src/function-configs/date/subtractFromDate.ts, packages/data-mate/src/function-configs/date/toDate.ts, packages/data-mate/src/function-configs/interfaces.ts, packages/data-mate/src/function-configs/numeric/index.ts, packages/data-mate/src/function-configs/numeric/toNumber.ts, packages/data-mate/src/function-configs/string/endsWith.ts, packages/data-mate/src/function-configs/string/index.ts, packages/data-mate/src/function-configs/string/startsWith.ts, packages/data-mate/test/function-configs/function-configs-spec.ts, packages/utils/package.json, packages/utils/src/dates.ts, packages/utils/src/strings.ts
added several functions to dates, strings and added toNumber
=> Add in several date functions, and other string functions

packages/data-mate/src/function-configs/date/getDate.ts, packages/data-mate/src/function-configs/date/getHours.ts, packages/data-mate/src/function-configs/date/getMilliseconds.ts, packages/data-mate/src/function-configs/date/getMinutes.ts, packages/data-mate/src/function-configs/date/getMonth.ts, packages/data-mate/src/function-configs/date/getSeconds.ts, packages/data-mate/src/function-configs/date/getYear.ts, packages/data-mate/src/function-configs/date/index.ts, packages/utils/src/dates.ts, packages/utils/test/dates-spec.ts
functions:
* getMilliseconds
* getSeconds
* getMinutes
* getHours
* getDate
* getMonth
* getYear
Question on getDate - that could be confused with a complete date, not day of the month.  Maybe it should be getDayOfMonth?
=> Get years months date hours min sec msec functions

packages/data-mate/src/function-configs/object/index.ts, packages/data-mate/src/function-configs/object/lookup.ts, packages/utils/src/objects.ts, packages/utils/test/objects-spec.ts
lookup function - 
There's a few spots here that I'm not sure of:
* seems like the utils function should check if the lookup object is an actual object, or should the type determine that?
* also I have the arg as the lookup object and the input as the key to support the fp style, but that feels backwards to me like the arg should be the key and the input should be the lookup arg
=> Lookup function

packages/data-mate/src/data-frame/DataFrame.ts, packages/data-mate/src/vector/Vector.ts, packages/data-mate/test/data-frame-spec.ts
Ensure that `DataFrame.appendAll` will correctly deal with varying fields
=> Ensure that DataFrame.appendAll will add varying fields if needed

docs/packages/data-mate/functions.md
functions.md updated to the new function descriptions
=> updated functions.md

packages/teraslice-cli/package.json, packages/teraslice-cli/src/cmds/assets/deploy.ts, packages/teraslice-cli/src/helpers/asset-src.ts, packages/teraslice-cli/src/helpers/github-asset.ts, packages/teraslice-cli/src/interfaces.ts, packages/teraslice-cli/test/lib/github-asset-spec.ts
This implements the JS asset build.
=> add support for JS asset bundle refs: 2748

package.json, packages/data-mate/test/data-frame-spec.ts, packages/scripts/package.json, packages/utils/src/numbers.ts, packages/xlucene-parser/src/parser.ts, yarn.lock
Reverts terascope/teraslice#2757
=> Revert "Bump typescript from 4.2.4 to 4.3.2"

packages/data-mate/src/function-configs/object/lookup.ts, packages/utils/src/objects.ts, packages/utils/test/objects-spec.ts
changes to lookup function to accept formatted strings and arrays
=> lookup function changes, updated tests

e2e/docker-compose.yml, packages/scripts/package.json, packages/scripts/src/helpers/config.ts, packages/scripts/src/helpers/misc.ts, packages/scripts/src/helpers/test-runner/index.ts
Add support for overriding the docker dev image and registry to ts-scripts
=> Allow dev docker image override

package.json, packages/teraslice/lib/utils/asset_utils.js, packages/teraslice/lib/workers/helpers/worker-shutdown.js, packages/teraslice/lib/workers/worker/index.js, packages/teraslice/package.json, packages/teraslice/worker-service.js
- Add better exit log message with status code
- Ensure that the slice gets marked as failed if there is an expected error
- Ensure that older versions of node work on newer versions of teraslice
=> v0.77.1 - Add better error handling for unhandled errors or rejections

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/field-type.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json, yarn.lock
Reverts terascope/teraslice#2811
=> Revert "Utils fix"

packages/data-mate/package.json, packages/data-mate/src/adapters/data-frame-adapter/index.ts, packages/data-mate/src/column/utils.ts, packages/data-mate/src/function-configs/date/setTimezone.ts, packages/data-mate/src/function-configs/date/timezoneToOffset.ts, packages/data-mate/src/function-configs/interfaces.ts, packages/data-mate/src/function-configs/json/cast.ts, packages/data-mate/src/function-configs/json/index.ts, packages/data-mate/test/function-configs/function-configs-spec.ts, packages/data-mate/test/function-configs/functionTestHarness.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/dates.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
=> Data mate functions

packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/utils/retry-config.ts
- Add `node_disconnect_exception` to index store retries
=> Add node_disconnect_exception to index store retries

packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-manager.ts, packages/elasticsearch-store/src/utils/elasticsearch.ts, packages/elasticsearch-store/test/helpers/simple-index.ts, packages/elasticsearch-store/test/index-manager-index-setup-spec.ts, packages/elasticsearch-store/test/index-manager-migrate-spec.ts, packages/elasticsearch-store/test/index-model-spec.ts, packages/elasticsearch-store/test/index-store-spec.ts, packages/elasticsearch-store/test/index-store-timeseries-spec.ts
- Update tests to have an indexed nested property
- Fix spelling in index-model-spec
- Correctly detect index field mapping changes, mainly when a nested field changes
=> Fix index change detection in elasticsearch-store

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/types/src/geo-interfaces.ts, packages/utils/package.json, packages/utils/src/field-type.ts, packages/utils/src/geo.ts, packages/utils/src/numbers.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Remove cached check for geo points that uses `WeakSet` since doesn't scale with the V8 garbage collector
- Improve performance of `parseGeoPoint` by creating a "hot path" for our ideal geo point data structure
=> Improve Geo Point Performance

packages/data-mate/package.json, packages/data-mate/src/aggregation-frame/AggregationFrame.ts, packages/data-mate/src/column/aggregations.ts, packages/data-mate/src/data-frame/DataFrame.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/bench/map-suite.js, packages/utils/package.json, packages/utils/src/big-map.ts, packages/utils/src/big-set.ts, packages/utils/src/dates.ts, packages/utils/test/big-map-spec.ts, packages/utils/test/big-set-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Improve aggregation performance by doing less
- Improve column lookup by name performance
- Improve date performance (minor)
- Fix `BigMap` and `BigSet` API to be more compatible with `Set` and `Map`
=> Improve aggregation/data frame performance

packages/scripts/package.json, packages/scripts/src/cmds/test.ts, packages/scripts/src/helpers/scripts.ts, packages/scripts/src/helpers/test-runner/interfaces.ts, packages/scripts/src/helpers/test-runner/services.ts
-hard code the docker image that has the config file overrides built in
=> Rabbit test fix

packages/scripts/package.json, packages/scripts/src/helpers/config.ts, packages/scripts/src/helpers/test-runner/services.ts
- made timeout configurable
- made host locally bound for rabbitmq
=> More env fixes

packages/scripts/package.json, packages/scripts/src/helpers/config.ts, packages/scripts/src/helpers/test-runner/services.ts
- make sure code checks management port url
=> Management port check

packages/data-mate/package.json, packages/data-mate/src/vector/ListVector.ts, packages/data-mate/test/vector/list-vector-spec.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/empty.ts, packages/utils/src/index.ts, packages/utils/src/iterators.ts, packages/utils/test/empty-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Add `ListVector.getRowIterator` so we can iterate over values in a given row
- Add `isIterator` and `isAsyncIterator` to utils
- Fix `isEmpty` thinking that the iterators are empty
=> Add ListVector.getRowIterator and improve iterator support in utils

README.md, packages/data-mate/package.json, packages/data-mate/src/function-configs/numeric/setPrecision.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-manager.ts, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/numbers.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Fix non-timeseries template index pattern to not include wildcard
- Allow NaN and Infinity with setPrecision
=> Fix index mapping and setPrecision

Dockerfile, docs/configuration/clustering-k8s.md, examples/k8s/Makefile, package.json, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/package.json, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
This PR will address the issues in the following milestone:
https://github.com/terascope/teraslice/milestone/8
=> K8s improvements summer 2021

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/promises.ts, packages/utils/test/promises-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
-fixed issue on waiting for half time out timeout when jitter is enabled
=> Pwhile fix

packages/data-mate/package.json, packages/data-mate/src/data-frame/DataFrame.ts, packages/elasticsearch-store/package.json, packages/ts-transforms/package.json
Change DataFrame.toJSON and similar functions to output DataEntities for better interop between or other libraries
=> Change DataFrame toJSON to return DataEntities

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/index.js, packages/elasticsearch-api/package.json, packages/elasticsearch-api/test/api-spec.js, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/arrays.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- Adds `chunkIter` util
- Fix affected row count by not counting 404 items in the result in `bulkSend`
=> Add chunk iterator util and fix affected rows

packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- fixed issue that the types changes were not picked up
=> bump types pacakge

packages/scripts/package.json, packages/scripts/src/helpers/scripts.ts, packages/scripts/src/helpers/test-runner/services.ts, packages/scripts/test/scripts-spec.ts, packages/scripts/test/service-spec.ts, packages/scripts/test/test.setup.js, packages/utils/src/promises.ts
* error handling and tests for pulling a bad docker image
* removed xpack commands on opensearch
=> update script error handling and remove xpack commands from opensearch

packages/elasticsearch-store/src/elasticsearch-client/client_wrapper.ts, packages/elasticsearch-store/src/elasticsearch-client/interfaces.ts, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/interfaces.ts, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/msearch.ts, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/reindex.ts, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/search.ts, packages/elasticsearch-store/test/client-wrapper-functions/msearch-spec.ts, packages/elasticsearch-store/test/client-wrapper-functions/ping-spec.ts
=> Client conversion ci

packages/elasticsearch-store/src/elasticsearch-client/client.ts, packages/elasticsearch-store/src/index-manager.ts, packages/elasticsearch-store/test/client-functions-spec.ts
* adjusted tests
* __meta on client
=> changed __meta in client

packages/elasticsearch-store/package.json, packages/terafoundation/package.json, packages/teraslice/package.json, packages/xlucene-translator/package.json, packages/xlucene-translator/src/query-access/query-access.ts, packages/xlucene-translator/test/query-access-spec.ts
Fix Query Access to respect the original included/excluded fields
=> fix to not override original includes/excludes

packages/data-mate/src/vector/Vector.ts
=> linter fixes

packages/xlucene-translator/test/query-access-spec.ts
=> fixed query access tests

.travis.yml, package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/eslint-config/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/scripts/src/helpers/config.ts, packages/scripts/test/test-runner-spec.ts, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
* all unit tests are combined to one suite called unit and 6 shards in travis.yml
=> Master build test fix

packages/elasticsearch-api/index.js, packages/elasticsearch-api/package.json, packages/teraslice-state-storage/package.json, packages/teraslice/package.json
- add types package to elasticsearch-api to help remove errors
=> Package dep fixes

packages/teraslice-cli/package.json, packages/teraslice-cli/src/cmds/assets/init.ts, packages/teraslice-cli/src/helpers/utils.ts, packages/teraslice-cli/src/helpers/yargs-options.ts, packages/teraslice-cli/test/cmds/assets/init-spec.ts
* fixes`Callback support have been removed`  bug for teraslice-cli assets init and it's options
* bumped cli version
=> Teraslice cli assets init fix

e2e/package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/test/client-functions-spec.ts, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/types/src/elasticsearch-client/elasticsearch-params.ts, packages/types/src/elasticsearch-client/elasticsearch-types.ts, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- fix types issues in ClientParams and ClientResponse for elasticsearch/opensearch operations
=> Elastic type fixes

e2e/package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/elasticsearch-client/client.ts, packages/elasticsearch-store/src/test-helpers/elasticsearch.ts, packages/elasticsearch-store/src/utils/elasticsearch.ts, packages/elasticsearch-store/test/client-functions-spec.ts, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/types/package.json, packages/types/src/elasticsearch-client/elasticsearch-response.ts, packages/utils/package.json, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- added tests for the ten missing tests
- fix bad reference in client facade to underlining client
- fix type references
=> Update facade client tests

e2e/package.json, packages/data-mate/package.json, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/big-map.ts, packages/utils/test/big-lru-map-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
* fixes bug where lru cache crashes in cases where with cache size limits at about 8.7M keys to 16.7M keys
* bumped versions
=> LRU cache fix

docs/configuration/clustering-k8s.md, examples/k8s/Makefile, examples/k8s/example-job-with-pod-spec-override.json, examples/k8s/teraslice-master.yaml.tpl, examples/k8s/teraslice-worker.yaml.tpl, package.json, packages/job-components/src/interfaces/context.ts, packages/job-components/src/interfaces/jobs.ts, packages/job-components/src/job-schemas.ts, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/index.js, packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js, packages/teraslice/lib/config/schemas/system.js, packages/teraslice/package.json, packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
I had this working with the example job with the `initContainers` added, that ran and everything so it worked.  I've made some changes since then so it's possible that I broke it again, but its close.  I need to add tests and implement the `kubernetes_overrides_enabled` config setting
refs: 3347
=> K8s update mar 2023

packages/teraslice-cli/package.json, packages/teraslice-cli/test/fixtures/elasticsearch-assets-release.ts
- simplify pull request to just fix asset test to get build working
=> Fix asset deploy tests

packages/scripts/src/helpers/config.ts, packages/scripts/src/helpers/test-runner/services.ts
This branch tries to fix some minor deprecation noise and other things like that.  I don't think it really has much of a chance to fix the opensearch timeout bug.
=> Minor fixes and possible opensearch fix

.github/workflows/publish-master.yml
disable these until we have a chance to fix the issue
=> disable doc tests in CI

e2e/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/test-helpers/elasticsearch.ts, packages/elasticsearch-store/test/client-functions-spec.ts, packages/terafoundation/package.json, packages/teraslice/package.json
- populateIndex was broken and not tested, made sure that tests are using it and fixed bug
=> fix test helper method

e2e/package.json, package.json, packages/elasticsearch-api/index.js, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/indicesPutTemplate.ts, packages/terafoundation/package.json, packages/teraslice-state-storage/package.json, packages/teraslice/package.json
- fix index and template creation methods when using opensearch v2
=> fix startup issue with opensearch v2

.github/workflows/test.yml, package.json, packages/scripts/package.json, packages/scripts/src/helpers/config.ts, packages/terafoundation/package.json, packages/terafoundation/src/connectors/s3.ts, packages/terafoundation/test/validate-configs-spec.ts, packages/teraslice/lib/storage/backends/mappings/ex.json, packages/teraslice/package.json
- fix s3 schema in terafoundation
- change default kafka version for testing to 3.1
=> Store schema chagnes

e2e/package.json, packages/data-mate/package.json, packages/data-mate/src/function-configs/date/index.ts, packages/data-mate/src/function-configs/date/toTimeZone.ts, packages/data-mate/src/function-configs/date/toTimeZoneUsingLocation.ts, packages/data-types/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/generator-teraslice/package.json, packages/job-components/package.json, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice-cli/package.json, packages/teraslice-client-js/package.json, packages/teraslice-messaging/package.json, packages/teraslice-op-test-harness/package.json, packages/teraslice-state-storage/package.json, packages/teraslice-test-harness/package.json, packages/teraslice/package.json, packages/ts-transforms/package.json, packages/utils/package.json, packages/utils/src/dates.ts, packages/utils/test/dates-spec.ts, packages/xlucene-parser/package.json, packages/xlucene-translator/package.json, packages/xpressions/package.json
- added `toTimeZone` and to `toTimeZoneUsingLocation` functions and their corresponding data-mate function definitions
=> Timezone functions

packages/scripts/src/helpers/packages.ts, packages/scripts/src/helpers/test-runner/index.ts
This merge fixes the workspaces issue that is in issue #3413.
=> Ts scripts workspaces test fix

docs/packages/teraslice-cli/overview.md, yarn.lock
```
name                          from     to       workspace
@types/bluebird               3.5.39   3.5.39   teraslice-workspace            
@types/bunyan                 1.8.9    1.8.9    terafoundation                 
@types/convict                6.1.4    6.1.4    teraslice-workspace            
@types/debug                  4.1.9    4.1.9    @terascope/utils               
@types/decompress             4.2.5    4.2.5    teraslice-cli                  
@types/elasticsearch          5.0.41   5.0.41   teraslice-workspace            
@types/elasticsearch          5.0.41   5.0.41   @terascope/elasticsearch-api   
@types/elasticsearch          5.0.41   5.0.41   terafoundation                 
@types/elasticsearch          5.0.41   5.0.41   xlucene-translator             
@types/graphlib …
```
=> Update @types/* if at the patch level

config/docker-teraslice-master.yml, config/docker-teraslice-worker.yml, docker-compose.yml
- Add minio to docker-compose.yml
- Add minio to config/docker-teraslice-master.yml
- Add minio to config/docker-teraslice-worker.yml
ref: https://github.com/terascope/file-assets/issues/229#issuecomment-1743431598
=> Update docker compose to include minio

.github/workflows/publish-tag.yml, package.json, packages/teraslice/package.json
I add the missing yarn setup and bump the version again.
=> release: (patch) teraslice@0.86.4

.github/workflows/publish-master.yml, package.json
=> fix version and disable docs in ci

package.json, packages/data-mate/package.json, packages/elasticsearch-store/package.json, yarn.lock
The following packages are included in this update:
```
Package                          Current   Wanted    Workspace              
@types/bluebird                  3.5.39    3.5.42    teraslice-workspace            
@types/convict                   6.1.4     6.1.6     teraslice-workspace            
@types/debug                     4.1.9     4.1.12    @terascope/utils               
@types/decompress                4.2.5     4.2.7     teraslice-cli                  
@types/elasticsearch             5.0.41    5.0.43    teraslice-workspace            
@types/elasticsearch             5.0.41    5.0.43    @terascope/elasticsearch-api   
@types/elasticsearch             5.0.41    5.0.43    terafoundation                 
@types/elasticsearch             5.0.41    5.0.43    xlucene-translator …
```
=> Dependency updates - patch level and @types

e2e/test/teraslice-harness.js
This PR implements the following changes:
- Fixes reindex e2e test from a false fail by adding additional catch statements proving the job completed
ref to issue #3450
=> Fix reindex e2e test from false fail

package.json, packages/teraslice-cli/package.json, yarn.lock
Revert any changes that were made in #3539, #3541, #3542, #3543, or #3548.
=> Revert resolution change to teraslice-cli and root package.json

packages/teraslice-cli/package.json, packages/teraslice-cli/src/helpers/asset-src.ts, packages/teraslice-cli/src/helpers/yargs-options.ts
Add `node20` to asset `bundle-target` choices array, remove `node14` from array. 
Make `node18` default `bundleTarget`
=> Add node20 to asset bundle-target choices array, remove node14.

e2e/test/cases/assets/simple-spec.ts
Fix an e2e test that double checks that in s3 asset storage mode the asset is not stored in elasticsearch under the `blob` key. I was using `teraslice.assets.list()` which returns asset metadata from ES, but never returns the `blob` key, so the test would always pass. The function now uses the elasticsearch client within the test harness to get the complete records for each asset.
=> Fix e2e s3 asset test that could never fail

Dockerfile.dev, package.json, packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8sResource.ts, packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/k8sResource.ts, yarn.lock
- Fixes bug when running `ts-scripts k8s` where the master, execution contoller, and workers don't properly run their respective exit processes.
Ref to issue #3738
=> [teraslice] Fix teraslice k8s --dev mode process exit bug 

.github/workflows/test.yml, packages/scripts/package.json, packages/scripts/src/helpers/test-runner/services.ts
- Fixes environment variables for Rabbitmq service that prevents a health check from completing
- Updates **@terascope/scripts** from `v1.3.1` to `v1.3.2`
=> [scripts] Update env variables for Rabbitmq

.github/workflows/publish-tag.yml, .github/workflows/test.yml, scripts/check-latest-node-version.sh
- Removes all CI testing for node 20
Ref to issue #3798
=> [CI] Remove node 20 from CI tests

e2e/package.json, packages/elasticsearch-api/index.js, packages/elasticsearch-api/package.json, packages/elasticsearch-api/test/api-spec.js, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/elasticsearch-client/method-helpers/search.ts, packages/terafoundation/package.json, packages/teraslice-state-storage/package.json, packages/teraslice/package.json, yarn.lock
- migrate total tracking logic to the base client search methods
=> Es client total fixes

yarn.lock
The yarn.lock was not synced on the last merge to master.
=> Fix out of sync yarn.lock

package.json, packages/teraslice/package.json
Bump teraslice version for previous PR https://github.com/terascope/teraslice/pull/3952
=> release: (patch) teraslice@2.12.4

e2e/package.json, packages/elasticsearch-api/package.json, packages/elasticsearch-store/package.json, packages/elasticsearch-store/src/index-model.ts, packages/elasticsearch-store/src/utils/elasticsearch.ts, packages/elasticsearch-store/test/index-model-spec.ts, packages/scripts/package.json, packages/terafoundation/package.json, packages/teraslice/package.json, yarn.lock
=> fix recordExists to return false if no id
