- lib/master.js
- lib/readers/elasticsearch_reader.js
- lib/senders/elasticsearch_bulk_insert.js
- lib/senders/hdfs_file_append.js
- lib/senders/kafka_simple_sender.js
- lib/utils/analytics.js
- lib/utils/config.js
- lib/utils/kafka.js
- lib/worker.js
can now specify  "progressive_start": someNumber on the jobConfig level to slowly ramp up the number of workers evenly over that period of time.
you can also specify "connection" and "connection_cache" on the _op level of readers and senders to specify which endpoint to use as well as if the connection should be cached. It will default to the "default" endpoint and cached: true
if errors occured, they will be logged in the end of runs, if "analytics" is set to true, additional information will be logged after the job completes. This currently works for the "once" lifecycle setting as it is meant to terminate after completion.
> resolve tickets

- lib/processors/elasticsearch_index_selector.js
Renamed upsert_fields to update_fields and added 'delete', 'upsert', 'script_file' and 'script_params' parameters to fill out the list of operations.
> Correcting update/upsert functionality and adding delete. fixes #87

- lib/readers/elasticsearch_data_generator.js
- lib/readers/elasticsearch_reader.js
- lib/utils/data_utils.js
- lib/utils/elastic_utils.js
- package.json
- spec/readers/elasticsearch_reader-spec.js
- spec/senders/file_export-spec.js
- spec/utils/data_utils-spec.js
- spec/utils/elastic_utils-spec.js
new additions: 
data generator will now take a "format", "start", and "end" key to change the schema
reader now accepts a "query" key where you can place a lucene query
reader "start" and "end" will now take date math options 
dates are now saved in this format "2016-01-19T13:33:09.356-07:00"
> Data generator fix

- lib/cluster/services/cluster.js
Simple fix, this error happened when i unified the type of data that was being emitted on events. Must have missed this simple change
> fixed worker allocation bug resolves #247

- lib/cluster/storage/backends/mappings/state.json
- lib/cluster/storage/state.js
- lib/readers/elasticsearch_date_range/slicer.js
- lib/readers/elasticsearch_reader.js
- lib/utils/elastic_utils.js
new reader config parameter:  time_resolution ,  it defaults to 'ms', you can specify 's' or 'seconds' for second resolution
> Time resolution

- lib/cluster/services/jobs.js
simple fix, though it only returns the last 10k jobs, is this ok, should the limit be higher especially for systems that have a lot of jobs?
> made sure queue order is maintained or restart resolves #334

- lib/processors/elasticsearch_bulk.js
- lib/utils/elastic_utils.js
unforunatly is was just a simple bug of not passing the proper client and data parameters recursivly.
> fixed recursion of retry of queue overloads resolves #361

- lib/cluster/moderator/index.js
It seems like the error occured when it tried to reinitialize itself, for some reason the call for the moderator to initialized was wrong. This would trigger when ever there was a new node, or major problems with elasticsearch
> fixed moderator with elasticsearch failuires resolves #377 resolves #376

- lib/cluster/worker.js
basically is was placed wrong, the messager was not fully ready by the time the callback was called
> fixed worker to properly exit on getClient errors resolves #405

- spec/moderator/elasticsearch-spec.js
It appears that a few tests were left in "focus" mode in the last PR.  I have remedied that.
> re-enabling all tests

- lib/cluster/storage/backends/mappings/asset.json
On ES5 I received the following error when uploading a larger asset:
```
"error": "[illegal_argument_exception] DocValuesField \"blob\" is too large, must be <= 32766"
```
This PR addresses that by setting `doc_values=true` on the `blob` field.
> setting doc_values=false for asset blob field

- lib/processors/elasticsearch_index_selector.js
This currently only works with painless scripts. It will mainly be useful on ES >5 where painless scripts are enabled by default.
script_params defines the field from the incoming document to copy automatically into params for the script. 
This API currently mirrors how ES it self does this. Ideally we can eventually come with something that is a little less cumbersome to use. Now that scripting is enabled by default there should be many cases where scripts will be useful.
Example usage
```
{
"_op": "elasticsearch_index_selector",
"index": "myindex-v1",
"type": "mytype",
"upsert": true,
"script": "
ctx._source.count += params.count;
if (params.myfield != null) ctx._source.myfield = params.myfield;
",
"script_params" : {
"count": "count",
"myfield": "myfield"
},
"update_retry_on_conflict": …
```
> Adding the ability to use inline scripts on es index selector

- spec/moderator/elasticsearch-spec.js
It seems we've had our tests disabled again.  Not sure if this never got fixed last time I noticed it or what.  Regardless, this PR eliminates the errant `fit` and `fdescribe`.
> removing the fit and fdescribe that disabled most of the tests

- lib/cluster/node_master.js
- Need to discuss if any of the /txt endpoints should default to showing assets or not, not all job will have assets. As it stand now you can still query the assets field but you would have to manually ask for it.
- For now we are displaying the asset id's and not the name and version. Name and version are not always passed, and even if they are they are only used to get the actual id which is used in the system. I might be able to add info on the name and version as well if thats truly needed. 
If a job has assets, the assets will show up in node state when all the assets have been downloaded. It is shown as an array of id's of all the assets used in the job since there may be multiple
> added verison id to workers and slicers in node state resolves #440

- lib/config/validators/config.js
- lib/config/validators/job.js
- spec/config/validators/config-spec.js
To support development of the Teraslice Test harness, specifically
https://github.com/terascope/teraslice_op_test_harness/issues/2
I have extracted `validateOperation`.  It is renamed to
`validateConfig` since it handles both jobConfigs and opConfigs.
I have also removed the third argument, which was a boolean
that indicated whether the config passes was an operation or not.
I replaced it with a test for the presence of `._op` which should
be present on all operations.
**This is a work in progress.  If we want to go this route, a future commit should modify `lib/config/validators/job.js` to use the function added here.**
> Extract validateOperation from validators.job

- integration-tests/Makefile
* docker build will now "find" changed dependencies
because it no longer uses the docker build cache
* add clean-all target that removes the node_modules
directory and the images.log.
* changed wording on clean help to better reflect
what it actually does
closes: #487
> Docker build now uses --no-cache

- README.md
- docs/api.md
There were several places where `/job/` was used as the jobs api endpoint ... mostly in the `README.md`
This PR addresses that.
> fixing a few bad api endpoints in the docs

- integration-tests/docker-compose.sh
While here, reduced elasticsearch heap to 1g to reduce system requirements.
> Fixes #504: honor absolutely-linked npm modules

- Makefile
- integration-tests/config/processor-master.yaml
- integration-tests/config/processor-worker.yaml
- integration-tests/spec/cases/data/reindex.js
- lib/cluster/services/api.js
- lib/cluster/services/cluster.js
- lib/cluster/services/messaging.js
- lib/cluster/slicer.js
- lib/config/schemas/system.js
- package.json
- spec/helpers/reporter.js
Fixes #481: I chose `cluster:analytics` as the message key to reserve room for other
sub-systems to push their metrics.  The integration test assumes another test has
run that has exercised the slicer bits - not clean but didn't want to add even more
time to the test suite.
Needs client changes to be accepted for test to work: terascope/teraslice-client-js/pull/6
> Push slicer analytics to cluster master

- integration-tests/docker-compose.sh
Takes about 2-3 minutes off total run time for me.  Requires a new-ish docker (17.04):
https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/
> Cache bind mounts for faster integration tests on mac

- integration-tests/spec/cases/cluster/job-state.js
- integration-tests/spec/cases/data/reindex.js
- integration-tests/spec/fixtures/jobs/generator.json
- integration-tests/spec/setup.js
- lib/cluster/node_master.js
- lib/cluster/services/cluster.js
- lib/cluster/services/jobs.js
The issue was found to reside in node_master code regarding the stop job event. A stop job event will notify each node_master and will expect a response back from each node indicating that it stop. In the case of the node where the actual slicer resides, the slicer handles the reply, but on other nodes where the workers reside, the node_master has special logic to reply itself when it sees all the appropriate child processes are gone. The issue happens in how the node_master monitors. If there is another slicer not relevant to the job being stopped on the same node as regular workers that should shutdown, the node_master would not properly execute the special logic, thus leading the job to hang even though it should have finished
> fixed stop job timeout issues resolves #434

- lib/cluster/services/cluster.js
- lib/cluster/services/jobs.js
- lib/cluster/storage/backends/mappings/job.json
this will also add `slicer_hostname` and `slicer_port` to the execution context
> prevent cleanUpNode fn from duplicating jobs resolves #454

- lib/cluster/slicer.js
- on job completion it now checks for all work that has been started as well as those that have errors
- If all workers have been disconnected, job will be marked as failed
> if all workers disconnect, slicer will terminate resolves #253

- docs/configuration.md
- docs/custom_operations.md
- lib/cluster/slicer.js
- lib/config/schemas/system.js
- lib/readers/elasticsearch_data_generator.js
- lib/readers/elasticsearch_reader.js
- lib/readers/id_reader.js
- spec/readers/id_slicer-spec.js
can not add another method to a reader to expose to determine the slicer queue length
`function slicerQueueLength(jobConfig){
// the fully validated jobConfig
// can return a num >= 1
//or return  'QUEUE_MINIMUM_SIZE' which will make the queue dynamic to the number of workers
}
module.exports = {
newReader: newReader,
newSlicer: newSlicer,
schema, schema,
slicerQueueLength: slicerQueueLength
}
`
> Slicer queue refactor

- .gitignore
- package.json
This changes out `npm test` command to use istanbul/nyc to check the code coverage of our tests.  The coverage report will be shown right after the test output by default.
It looks like this:
closes #530
> adding istanbul 2.0 code coverage to default test command

- lib/cluster/services/cluster.js
- lib/cluster/services/jobs.js
- lib/cluster/services/messaging.js
- lib/cluster/slicer.js
- lib/cluster/storage/jobs.js
- lib/readers/elasticsearch_date_range/slicer.js
This is a first pass on switching most of the responsibility of managing ex state to the slicer. There are a few cases it must still rely on the cluster master to handle the state in situations where the slicer is not able to be instantiated at all.
> first pass on slicer handling ex state resolves #518

- .eslintrc
- package.json
This uses https://github.com/airbnb/javascript as the baseline.
In difference to the airbnb standards we will continue with the following practices.
* 4 space indention
* Using _ at the beginning of functions intended to be private
* Allowing require at places other than the top of a file
* Although I think this is something we should probably change in the future
* Allowing dynamic requires
* Continuing to place "use strict" at the top of the module. This will be unnecessary in the future but while we're targeting node 4 it's still needed.
Additional conventions beyond this.
* op configuration parameters exposed to jobs should not be camel case and should use _ as word separator
* Fields in data records stored in ES and network messages should not be camel case and should use _ as word …
> Setting eslint code standards using the airbnb standards as a base

- lib/cluster/node_master.js
simple first round, will need more work after we refactor cluster_master and know more of what connections we need or not
> first round of starting slicer/worker on startup resolves #519

- integration-tests/spec/wait.js
forValue shouldn't schedule itself to run again unless result isn't
equal to value AND counter does not exceed iterations.
> Make forValue return when it fails

- lib/readers/elasticsearch_date_range/slicer.js
- lib/readers/id_slicer.js
- lib/utils/error_utils.js
- spec/readers/id_slicer-spec.js
the main issue that I found was that when it entered the retry logic it would not properly return the called function, which the top calling function would then return undefined which singles to the slicer that it finished (even though it really didn't). There was duplicate logic in elasticsearch slicer as well so this had this pitfall as well. We need better intergration tests that can simulate a slight recoverable network issue as well as full blown failure to test more scenarios.
> fixed returns on retries to not immediatly complete resolves #549

- lib/cluster/storage/backends/mappings/ex.json
The ex mapping was accidentally applying to the job type.  This
fixes that.
> Fixing ex mapping to apply to ex type

- lib/readers/elasticsearch_date_range/slicer.js
- lib/readers/elasticsearch_reader.js
- lib/utils/date_utils.js
i switched the regex to /(\d+)(\D+)/i which looks for numbers next to non-number characters. It looks like the schema failed becuase it did not split the numbers from the time selectors when it was being passed to dateOptions. We really need to test our schema seperate. the unit tests did not cover schema validations, we should test those in the future
> fixed schema validation and faulty regex

- lib/cluster/worker.js
When the user sets recycle_worker on a job the workers are
recycled after they hit that slice count.  These can tend to
happen around the same time for all workers.  In the case of
kafka workers, the time it takes to rebalance partitions takes
some time.  By recycling so many workers in a short period of
time we end up accumulating a lot of lag.
This PR tries to stagger the recycle times by comparing
sliceCount with somewhere between 75% and 100% of the
random_worker setting.
> Stagger worker recycle

- docs/api.md
- docs/configuration.md
- lib/cluster/node_master.js
- lib/cluster/services/api.js
- lib/cluster/services/cluster/backends/native.js
- lib/cluster/services/execution.js
- lib/cluster/services/jobs.js
- lib/cluster/services/messaging.js
- lib/config/schemas/system.js
NOTE CONFIG SETTING CHANGES:
- changed `network_timeout` to `action_timeout`
- added `network_latency_buffer` (defaults to 15s) which combines with action_timeout to make the final network_timeout
- can now add a a timeout parameter to stop job which will take the place of action_timeout, note that `network_latency_buffer` will still be added to it for final timeout
```
curl -XPOST localhost:5678/jobs/8b9596db-db1b-4db4-8957-b2bdc4625335/_stop?timeout=120000
```
> node master will now use SIGKILL on worker after timeout resolves #605

- lib/cluster/services/api.js
After testing it seemed that the endpoint works correctly. I got the error reported only when I used the job_id instead of the ex_id for that endpoint. Take note that you can call /jobs/:job_id/slicer with the job_id that is returned assuming you only have one invocation, if you dont you will just get multiple back. If you call /ex/:ex_id/slicer it must be with an actual ex_id, which you would have to dig around a bit. The error was not reporting back correctly so I fixed that
> fixed ex/ex_id/slicer api endpoint error resolves #660

- lib/cluster/execution_controller/engine.js
- lib/cluster/runners/op.js
- lib/cluster/services/assets.js
- lib/cluster/storage/state.js
- lib/processors/elasticsearch_bulk.js
- lib/processors/elasticsearch_index_selector.js
- lib/processors/noop.js
- lib/processors/save_file.js
- lib/processors/stdout.js
- spec/execution_controller/engine-spec.js
this needs changes in the queue module https://github.com/terascope/queue/pull/5
> allow slices to be sent to specific workers resolves #624

- lib/cluster/node_master.js
The k8s cluster_master should be able to start up without requiring an EX.
> k8s cluster master fix

- lib/readers/elasticsearch_date_range/slicer.js
- spec/readers/elasticsearch_reader-spec.js
make sure to specify the correct connection on the job that it points to the node
> fixed cross cluster searching resolves #692

- .eslintrc
Since we are slowing updating teraslice and our other projects to follow our eslint rules, I believe now is a good time to add a few rules that improve our ability to catch errors before they happen. I also think it is important that our eslint is upgraded to better support changes in ES6. All of these change are what I would consider a "patch" release to our eslint rules.
I propose adding the following to catch errors before they happen:
- [handle-callback-err](https://eslint.org/docs/rules/handle-callback-err)
- Ignorance is not bliss when it comes errors
- [no-debugger](https://eslint.org/docs/rules/no-debugger)
- Debugger statements can decrease performance and should not be left in the code
- [no-path-concat](https://eslint.org/docs/rules/no-path-concat)
- Using string concatenation …
> A proposal for eslint changes to catch errors and handle ES6 better

- lib/cluster/services/jobs.js
- lib/cluster/storage/jobs.js
the fields: job_id (which is used for searching and other vital queries) and _created (which is used for sorting) where missing. This pr adds them back in
> added important meta data back to updated job

- package.json
Reverted socket.io to version 1.4.5 because we were seeing issues with workers failing to reconnect after rebalance or adding workers.
> changed socket.io to version 1.4.5

- docs/api.md
- integration-tests/spec/cases/data/reindex.js
- integration-tests/spec/setup.js
- lib/cluster/execution_controller/engine.js
- lib/cluster/execution_controller/recovery.js
- lib/cluster/node_master.js
- lib/cluster/services/api.js
- lib/cluster/services/cluster/backends/native.js
- lib/cluster/services/execution.js
- lib/cluster/services/jobs.js
- lib/cluster/storage/backends/elasticsearch_store.js
- lib/cluster/storage/backends/mappings/ex.json
- lib/cluster/storage/state.js
- lib/readers/elasticsearch_data_generator.js
- spec/execution_controller/recovery-spec.js
- yarn.lock
added  /ex/ex_id/_recovery?cleanup=all endpoints. If you use cleanup, it will stop the execution after recovery finishes and exit. cleanup may be set to `errors` or `all`. This pr needs to coincide with PRs in teraslice-client-js so tests may fail
> Recovery changes

- lib/cluster/services/cluster/backends/kubernetes/k8s.js
- package.json
This is called the Cascading Deletion Policy by k8s.  Basically we just
need to pass a body with the request that will ensure pods get deleted
too.  I suppose we might encounter conditions where we don't want the
pods deleted when the job is, but for now, we'll force that.
closes: #777
> Ensure execution_controller pods are remove on job stop

- Dockerfile
- docs/k8s-clustering.md
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/deployments/worker.hbs
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/index.js
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/jobs/execution_controller.hbs
- packages/teraslice/lib/config/schemas/system.js
This PR adds two new config options
* `kubernetes_config_map_name` - the name of the config map that the teraslice master associates with the workers it launches.  On our internal systems, the name ends up being `<CLUSTERNAME>-worker` but it should be able to be anything.
* `kubernetes_image_pull_secret` - the kubernetes secret used for pulling docker images
> Issue 773 config image pull

- packages/teraslice/lib/cluster/worker/executor.js
this:
```
23:14:06.767Z ERROR teraslice: slice state has been marked as error (ex_id=f24ea3b4-dcad-45c3-b8b0-d03a78f017e5, job_id=165c67ca-9e4f-4f09-9825-17495e4f3468, module=slice, worker_id=10.1.45.242__15, slice_id=3d73ffcb-f114-41ab-b7a1-9c72407fef52)
slice: {
"slice_id": "3d73ffcb-f114-41ab-b7a1-9c72407fef52",
"request": {
"total": 439597,
"path": "/tmp/work/ready/t1.json.lz4",
"length": 39598,
"offset": 399999
},
"slicer_id": 0,
"slicer_order": 5,
"_created": "2018-08-28T23:14:05.761Z"
}
--
error: TypeError: chunkFormatter[opConfig.format] is not a function
at readerClient.then.then.data (/Users/estephens/src/terascope/teraslice/assets/bd94da86b67ae2219293da5afd89d7520abbf6c9/node_modules/@terascope/chunked-file-reader/index.js:50:54)
at <anonymous>
23:14:06.782Z ERROR teraslice: …
```
> Improve slice error msg

- packages/teraslice-worker/lib/execution-controller/analytics.js
I think the change here should resolve our missing slice analytics.  This was introduced 6 days ago.  So I think this it the culprit.  I am still confused as to why we had reports that this didn't work on the previous version.  But I updated the other internal cluster to the `v0.40.0` build and it started exhibiting the same issue.  And this code stood out.
> Change get to update so set will work

- packages/teraslice/lib/cluster/services/api.js
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/index.js
- packages/teraslice/lib/cluster/services/cluster/backends/native.js
- packages/teraslice/lib/cluster/services/execution.js
- packages/teraslice/lib/cluster/services/jobs.js
- packages/teraslice/lib/cluster/storage/execution.js
simple fix. It changes the status to `stopping`, waits for it to stop, then it checks to see if its already in a terminal status before changing it to `stopped`
> set a transition of stopping before its stopped resolves #783

- package.json
- packages/elasticsearch-api/package.json
- packages/error-parser/package.json
- packages/job-components/package.json
- packages/job-components/src/operations/core/slicer-core.ts
- packages/job-components/src/operations/parallel-slicer.ts
- packages/job-components/src/operations/slicer.ts
- packages/job-components/test/operations/parallel-slicer-spec.ts
- packages/job-components/test/operations/slicer-spec.ts
- packages/queue/package.json
- packages/queue/types/index.d.ts
- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/execution-controller/interfaces.ts
- packages/teraslice-messaging/src/execution-controller/server.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-types/package.json
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/package.json
- scripts/bump.js
- scripts/publish.sh
- yarn.lock
A few of our packages had changed but were never published, which means that that NPM wasn't reflecting the latest changes. I bumped a lot of packages so that they can be updated. This release should decrease the size of the `job-components` library.
In addition to bumping the packages, I made a few fixes the`job-components` library to match the latest teraslice changed, updated the queue type definitions and fixed some of our scripts.
> v0.42.2 update packages and a few minor changes

- .eslintrc
- packages/elasticsearch-api/index.js
- packages/teraslice-op-test-harness/index.js
- packages/teraslice-op-test-harness/test/harness-spec.js
- packages/teraslice/cluster-service.js
- packages/teraslice/lib/readers/id_slicer.js
- packages/teraslice/lib/workers/execution-controller/scheduler.js
- packages/teraslice/worker-service.js
I disabled the following rules because they should be up to the developer's discretion, not the linting.
- [class-methods-use-this](https://eslint.org/docs/rules/class-methods-use-this)
- [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax)
- [no-await-in-loop](https://eslint.org/docs/rules/no-await-in-loop)
- [no-plusplus](https://eslint.org/docs/rules/no-plusplus)
- [no-continue](https://eslint.org/docs/rules/no-continue)
> Be free from ESLint restrictions

- e2e/docker-compose.yml
- package.json
- packages/job-components/package.json
- packages/job-components/src/operations/parallel-slicer.ts
- packages/job-components/src/operations/shims/legacy-processor-shim.ts
- packages/job-components/src/operations/shims/legacy-reader-shim.ts
- packages/job-components/src/operations/shims/reader-shim.ts
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/README.md
- packages/teraslice-op-test-harness/index.js
- packages/teraslice-op-test-harness/lib/operation.js
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-op-test-harness/test/harness-spec.js
- packages/teraslice/package.json
- yarn.lock
* Easier use in tests
* Fix parallel slicer to handle slicers race to finish
* Return the new Constructors on the legacy shims to make it more compatible with test-op-harness
> Improvements for teraslice-test-op-harness and parallel-slicer

- package.json
- packages/job-components/bench/data-encoding-suite.js
- packages/job-components/package.json
- packages/job-components/src/interfaces/jobs.ts
- packages/job-components/src/job-schemas.ts
- packages/job-components/src/operations/data-entity.ts
- packages/job-components/src/utils.ts
- packages/job-components/test/config-validators-spec.ts
- packages/job-components/test/operations/convict-schema-spec.ts
- packages/job-components/test/operations/data-entity-spec.ts
- packages/job-components/test/utils-spec.ts
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-op-test-harness/test/harness-spec.js
- packages/teraslice/package.json
- packages/teraslice/test/processors/noop-spec.js
- yarn.lock
This initial version only supports JSON encoded buffers and strings, but it is designed in a way to support other types in the future, like `cbor` or `protobuf`.
An example usage is:
```ts
const opConfig = {
_op: 'example',
_encoding: 'json'
};
const buf = Buffer.from(JSON.stringify({ foo: 'bar' }));
const dataEntity = DataEntity.fromBuffer(buf, opConfig);
console.log('it should have foo: bar', dataEntity.foo === 'bar');
const resultBuf = dataEntity.toBuffer(opConfig);
console.log('it should equal buf', resultBuf === buf);
```
Resolves #855
> DataEntity serialization/deserialization

- packages/job-components/bench/data-encoding-suite.js
- packages/job-components/bench/data-entity-large-suite.js
- packages/job-components/bench/data-entity-small-suite.js
- packages/job-components/bench/fixtures/proxy-entity.js
- packages/job-components/bench/simple-job-suite.js
- packages/job-components/bench/worker-lifecycle-suite.js
- packages/job-components/package.json
- packages/job-components/src/operations/data-entity.ts
- packages/job-components/src/operations/map-processor.ts
- packages/job-components/test/operations/data-entity-spec.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
Creating large DataEntities was slow because of using shallow cloning the object onto the DataEntity. I switched DataEntity.make to create a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) instead of using Object.assign. Benchmarks prove that this is roughly 600x-1000x faster, which is very significant and likely well worth another performance impacts the previous DataEntity had.
**NOTE:** Unfortunately I have been unable to figure out how to make `new DataEntity` to work with a Proxy, but this has a very small impact since it is rarely used. I added comments to make this clear and will defer the change to a later date.
Ref https://github.com/terascope/kafka-assets/issues/11
> Faster DataEntity creation

- package.json
- packages/job-components/package.json
- packages/job-components/src/interfaces/context.ts
- packages/job-components/src/interfaces/index.ts
- packages/job-components/src/interfaces/logger.ts
- packages/job-components/src/interfaces/operations.ts
- packages/job-components/src/operation-loader.ts
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/execution-context/worker-spec.ts
- packages/job-components/test/fixtures/failing-reader/fetcher.js
- packages/job-components/test/fixtures/failing-reader/index.js
- packages/job-components/test/fixtures/failing-reader/schema.js
- packages/job-components/test/fixtures/failing-reader/slicer.js
- packages/job-components/test/register-apis-spec.ts
- packages/teraslice-op-test-harness/index.js
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/README.md
- packages/teraslice-test-harness/package.json
- packages/teraslice-test-harness/src/slicer-test-harness.ts
- packages/teraslice-test-harness/src/worker-test-harness.ts
- packages/teraslice-test-harness/test/example-asset-spec.ts
- packages/teraslice-test-harness/test/job-test-harness-spec.ts
- packages/teraslice-test-harness/test/op-test-harness-spec.ts
- packages/teraslice-test-harness/test/slicer-test-harness-spec.ts
- packages/teraslice-test-harness/test/worker-test-harness-spec.ts
- packages/teraslice/lib/workers/worker/slice.js
- packages/teraslice/package.json
- packages/teraslice/test/workers/worker/slice-spec.js
- yarn.lock
I found a couple issues when developing with job-components, and the teraslice-test-harness. This PR fixes the following things:
- Fixes `Logger` type definitions
- Terafoundation test clients are now expected to return `{ client: any }` when `create` is called, in order to behave as close to real life as possible.
- Add failing reader spec
- Add support for ignoring certain directories when testing typescript operations
- Fix typescript definitions for runSlice and createSlices
> v0.44.1 Fix a couple small issues in job-components and teraslice-test-harness

- packages/job-components/package.json
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/test-helpers-spec.ts
- packages/teraslice-op-test-harness/index.js
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-op-test-harness/test/harness-spec.js
- packages/teraslice-op-test-harness/types/index.d.ts
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
When running in elasticsearch-assets there was an issue when changing an existing client between test runs. This is fixed now.
> Fix test-op-harness and test client usage

- packages/docker-compose-js/README.md
This package is published on npmjs.org as [`@terascope/docker-compose-js`](https://www.npmjs.com/package/@terascope/docker-compose-js), but referred to in the current README.md as [`docker-compose-js`](https://www.npmjs.com/package/docker-compose-js), which references a different package.
> Fix npm package references.

- Dockerfile
- docker-base/Dockerfile
- docker-base/README.md
- docker-base/build-and-push.sh
- docker-base/package.json
- docker-base/yarn.lock
- e2e/test/download-assets.js
- e2e/test/fixtures/jobs/kafka-reader.json
- e2e/test/fixtures/jobs/kafka-sender.json
Use the new Kafka 2.0.0 asset bundle and connector.
Removes kafka processors from base docker image
> Use kafka 2.0 asset bundle

- packages/ts-transforms/package.json
- packages/ts-transforms/src/operations/lib/transforms/extraction.ts
- packages/ts-transforms/src/phases/output_phase.ts
- packages/ts-transforms/src/phases/post_process_phase.ts
- packages/ts-transforms/test/fixtures/transformRules19.txt
- packages/ts-transforms/test/fixtures/transformRules24.txt
- packages/ts-transforms/test/fixtures/transformRules25.txt
- packages/ts-transforms/test/operations/transforms/extraction-spec.ts
- packages/ts-transforms/test/phases/output_phase-spec.ts
- packages/ts-transforms/test/transform-spec.ts
- this should allow multipe `multivalue` settings on post_process extractions with mutate: true
> Multivalue fix

- packages/ts-transforms/package.json
- packages/ts-transforms/src/operations/lib/transforms/extraction.ts
- packages/ts-transforms/test/fixtures/transformRules6.txt
- packages/ts-transforms/test/operations/transforms/extraction-spec.ts
- packages/ts-transforms/test/transform-spec.ts
`post_process: extraction` now defaults to `mutate:true`. You can still set mutate:false if desired.
> Extraction defaults

- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
Not sure how this got by me.  The job start issue raise by @macgyver603 was caused by trying to set properties on the pod `template.spec` property.  There is no `template` on services since they don't create pods.
This PR includes the fix and a test that should hopefully catch a regression.  There may be other `resourceTypes` in the future that need to be excluded, but none that I can anticipate today, so I've just excluded `services` from running the private methods that set up resources.
> fix k8s job start issue

- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
Fortunately @macgyver603 caught the k8s jobname invalid DNS character problem (# wouldn't work in job names) a couple days ago.  I remembered and fix it here.
This happened because I added job names into the pod names ... which in turn end up being DNS names.
So this should go into `v0.50.0` or Charlie will be sad.
> fix job name special character issue in k8s

- .travis.yml
- docs/packages/data-access-plugin/overview.md
- packages/data-access-plugin/package.json
- packages/data-access-plugin/src/index.ts
- packages/data-access-plugin/src/interfaces.ts
- packages/data-access-plugin/src/manager/index.ts
- packages/data-access-plugin/src/search/index.ts
- packages/data-access-plugin/src/search/interfaces.ts
- packages/data-access-plugin/src/search/utils.ts
- packages/data-access-plugin/src/utils.ts
- packages/data-access-plugin/test/adapter-spec.ts
- packages/data-access-plugin/test/plugin-spec.ts
- packages/data-access/package.json
- packages/data-access/src/acl-manager.ts
- packages/data-access/src/models/users.ts
- packages/elasticsearch-store/src/index-manager.ts
- Add support for configuring the connector for the data-access and for spaces. For spaces set `metadata.teraserver.connection` on the space.
- Fix use of pretty
- Add todos, update docs and fixes
- Fixes to user graphql types
> Data Access Plugin Fixes

- packages/teraslice/package.json
This just bumps the version of teraslice for when we want to do the `v0.51.0` release.
> Bump version of teraslice to v0.51.0 for release.

- packages/teraslice-cli/cmds/assets/deploy.js
- packages/teraslice-cli/lib/tjm-util.js
- packages/teraslice-cli/package.json
- packages/teraslice-cli/test/lib/tjm_util-spec.js
2 fixes to the cli
* tjm stop checks status before calling stop on a job
* asset --replace doesn't assume the latest asset is the one that needs replacing and checks for the asset version
> better job stopping and no assumptions with asset replace

- jest.config.base.js
- packages/data-access-plugin/package.json
- packages/job-components/package.json
- packages/job-components/src/execution-context/api.ts
- packages/job-components/src/execution-context/base.ts
- packages/job-components/src/execution-context/index.ts
- packages/job-components/src/execution-context/interfaces.ts
- packages/job-components/src/execution-context/slicer.ts
- packages/job-components/src/execution-context/utils.ts
- packages/job-components/src/execution-context/worker.ts
- packages/job-components/src/operations/interfaces.ts
- packages/job-components/src/register-apis.ts
- packages/job-components/test/execution-context/worker-spec.ts
- packages/job-components/test/operations/operation-api-spec.ts
- packages/job-components/test/register-apis-spec.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice-test-harness/src/worker-test-harness.ts
- packages/teraslice-test-harness/test/example-asset-spec.ts
- packages/teraslice-test-harness/test/worker-test-harness-spec.ts
- packages/teraslice/package.json
- scripts/add-test-env.js
@jsnoble was using the operation apis in the `WorkerTestHarness` and found the usage was it was confusing and misleading, the operation apis we loaded in two different ways.
Move around the code so the majority of the API registration and loading is used in one place.
- Ensure `NODE_ENV === test` when running tests
- Improved interface for WorkerTestHarness->flush and improved tests
- Add `makeLogger` function to `executionContext` api to make it easier to register loggers.
- And other minor misc fixes to job-components
- Bump packages
> v0.53.1 - Fix/Improve Operation API usage

- packages/chunked-file-reader/package.json
- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/terafoundation/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/lib/workers/execution-controller/scheduler.js
- packages/teraslice/lib/workers/helpers/worker-shutdown.js
- packages/teraslice/package.json
- packages/teraslice/worker-service.js
- packages/ts-transforms/package.json
- packages/ui-components/package.json
- packages/ui-core/package.json
- packages/ui-data-access/package.json
- packages/utils/package.json
- packages/utils/src/errors.ts
- packages/utils/src/promises.ts
- packages/utils/test/promises-spec.ts
- packages/xlucene-evaluator/package.json
- Fix `unhandledRejection` in `bulkSend` in `elasticsearch-api`
- Fix stack trace in `pRetry`
- Keep error logging consistent by logging the err before the message
- Bumps `teraslice`, `@terascope/utils` and `@terascope/elasticsearch-api`
Resolves #1213
> v0.53.3 - Fix unhandledRejection and improved error logging

- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-types/package.json
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- packages/ui-components/package.json
- packages/ui-data-access/package.json
- packages/xlucene-evaluator/package.json
- packages/xlucene-evaluator/peg/lucene.pegjs
- packages/xlucene-evaluator/src/translator/interfaces.ts
- packages/xlucene-evaluator/src/translator/utils.ts
- packages/xlucene-evaluator/test/cases/parser/terms.ts
- packages/xlucene-evaluator/test/cases/translator/field-group.ts
- packages/xlucene-evaluator/test/cases/translator/logical-group.ts
- packages/xlucene-evaluator/test/cases/translator/term.ts
xlucene was previously translating term queries using a [Term Query](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-term-query.html), however that has issues querying analyzed fields since it won't do an exact match. This PR changes xlucene to use a [Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-match-query.html) instead.
> Fix for matching xlucene query translations

- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-access/src/interfaces.ts
- packages/data-access/src/search-access.ts
- packages/data-access/test/search-access-spec.ts
- packages/ui-components/package.json
- packages/ui-data-access/package.json
Fixes the "Returning" response and fixes converting the `start` query parameter to a string.
Resolves #1268 
Resolves #1267
> Fix "v1" vs "v2" API compatability

- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts
- refactored mget
- added sync method, which acts like mget but does not return results, its primarily used to update the cache
- added tests
> State storage sync

- .travis.yml
- e2e/test/misc.js
- packages/data-access-plugin/package.json
- packages/data-access-plugin/test/helpers/elasticsearch.ts
- packages/data-access-plugin/test/manager-plugin-spec.ts
- packages/data-access/package.json
- packages/data-access/test/helpers/elasticsearch.ts
- packages/data-access/test/search-access-spec.ts
- packages/data-types/package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/utils/elasticsearch.ts
- packages/elasticsearch-store/test/helpers/elasticsearch.ts
- packages/terafoundation/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/ui-components/package.json
- packages/ui-data-access/package.json
- packages/xlucene-evaluator/package.json
- packages/xlucene-evaluator/src/query-access/query-access.ts
Fix compatibility for elasticsearch api version of `5.6`. Our cluster information should use the following `apiVersion`s in the connector configuration:
- for elasticsearch 7, `apiVersion: 7.2`
- for elasticsearch 6, `apiVersion: 6.5`
- for elasticsearch 5, `apiVersion: 5.6`
> v0.54.8 - Fix es compatibility in 5.6

- packages/data-access-plugin/bin/simple-migrate.js
- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-access/src/acl-manager.ts
- packages/data-access/src/models/config/data-types.ts
- packages/data-access/src/models/config/spaces.ts
- packages/data-types/src/interfaces.ts
- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/index-manager.ts
- packages/elasticsearch-store/src/index-store.ts
- packages/elasticsearch-store/src/interfaces.ts
- packages/elasticsearch-store/test/helpers/simple-index.ts
- packages/elasticsearch-store/test/index-manager-migrate-spec.ts
- packages/elasticsearch-store/test/index-manager-spec.ts
- packages/elasticsearch-store/test/index-model-spec.ts
- packages/ui-components/package.json
- packages/ui-data-access/package.json
Fixes object mappings for `spaces` and `data-types` and adds basic migration functionality to `elasticsearch-store`.
TODO:
Resolves #1307
> Data Type mapping fixes

- packages/scripts/package.json
- packages/scripts/src/helpers/test-runner/utils.ts
Previously it wasn't using the docker cache layers, now it should be. This should improve the e2e tests.
> Fix Docker build in CI

- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-types/package.json
- packages/data-types/src/types/versions/v1/keyword-tokens-case-insensitive.ts
- packages/data-types/src/types/versions/v1/keyword-tokens.ts
- packages/data-types/test/data-type-spec.ts
- packages/data-types/test/types/v1/keyword-tokens-case-insensitive-spec.ts
- packages/data-types/test/types/v1/keyword-tokens-spec.ts
- packages/elasticsearch-store/package.json
- packages/ui-data-access/package.json
* all field types that use a non-custom analyzer use the standard analyzer
* removed index: true in keyword tokens to be consistent with other data fields
addresses issue #1313
> changed type analyzers to standard and removed index:true

- package.json
- packages/data-access-plugin/package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/types/index.d.ts
- packages/terafoundation/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice-messaging/src/messenger/core.ts
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/cached-state-storage/index.ts
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice-state-storage/src/interfaces.ts
- packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts
- packages/teraslice/lib/cluster/node_master.js
- packages/teraslice/lib/cluster/storage/backends/elasticsearch_store.js
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/lib/workers/helpers/worker-shutdown.js
- packages/teraslice/package.json
- packages/utils/package.json
- packages/utils/src/arrays.ts
Fix `unhandledRejection` in `teraslice-messaging` when client is not ready
Better millisecond logs in `teraslice-messaging` and `teraslice`
Minor cleanup in cached-state-storage
Many improvements and fixes elasticsearch-state-storage
More accurate and understandable tests for elasticsearch-state-storage
> v0.54.11 - Fix unhandled rejection and teraslice-state-storage improvements

- packages/chunked-file-reader/package.json
- packages/data-access-plugin/package.json
- packages/data-access/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/job-components/src/execution-context/api.ts
- packages/job-components/src/execution-context/utils.ts
- packages/job-components/src/index.ts
- packages/job-components/src/operations/core/api-core.ts
- packages/job-components/src/operations/core/operation-core.ts
- packages/job-components/src/operations/core/slicer-core.ts
- packages/job-components/src/utils.ts
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/ui-components/package.json
- packages/ui-core/package.json
- packages/ui-data-access/package.json
- packages/utils/package.json
- packages/xlucene-evaluator/package.json
- Use `pImmediate` when using a recursion in the `teraslice-state-storage`
- Use a consistent logger in operations
- Bump `utils` and `terafoundation` to fix `makeLogger` issue
> v0.55.2 - A few fixes

- .gitignore
- e2e/docker-compose.yml
- e2e/package.json
- e2e/scripts/logs.sh
- e2e/test/cases/assets/simple-spec.js
- e2e/test/cases/cluster/job-state-spec.js
- e2e/test/fixtures/jobs/generator-asset.json
- e2e/test/global.setup.js
- e2e/test/misc.js
- e2e/test/setup-config.js
- packages/scripts/package.json
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/teraslice/lib/cluster/services/cluster/backends/native/messaging.js
- Fixes formatting of docker build tag name
- Fix simple asset test in e2e to cleanup properly
- Minor fixes to e2e tests
- Write e2e teraslice logs to file so we can get logs from containers that have been removed
- Minor fixes to node_master messaging in native clustering to use the same `pingTimeout` logic as in `teraslice-messaging`
> Fix daily docker tag name and e2e test improvements

- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/cluster-master/client.ts
- packages/teraslice-messaging/src/cluster-master/interfaces.ts
- packages/teraslice-messaging/src/execution-controller/client.ts
- packages/teraslice-messaging/src/execution-controller/interfaces.ts
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice-messaging/src/messenger/interfaces.ts
- packages/teraslice-messaging/src/messenger/server.ts
- packages/teraslice-messaging/test/cluster-master-spec.ts
- packages/teraslice-messaging/test/execution-controller-spec.ts
- packages/teraslice-messaging/test/messenger-spec.ts
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/lib/workers/worker/index.js
- packages/teraslice/package.json
- packages/teraslice/test/workers/execution-controller/execution-special-test-cases-spec.js
- packages/teraslice/test/workers/execution-controller/execution-test-cases-spec.js
Set the `pingTimeout` on the `socket.io` client to be `worker_disconnect_timeout` to avoid disconnecting the client before the connection is actually dead.
> v0.55.5 - Set pingTimeout on socket.io client

- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
bump `teraslice`
bump `teraslice-test-harness`,` teraslice-op-test-harness` to include latest `job-components`
All of the API changes were in #1424
> v0.57.0 - Minor DataEntity API improvements

- packages/chunked-file-reader/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/entities/data-entity.ts
- packages/utils/test/data-entity-spec.ts
- packages/xlucene-evaluator/package.json
- A `DataEntity` should be able to be remove a `_key` via `entity.setMetadata('_key', undefined);`
- Fix issue with extending a `DataEntity` and getting the instance of the a real `DataEntity`
> v0.57.1 - Fixes to DataEntity API changes

- package.json
- packages/teraslice/lib/workers/helpers/worker-shutdown.js
- packages/teraslice/package.json
Fix non-zero exit code logic in worker-shutdown that could potentially allow an execution controller to restart in k8s.
> v0.57.2 - Fix worker shutdown logic

- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/test.ts
- packages/scripts/src/command.ts
- packages/scripts/src/helpers/bump/utils.ts
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/misc.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/interfaces.ts
- packages/scripts/src/helpers/test-runner/services.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/scripts/test/bump-spec.ts
- feat: show version in bump commit message
- fix: add multiple docker registry support
- fix: better test errors
- fix: issue when ts-scripts cli fails
- feat: add the ability to set env JEST_MAX_WORKERS (to global constrained concurrency)
- fix: allow overriding FORCE_COLOR in ts-scripts
- feat: allow specifying a network to connect to for the test services
BREAKING CHANGES:
- Removes flags for `--elasticsearch-host` and `--kafka-broker` 
- Changes the configuration for docker registries from `registry` to `registries`
> ts-scripts improvements

- .dockerignore
- .gitignore
- .travis.yml
- .yarnrc
- Dockerfile
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/services.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- scripts/cleanup.sh
- fix: ts-scripts test namespace
- fix: ts-scripts `FORCE_COLOR`
- fix: infer prelease tag from version not env
- fix: coverage reporting
- fix: official elasticsearch docker image usage in v5.6.16
- fix: some of the yarn-caches issues I have found and other docker issues
> More ts-scripts fixes

- e2e/package.json
- packages/chunked-file-reader/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/errors.ts
- packages/utils/src/objects.ts
- packages/utils/test/objects-spec.ts
- packages/xlucene-evaluator/package.json
Adds tests for a bunch of edge cases with the `has` utility from `@terascope/utils`. Prevents crash  when given a string or other non-object types as the first parameter.
Also fixes instanceof detection in `TSError` when there are multiple instances of `@terascope/utils` in a given a project.
> Fix has util function

- package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/terafoundation/package.json
- packages/terafoundation/src/validate-configs.ts
- packages/teraslice-state-storage/package.json
- packages/teraslice/lib/cluster/storage/backends/elasticsearch_store.js
- packages/teraslice/package.json
- Fix `terafoundation` to apply schema for keys that aren't specified in the user config file.
- Fix logging the index exists during index creation in `elasticsearch-api->indexSetup`
> v0.58.1 - terafoundation schema fix and Elasticsearch API error fix

- .travis.yml
- docs/development/overview.md
- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/sync.ts
- packages/scripts/src/helpers/bump/index.ts
- packages/scripts/src/helpers/bump/interfaces.ts
- packages/scripts/src/helpers/bump/utils.ts
- packages/scripts/src/helpers/packages.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/sync/index.ts
- packages/scripts/src/helpers/sync/interfaces.ts
- packages/scripts/src/helpers/sync/utils.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/scripts/test/bump-spec.ts
- fix: printing empty env when running test with debug
- feat: add `--quiet` flag to `yarn sync` and run `yarn sync` at the end of `yarn setup` to help prevent merge issues.
- feat: before bumping a package, reset the version to npm version to avoid issues after merging, ref #1496
> ts-scripts bump and sync improvments

- package.json
- packages/teraslice/lib/workers/execution-controller/execution-analytics.js
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/package.json
fix: sending execution analytics when the cluster master is down
Fixes (hopefully) https://github.com/terascope/teraslice/issues/1461
> v0.58.3 - Stop sending execution analytics cluster shutdown (hopefully)

- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/test/api-spec.js
- packages/teraslice-state-storage/package.json
- packages/teraslice/package.json
- changes needed for elasticsearch-assets to allow id-reader to query off of a field
> elasticsearch api changes for id-slicer

- Dockerfile
- package.json
- packages/teraslice/package.json
Update docker image to use `terafoundation_kafka_connector@2.5.3` which switching back to using the official `node-rdkafka` npm package.
Ref #1500
> v0.60.1 - Update kafka connector 2.5.3

- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/index-model.ts
- packages/terafoundation/package.json
- packages/teraslice/package.json
Change the default production/test index replicas / shards in `elasticsearch-store`. Previously this would default to 1 replica and 5 shards (if `NODE_ENV == null` or `NODE_ENV === 'production'`). Now the default is 2 replica and 5 shards (if `NODE_ENV !== 'test'`). This will prevent accidentally creating indexes with less replicas or shards if NODE_ENV is set to development, like if you are running a migration or running against a production instance.
> Fix default index replicas

- packages/data-types/package.json
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- packages/xlucene-evaluator/package.json
- packages/xlucene-evaluator/src/parser/context.ts
- packages/xlucene-evaluator/src/parser/interfaces.ts
- packages/xlucene-evaluator/src/parser/parser.ts
- packages/xlucene-evaluator/src/translator/interfaces.ts
- packages/xlucene-evaluator/src/translator/utils.ts
- packages/xlucene-evaluator/test/cases/translator/term.ts
Fixes regex queries on tokenized fields by switching use a `query_string` for tokenized fields since that is the only way I can see how to fix it.
>  The regexp query allows you to use regular expression term queries. See Regular expression syntax for details of the supported regular expression language. The "term queries" in that first sentence means that Elasticsearch will apply the regexp to the terms produced by the tokenizer for that field, and not to the original text of the field.
From [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-regexp-query.html#query-dsl-regexp-query)
> Fix regex queries in xlucene

- package.json
- packages/teraslice/lib/cluster/services/api.js
- packages/teraslice/lib/cluster/services/execution.js
- packages/teraslice/package.json
Fixes the following issues:
```sh
curl -Ss localhost:5678/txt/workers
{
"error": 500,
"message": "clusterService.getClusterState(...).filter is not a function"
}
curl -Ss localhost:5678/txt/ex
{
"error": 500,
"message": "executionService.search is not a function"
}
curl -Ss localhost:5678/txt/nodes
{
"error": 500,
"message": "Cannot read property 'length' of undefined"
}
curl -Ss localhost:5678/ex
{
"error": 500,
"message": "exStore.searchExecutionContexts is not a function"
}
```
> v0.62.1 - Fix services references

- package.json
- packages/data-types/package.json
- packages/data-types/src/data-type.ts
- packages/data-types/src/interfaces.ts
- packages/data-types/src/types/base-type.ts
- packages/data-types/src/types/group-type.ts
- packages/data-types/src/types/index.ts
- packages/data-types/src/types/v1/boundary.ts
- packages/data-types/src/types/v1/geo-point.ts
- packages/data-types/src/types/v1/geo.ts
- packages/data-types/test/data-type-graphql-spec.ts
- packages/data-types/test/data-type-spec.ts
- packages/elasticsearch-store/package.json
- packages/teraslice-messaging/src/messenger/server.ts
- packages/teraslice/lib/storage/execution.js
- packages/teraslice/lib/workers/execution-controller/index.js
- packages/teraslice/lib/workers/helpers/job.js
- packages/teraslice/package.json
- Add optional support for snake casing type names for` dataType->toGraphQL` (this will make it look more consistent if snake case is used for other types)
- Add `groupedFields` to data type instance to make easier to do look if a base field exists in a `DataType` (and what any nested fields too)
- Make sure to update `_updated` date on execution and job more often
Resolves #1660
> v0.63.2 - Fix updating _updated date on execution / job

- package.json
- packages/teraslice/lib/storage/execution.js
- packages/teraslice/lib/workers/execution-controller/execution-analytics.js
- packages/teraslice/lib/workers/execution-controller/scheduler.js
- packages/teraslice/package.json
- packages/teraslice/test/workers/execution-controller/execution-special-test-cases-spec.js
- packages/teraslice/test/workers/execution-controller/execution-test-cases-spec.js
- Fix `_slicer_stats.slicers`, which was previously returning a function
- Fix updating the `executionMetaData` function to not set `_slicer_stats` to `null` and effectively remove the `_slicer_stats` when updating the execution.
- Improves the code documentation around `executionMetaData` functionality
Resolves https://github.com/terascope/teraslice/issues/1701
> v0.63.6 - Fix/slicer stats on stopped jobs

- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/index-model.ts
- packages/elasticsearch-store/src/index-store.ts
- packages/elasticsearch-store/src/interfaces.ts
- packages/elasticsearch-store/src/utils/model.ts
- packages/elasticsearch-store/test/index-model-spec.ts
- packages/elasticsearch-store/test/index-search-compatability-spec.ts
- packages/elasticsearch-store/test/index-store-spec.ts
- packages/elasticsearch-store/test/utils-spec.ts
**BREAKING CHANGES:**
- Change `IndexStore` to use the UUID v4 id generator instead of nanoid
- Change `IndexModel` behavior when counting unique values like name to ignore special characters and case insenstive.
- Change `IndexStore->search` to return a `{ _total: number; _fetched: number; results: any[] }` instead of just the results so we can get the total record count.
> Breaking changes to elasticsearch-store

- packages/data-mate/package.json
- packages/data-types/src/types/v1/ngram-tokens.ts
- packages/data-types/test/types/v1/keyword-case-insensitive-spec.ts
- packages/data-types/test/types/v1/keyword-tokens-case-insensitive-spec.ts
- packages/data-types/test/types/v1/ngram-tokens-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-parser/src/context.ts
- packages/xlucene-parser/src/interfaces.ts
- packages/xlucene-parser/test/cases/parser/term.ts
- packages/xlucene-translator/package.json
- packages/xlucene-translator/test/cases/translator/term.ts
This change will correctly use a [match](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-match-query.html) instead of [term](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-term-query.html) when querying against `ngram_analyzer` fields that use numeric values.
> Fix xLucene searching of tokenized fields with numeric values

- jest.config.base.js
- jest.config.js
- package.json
- packages/docker-compose-js/package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/publish.ts
- packages/scripts/src/cmds/sync.ts
- packages/scripts/src/helpers/bump/utils.ts
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/packages.ts
- packages/scripts/src/helpers/sync/utils.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/services.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/scripts/src/index.ts
- yarn.lock
- Don't bump private packages
- Fail if elasticsearch service is not up
- Expost helper functions from `@terascope/scripts` and add `getJestAliases`
> ts-scripts test improvements

- packages/data-mate/package.json
- packages/data-mate/src/transforms/field-transform.ts
- packages/data-mate/src/validations/field-validator.ts
- packages/data-mate/test/field_transform-spec.ts
- packages/data-mate/test/field_validator-spec.ts
- packages/data-types/package.json
- packages/data-types/src/types/base-type.ts
- packages/data-types/src/types/v1/object.ts
- packages/data-types/test/types/v1/object-spec.ts
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/ts-transforms/test/phases/selector-phase-spec.ts
- packages/types/package.json
- packages/types/src/elasticsearch-interfaces.ts
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- added support in data-type `Object` for array support
- fixed extract bug so it does not throw on no results
- added `map` and `setDefault` to field transforms
- added `exists`, `guard`,  `isArray`,`every`, `guard` to field validations
> data-mate error fixes and data-type object support for arrays

- packages/data-mate/package.json
- packages/data-mate/src/transforms/field-transform.ts
- packages/data-mate/test/field_transform-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- toBoolean in data-mate will now return null when input is null/undefined
- utils toBoolean behaviour is **unchanged**. This will return a bool with null/undefiend.
> hotfix for data-mate

- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/env.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
The [`webpack.DefinePlugin`](https://webpack.js.org/plugins/define-plugin/) only allows getting the `NODE_ENV` environment variable using `process.env.NODE_ENV` and doesn't work with destructuring.
> Fix process.env usage in @terascope/utils for webpack

- Dockerfile
- package.json
- packages/teraslice/package.json
Updates docker base image to `terascope/node-base:10.19.0-2`, fixes node-rdkafka ssl issues.
The base image switches back to using alpine
Closes https://github.com/terascope/teraslice/issues/1868
> v0.64.5 - Update base docker image to fix node-rdkafka

- .travis.yml
- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/sync.ts
- packages/scripts/src/helpers/docs/index.ts
- packages/scripts/src/helpers/docs/sidebar.ts
- packages/scripts/src/helpers/docs/typedoc.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/misc.ts
- packages/scripts/src/helpers/packages.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/signale.ts
- packages/scripts/src/helpers/sync/configs.ts
- packages/scripts/src/helpers/sync/index.ts
- packages/scripts/src/helpers/sync/utils.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/interfaces.ts
- packages/scripts/src/helpers/test-runner/tracker.ts
- scripts/build-doctor.sh
- scripts/link-pkg.sh
- scripts/unlink-pkg.sh
- tsconfig.json
- yarn.lock
- Makes sure it is possible to have workspes outside of the packages directory (like `asset-bundles`)
- Tests output improves, better SIGTERM / SIGINT handling, and making sure to exit with correct status code with tests do not complete fully.
- Fix publish output and prerelease check
- Fix sync command to not output when `--quiet` is used and to better handle failures when there `git` is not available.
- Make sync generate the top level `tsconfig.json` file
- Fix a couple of top level bash scripts to match our internal monorepo (no major updates)
> Allow other workspaces outside of the packages directory and misc ts-scripts fixes

- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/test/api-spec.js
- packages/elasticsearch-api/types/index.d.ts
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/job-components/src/interfaces/index.ts
- packages/job-components/src/interfaces/misc.ts
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice-state-storage/test/elasticsearch-state-storage-spec.ts
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/types/package.json
- packages/types/src/misc.ts
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- fix types in elasticsearch-api
- get/mget/search now return data-entities with metadata
- mget => if full-response is false then it returns an array of data-entities of all found data, it filters out not-found. If you use full response, it returns as normal
> Elasticsearch api fixes

- package.json
- packages/teraslice/package.json
- this is a bump for teraslice so that the slicer api changes in job-components can be manifested
> release: (minor) teraslice@0.68.0

- packages/teraslice-cli/package.json
- yarn.lock
Updating teraslice-cli to use the new github download code.
> Update GitHub fetch to  v0.7.1 in teraslice-cli/earl

- Dockerfile
- package.json
- packages/teraslice/package.json
- updates `terafoundation_kafka_connector` to include `librdkafka@1.4.2` (from `1.2.2`) which includes a fix for [disconnects while rebalancing](https://github.com/edenhill/librdkafka/releases/tag/v1.4.0)
- updates `node` to `12.18.3` (from `12.18.1`) for a potential [memory leak fix](https://github.com/nodejs/node/issues/33266)
> v0.69.2 - update base docker image

- Dockerfile
- package.json
- packages/teraslice/package.json
Fixes a regression in stuck workers we found in the latest version of node-rdkafka/librdkafka
> v0.69.3 - Reverts version of librdafka due to regression in stuck workers

- package.json
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8s.js
- packages/teraslice/package.json
This PR reverts Teraslice execution stopping (in k8s) back to the original `deleteExecution` implementation.  The newer implementation, still present as `deleteExecutionControlled` takes longer to shutdown, and with a five minute node shutdown timeout, will take MORE than five minutes to shut down in cases with a stuck worker.
Also, we encountered this error:
```
[2020-08-12T22:41:22.156Z] ERROR: teraslice/19 on teraslice-cluster1-master-82828282: Error encountered deleting pod deployment, continuing execution controller shutdown: Error: Timeout Waiting: pods matching app.kubernetes.io/component=worker,teraslice.terascope.io/exId=257246 is 1/0 (assignment=cluster_master, module=kubernetes_cluster_service, worker_id=qpKc8-kF)
Error: Error encountered deleting pod deployment, continuing …
```
> switch to the old deleteExecution

- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/index-manager.ts
- packages/elasticsearch-store/src/index-model.ts
- packages/elasticsearch-store/src/index-store.ts
- packages/elasticsearch-store/src/interfaces.ts
- packages/elasticsearch-store/src/utils/elasticsearch.ts
- packages/elasticsearch-store/src/utils/validation.ts
- packages/elasticsearch-store/test/helpers/elasticsearch.ts
- packages/elasticsearch-store/test/index-manager-index-setup-spec.ts
- packages/elasticsearch-store/test/index-manager-spec.ts
- packages/elasticsearch-store/test/index-store-timeseries-spec.ts
- packages/elasticsearch-store/test/utils-spec.ts
- Fix time series support in elasticsearch-store
- Add `writeIndex` to  `IndexStore`
- Add `aggregate` function to `IndexStore`
- Add the ability to pass in more configuration options from `IndexModelConfig`
- Add `createBulkRecord` to `IndexModel`
- BREAKING: `indexQuery` is now `searchIndex` to  `IndexStore`
- BREAKING: The first argument to `getDefaultParams` in `IndexStore` is now the index to use
- Fix spelling issues
> Fix time series index support in elasticsearch-store

- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/test/api-spec.js
- packages/teraslice-state-storage/package.json
- packages/teraslice/package.json
* removes `type` from queries and bulk request
* expanded tests
* bumped version to 0.21.3
> elasticsearch-api remove type from es7 queries and bulk requests

- packages/data-mate/package.json
- packages/data-mate/src/aggregation-frame/AggregationFrame.ts
- packages/data-mate/src/column/Column.ts
- packages/data-mate/src/core/utils.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/src/index.ts
- packages/data-mate/src/vector/Vector.ts
- packages/data-mate/test/aggregation-frame-spec.ts
- packages/data-mate/test/data-frame-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- Adds multiple field orderBy support. **BREAKING** The interface changed from `orderBy(field(s), direction)` to `orderBy("${field}:${direction}")`
- Adds `getColumnOrThrow` to `DataFrame` for better errors
> Data frame multi field order by

- packages/data-mate/package.json
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-parser/src/parser.ts
- packages/xlucene-parser/src/utils.ts
- packages/xlucene-translator/package.json
- packages/xlucene-translator/src/translator/utils.ts
- packages/xlucene-translator/test/cases/translator/logical-group.ts
- packages/xpressions/package.json
- packages/xpressions/src/evaluate.ts
- packages/xpressions/src/interfaces.ts
- packages/xpressions/src/parse.ts
- packages/xpressions/src/transform.ts
- packages/xpressions/test/evaluate-spec.ts
- packages/xpressions/test/parse-spec.ts
- packages/xpressions/test/transform-spec.ts
- tsconfig.json
- Allow nil values in xLucene variables when used in the context of an OR variable
- Change xpressions to support explicit variables using $
- Improve xpression API to be more composable
> Allow nil values in xLucene ORs and xpression improvements

- packages/data-mate/package.json
- packages/data-mate/src/validations/field-validator.ts
- packages/data-mate/test/field_validator-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
date-mate field validator was not checking ips in the loopback range
since both isRoutableIp and IsNonRoutableIP shared basically the same logic I extracted the publicIP check to it's own function.  Not sure if that is the best place for it.  I checked in @terascope/utils but didn't see an obvious place there.
If it should go somewhere else let me know
Added tests to include all the private ip ranges and loopback range
bumped data-mate to 0.20.2
> Ip routable fix

- packages/data-mate/package.json
- packages/data-mate/src/vector/ListVector.ts
- packages/data-mate/src/vector/interfaces.ts
- packages/data-mate/src/vector/types/TupleVector.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
Adds a `skipEmptyArrays` option to DataFrame serialize options which will allow removing empty arrays
> Add skipEmptyArrays to DataFrame serialize options

- packages/data-mate/package.json
- packages/data-mate/src/aggregation-frame/AggregationFrame.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/test/data-frame-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- Add support to limit in appendAll so we can avoid extra overhead
- Fix getColumnOrThrow error message
> Add limit to DataFrame.appendAll

- package.json
- packages/terafoundation/package.json
- packages/terafoundation/src/connectors/s3.ts
- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/tjm-util.ts
- packages/teraslice-cli/test/lib/config-spec.ts
- packages/teraslice-cli/test/lib/tjm-util-spec.ts
- packages/teraslice/lib/cluster/services/execution.js
- packages/teraslice/package.json
Sometimes in development an execution gets stuck in stopping status since the process gets force killed in before it can be updated to stopped. Now the execution will be marked as stopped when starting up the execution service. I didn't add tests because it is not really testable. 
I also fixed an error message in the s3 connector
> v0.73.1 - Make sure stopping jobs get set to stopped

- packages/scripts/package.json
- packages/scripts/src/cmds/bump.ts
- packages/scripts/src/cmds/publish.ts
- packages/scripts/src/helpers/bump/interfaces.ts
- packages/scripts/src/helpers/bump/utils.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/interfaces.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/test/bump-spec.ts
- Add `--skip-reset` to bump script
- Add `--publish-outdated-packages` to publish
- Improvements to npm publish and docker push when there are unexpected errors
These flags are added to deal some edge cases particularly around bumping hot fix branches
> Add special flags to ts-scripts bump and publish

- package.json
- packages/teraslice/package.json
- this is a belated version update for teraslice as it was not updated when the new oploader changes was brought in
- this should allow loading of bundled type assets in teraslice
> release: (minor) teraslice@0.74.0

- packages/data-mate/package.json
- packages/data-mate/src/core/IPValue.ts
- packages/data-mate/src/validations/field-validator.ts
- packages/data-mate/test/field_validator-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
* changes to validation ip to allow for ipv4 mapped ipv6 addresses
* more thorough routable ip logic based on:
* https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml
*  https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml
* added comprehensive routable ip tests
* bumped version with bump script
> Ip validation upgrade

- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/test/workers/execution-controller/execution-controller-spec.js
- packages/teraslice/test/workers/worker/worker-spec.js
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/numbers.ts
- packages/utils/src/promises.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
`setImmediate` is no longer recommend for use, this fixes a couple cases where we use it. I also removed the `BigInt` warning since it was more annoying than helpful. I figured it would easier to tell it fail when using a `BigInt` instead of prematurally warning about it.
> Fix compatibility of setImmediate

- packages/eslint-config/index.js
- packages/eslint-config/lib/overrides.js
- packages/eslint-config/lib/rules/javascript.js
- packages/eslint-config/lib/rules/typescript.js
- packages/eslint-config/package.json
- Adds support for ecmascript v9 (some features we use that are supported in node 10 weren't parsable by eslint)
- Remove the eslint rule that was recently re-enabled that required more types defined for private functions (that should be up to the developer but recommended).
- Disable `no-useless-return` since that would autofix functions while developing and require adding the returns back in
> Eslint improvements

- packages/data-mate/bench/generate-data.js
- packages/data-mate/bench/serialize-perf-test.js
- packages/data-mate/package.json
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/test/__snapshots__/data-frame-spec.ts.snap
- packages/data-mate/test/data-frame-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
Make `serializeIterator` and `deserializeIterator` a more advanced use case, this also makes `serialize` and `deserialize` a more simple API since the new line joining and splitting is required knowledge.
This also fixes a bug where empty lines caused by ending new lines would cause serialization errors.
> Add a more simple DataFrame serialize/deserialize API

- packages/data-mate/package.json
- packages/data-mate/src/data-frame/utils.ts
- packages/data-mate/test/aggregation-frame-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- Fix groupBy key generation when different fields have the same value
Previously, this would have generated the same group by key for both records since 
the field name or position was not taken into account. This is incorrect, it should have generated two 
different buckets.
```js
[{
"field1": "hello",
"field2": null
}, {
"field1": null,
"field2": "hello"
}]
```
> Fix groupBy key generation

- docs/configuration/clustering-k8s.md
- package.json
- packages/job-components/src/interfaces/jobs.ts
- packages/job-components/src/job-schemas.ts
- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8sResource.js
- packages/teraslice/package.json
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8sResource-spec.js
This changes `external_ports` from a simple array of numbers to an array that can contain numbers or objects, looks like:
```json
"external_ports": [
9090,
{"name": "metrics", "port": 3333}
]
```
> add external port object type

- .yarnclean.ci
- Dockerfile
- package.json
- packages/scripts/src/helpers/test-runner/index.ts
- packages/teraslice-test-harness/src/download-external-asset.ts
- packages/teraslice/package.json
- yarn.lock
[EXPERIMENTAL] Update base image to node 12.22.1 with the latest kafka connector. Last time we tried this we got stuck workers but this is a new version of librdkafka so hopefully we don't run into this.
> v0.76.0 - Update base image kafka connector

- docs/packages/data-mate/functions.md
- packages/data-mate/src/column/aggregations.ts
- packages/data-mate/src/function-configs/object/equals.ts
- packages/data-mate/src/function-configs/string/encode-utils.ts
- packages/data-mate/src/function-configs/string/encode.ts
- packages/data-mate/src/function-configs/string/encodeBase64.ts
- packages/data-mate/src/function-configs/string/encodeHex.ts
- packages/data-mate/src/function-configs/string/encodeSHA.ts
- packages/data-mate/src/function-configs/string/encodeSHA1.ts
- packages/data-mate/src/function-configs/string/encodeURL.ts
- packages/data-mate/src/function-configs/string/index.ts
- packages/data-mate/src/function-configs/string/join.ts
- packages/data-mate/src/validations/field-validator.ts
- packages/job-components/src/operations/convict-schema.ts
- packages/utils/src/equality.ts
- packages/utils/src/objects.ts
- packages/utils/test/deps-spec.ts
- packages/utils/test/equality-spec.ts
- packages/utils/test/objects-spec.ts
> Add generic encode and misc fixes

- .travis.yml
- package.json
- packages/elasticsearch-store/test/index-store-spec.ts
- packages/elasticsearch-store/test/index-store-timeseries-spec.ts
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/teraslice-messaging/test/execution-controller-spec.ts
- packages/teraslice-messaging/test/messenger-spec.ts
- packages/teraslice-op-test-harness/test/harness-spec.js
- packages/teraslice-test-harness/src/download-external-asset.ts
- packages/teraslice-test-harness/src/index.ts
- packages/teraslice-test-harness/test/dowload-external-asset-spec.ts
- packages/ts-transforms/test/loader/loader-spec.ts
- packages/ts-transforms/test/phases/selector-phase-spec.ts
- yarn.lock
- Upgrade to jest 27
- Fix tests that popped up in jest 27
- Make the max number of projects per batch configurable via `MAX_PROJECTS_PER_BATCH`
- Remove duplicate job in travis-ci since we only have 5 concurrent jobs available
- Fix job names in travis-ci name
Closes #2775
> Upgrade jest and ts-jest to 27

- e2e/test/download-assets.js
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/dates.ts
- packages/utils/src/event-loop.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Only download the bundled assets in the e2e tests - this should speed them up
- Fix validation of `JEST_MAX_WORKERS` env
- Don't allow the tests to pass if none ran
- Fixes to EventLoop when logger gets deferenced
- Make tree shaking a little easier when requiring date-fns
Closes https://github.com/terascope/teraslice/issues/2819
> Fix no tests in ts-scripts

- packages/data-mate/package.json
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/src/data-frame/search-utils.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-parser/src/cached-parser.ts
- packages/xlucene-translator/package.json
- packages/xlucene-translator/src/query-access/query-access.ts
- Add support for using a cached xLucene query in DataFrame.search
- bump: (minor) @terascope/data-mate@0.30.0, elasticsearch-store@0.52.0
> Allow passing in a parsed xLucene query to DataFrame.search

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/cmds/assets/deploy.ts
I improve the error message to give the user a clue that the problem may be that there is not a released asset that matches their request, and they can specify the version if they want.
> Teraslice cli asset error message improvement

- packages/data-mate/bench/data-frame-deserialize-suite.js
- packages/data-mate/bench/src.js
- packages/data-mate/package.json
- packages/data-mate/src/core/ReadableData.ts
- packages/data-mate/src/core/WritableData.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/src/data-frame/utils.ts
- packages/data-mate/src/vector/Vector.ts
- packages/data-mate/test/data-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- Improve data frame deserialize performance (not much)
- Use `getColumnOrThrow` in more places to utilize the cache
- Hide the internal storage for Vector data so we can change how it is being stored in the future
> DataFrame improvements

- packages/data-mate/package.json
- packages/data-mate/src/data-frame/utils.ts
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/bench/getHashCodeFrom-suite.js
- packages/utils/package.json
- packages/utils/src/field-type.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
Improve the performance of `getHashCodeFrom` by relying less on md5 and extra function calls. I think this also reduces the likelihood of collisions. We used `md5` when the string length was greater than 35 characters, I changed that to `1024`.
> Faster getHashCodeFrom

- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/job-components/src/interfaces/misc.ts
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/interfaces.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Make `RouteSenderAPI->send` return the number of affected records
- Make `RouteSenderAPI->send` accept an iterable so we can stream process records in the future
- Add comments to the interface
- Move the interface to utils so it can be defined without needing to import job-components, this is useful for some our api packages
These changes should be backwards compatible since the number of affected records can default to the number of input records
> Make `RouteSenderAPI->send` return the number of affected records

- docs/packages/elasticsearch-api/overview.md
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/test/api-spec.js
- packages/elasticsearch-api/types/index.d.ts
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice/lib/storage/analytics.js
- packages/teraslice/lib/storage/backends/elasticsearch_store.js
- packages/teraslice/lib/storage/state.js
- packages/teraslice/package.json
- packages/teraslice/test/test.setup.js
Makes breaking changes to the elasticsearch api `bulkSend` method so that the retries work correctly.
> Breaking changes to `elasticsearch-api->buldSend` to fix retry support

- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/cluster.ts
- packages/elasticsearch-store/src/index-manager.ts
- packages/elasticsearch-store/src/index-model.ts
- packages/elasticsearch-store/src/index-store.ts
- packages/elasticsearch-store/src/index.ts
- packages/elasticsearch-store/test/index-store-spec.ts
> Expand bulk request API in IndexStore to support upserts with scripts

- packages/data-mate/bench/select-rows-perf-test.js
- packages/data-mate/package.json
- packages/data-mate/src/core/ReadableData.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/src/vector/Vector.ts
- packages/data-mate/test/data-frame-spec.ts
- packages/data-mate/test/vector/vector-spec.ts
- packages/elasticsearch-store/package.json
- packages/ts-transforms/package.json
- Minor performance improvements to DataFrame so it doesn't iterate over the columns too much when creating a DataFrame
- Add `DataFrame.appendOne` for a faster alternative to `appendAll` since it does less
- Add memory allocation optimizations to the Vector, ReadableData and WritableData which fixes memory explosions with lots of data buckets
> Performance improvement to DataFrames and add appendOne

- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/elasticsearch-client/create-client.ts
- packages/terafoundation/package.json
- packages/teraslice/package.json
es7 client would throw if using a docker image < 7.13 if elasticsearch. This is is because the client checks for the tagline, version, build_flavor, and headers (x-elastic-product) to verify that it is their product and not something else. 
Since the current opensearch library is backwards compatible with < 7.13, I am opting to use that for those version, and anything greater will use native elasticsearch client as the server should be compliant with their requirements.
I tested this against docker images to verify as this bug did not come up since all my local tests use elasticsearch itself, or docker images of v6 in teraslice. In the next major change to teraslice I will try to include v7 version of tests as well
> fix async client use with docker images

- packages/job-components/package.json
- packages/scripts/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
bump: (minor) @terascope/job-components@0.57.0, teraslice-client-js@0.45.0
bump: (minor) teraslice-cli@0.49.0, @terascope/scripts@0.48.0
> release: (minor) teraslice@0.80.0

- packages/scripts/package.json
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/packages.ts
- packages/scripts/src/helpers/test-runner/index.ts
- Improve compatibility usage on how scripts test-suites can be used with our asset packages, will be first used with elasticsearch-assets
> Allow scripts test suite to better run with asset directory structures

- packages/data-mate/package.json
- packages/data-mate/src/data-frame/search/buildMatcherForNode.ts
- packages/data-mate/src/data-frame/search/buildSearchMatcherForQuery.ts
- packages/data-mate/src/document-matcher/logic-builder/index.ts
- packages/data-mate/src/document-matcher/logic-builder/string.ts
- packages/data-mate/test/data-frame-search-partial-variables-spec.ts
- packages/data-mate/test/matcher/cases/document-matcher/index.ts
- packages/data-mate/test/matcher/cases/document-matcher/partial-variables.ts
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-parser/src/utils.ts
- packages/xlucene-translator/package.json
- undefined variables will turn the logic node to return false as it is inoperable
- this allows dataframes and document matcher to behave more like elasticsearch, so it wont blow up or return wrong data
> Dataframe missing variable field fix

- packages/data-mate/package.json
- packages/data-mate/test/vector/vector-spec.ts
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/elasticsearch-store/src/elasticsearch-client/create-client.ts
- packages/elasticsearch-store/src/index.ts
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/numbers.ts
- packages/utils/test/type-coercion-spec.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- javascript numbers go up to ^51 while an integer in another system is ^31 which causes friction when a value is coerced into a number, this fix makes it more permissable
> Bigint interger bug fix

- examples/k8s/elasticsearchDeployment.yaml
- examples/k8s/teraslice-master.yaml.tpl
- examples/k8s/teraslice-worker.yaml.tpl
I've updated the minikube development setup to use a newer elasticsearch
image (v7.9.3) as well as to use the new elasticsearch-next connector
> update minikube dev for new ES connector

- package.json
- packages/teraslice/lib/storage/backends/elasticsearch_store.js
- packages/teraslice/package.json
- fix's the issue around using the new client type on elasticsearch store startup. It should now be able to wait and recover if teraslice is up before elasticsearch is up.
> Teraslice store startup fix

- packages/teraslice-cli/package.json
- yarn.lock
- lock package  "glob-promise" to version "5.0.0", as "5.0.1" introduces an node engine breaking change to require v16, it would break our v14 servers and tests
> Cli version fix

- package.json
- packages/elasticsearch-api/index.js
- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/test/api-spec.js
- packages/elasticsearch-api/test/bulk-send-dlq-spec.js
- packages/elasticsearch-api/types/index.d.ts
- packages/teraslice-state-storage/package.json
- packages/teraslice/lib/storage/backends/elasticsearch_store.js
- packages/teraslice/lib/workers/execution-controller/scheduler.js
- packages/teraslice/package.json
- packages/teraslice/test/workers/execution-controller/scheduler-spec.js
Reverted changes to apis and tests from the previous dead-letter-queue related pr and changed the dead letter queue action to update the docs metadata instead of returning the docs with non-retryable errors.  This allows the class apis and tests to remain the same while still supplying the dlq info for each doc sent to elasticsearch.
> Dlq refactor

- package.json
- packages/terafoundation/package.json
- packages/terafoundation/src/connectors/s3.ts
- packages/teraslice/package.json
- yarn.lock
- use newest s3 v3 client creation in terafoundation
- ASSET COMPATIBILITY CHANGES , must use file-asset `>= v2.4.0` for correct compatibility, if using older file-assets then use teraslice < `v84.0`
> S3 connector changes

- docker-compose.yml
Update docker-compose.yml file:
Upgrade Elasticsearch from version 6.5.4 to version 7.9.3
refs:
#3392
> Upgrade Elasticsearch from version 6.5.4 to 7.9.3 in docker-compose.yml

- .github/dependabot.yml
Changes to dependabot.yml file:
- under `directory: '/website'` add:
ignore:
- dependency-name: "*"
> Update dependabot.yml to ignore /website dependencies

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/cmds/assets/deploy.ts
I added an ```If``` statement on line 138 inside ```teraslice/packages/teraslice-cli/src/cmds/assets/deploy.ts```
```diff
File: deploy.ts
130:         } else if (cliConfig.args.build || assetJsonExists) {
131:             const asset = new AssetSrc(
132:                 assetJsonExists ? '.' : cliConfig.args.srcDir,
133:                 cliConfig.args.dev
134:             );
135: 
136:             try {
137:                 reply.green('Beginning asset build.');
+ 138:                 if (cliConfig.args.replace) {
+ 139:                     asset.overwrite = true;
+ 140:                 }
141:                 const buildResult = await asset.build();
142:                 assetPath = buildResult.name;
143:                 reply.green(`Asset created:\n\t${buildResult.name} …
```
> add feature to terasclice-cli replace flag

- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/packages.ts
I made some updates based off of our final pr with the main branch here #3408
The main updates are: 
- Refactored code by removing ```console.logs``` and unnessesary comments
- Updating tests inside [bump-spec.ts](https://github.com/terascope/teraslice/blob/bump-asset-feature-dev-fix/packages/scripts/test/bump-spec.ts) to use temp files while testing "Bump Assets" instead of creating files in the root directory.
- Fixed a bug that added "asset:false" inside of the root ```package.json``` inside of teraslice causing "verify build" to fail on GitHub actions.
> Bump asset feature dev fix

- docs/packages/test-pkg/overview.md
- packages/scripts/src/cmds/bump-asset.ts
- packages/scripts/src/cmds/bump.ts
- packages/scripts/src/helpers/bump/index.ts
- packages/scripts/src/helpers/bump/interfaces.ts
- packages/scripts/src/helpers/bump/utils.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/packages.ts
- packages/scripts/src/helpers/sync/utils.ts
- packages/scripts/test/bump-asset-spec.ts
- packages/scripts/test/bump-spec.ts
Create a new command called `bump-asset` that will bump an assets version without bumping any package versions.
> Ts scripts bump asset only

- e2e/package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
bump: (patch) @terascope/data-mate@0.46.2, elasticsearch-store@0.71.2
bump: (patch) terafoundation@0.49.2, ts-transforms@0.75.2
bump: (patch) xlucene-parser@0.49.1, xlucene-translator@0.34.2
bump: (patch) @terascope/elasticsearch-api@3.10.2, @terascope/teraslice-state-storage@0.43.2
bump: (patch) generator-teraslice@0.29.2, @terascope/job-components@0.63.2
> bump: (patch) @terascope/utils@0.50.1, @terascope/data-types@0.41.2

- e2e/package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
bump: (minor) @terascope/data-mate@0.47.0, elasticsearch-store@0.72.0
bump: (minor) terafoundation@0.50.0, ts-transforms@0.76.0
bump: (minor) xlucene-parser@0.50.0, xlucene-translator@0.35.0
bump: (minor) @terascope/elasticsearch-api@3.11.0, @terascope/teraslice-state-storage@0.44.0
bump: (minor) generator-teraslice@0.30.0, @terascope/job-components@0.64.0
> bump: (minor) @terascope/utils@0.51.0, @terascope/data-types@0.42.0

- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- e2e/docker-compose.yml
- e2e/test/download-assets.js
- packages/scripts/src/cmds/publish.ts
- packages/scripts/src/cmds/test.ts
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/interfaces.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/interfaces.ts
- packages/scripts/test/service-spec.ts
- packages/scripts/test/test-runner-spec.ts
This PR adds support to the `ts-scripts` in `packages/scripts` to build docker images for different versions of Nodejs.
refs:
#3354
> add support for building docker images with multiple versions of node

- packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/index.js
There was a breaking change between k8s v1.26 and v1.27.
Within a k8s job yaml file the `spec.selector.matchLabels.controller-uid` field was changed to `spec.selector.matchLabels.batch.kubernetes.io/controller-uid`.
> Change label used to get execution controller pod

- package.json
- packages/teraslice/package.json
This release adds a bunch of package updates as well as added support for Teraslice running on k8s 1.27+.
We've also decided that this will probably be the last release of Teraslice on node 14.
> release: (patch) teraslice@0.86.3

- e2e/package.json
- packages/data-mate/package.json
- packages/data-mate/src/aggregation-frame/AggregationFrame.ts
- packages/data-mate/src/builder/Builder.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/test/aggregation-frame-spec.ts
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
MergeBy merges unique values from the specified fields together into a single record... if there are multiple values for the same field, the merged record will be the last value in the list of records.
Decided to not allow a frame to call groupBy and mergeBy in the same aggregation for now because would need to know whether to allow other aggregations (sum, count, select, etc) on both or just one and currently you can call those before or after groupBy so we would need to rework
> add mergeBy aggregation

- .github/workflows/publish-tag.yml
- package.json
- packages/teraslice/package.json
CI still failed due to missing docker credentials on push.  This fixes that.
> release: (patch) teraslice@0.86.5

- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- package.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/eslint-config/test/index-spec.js
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/teraslice/lib/cluster/services/api.js
- packages/teraslice/package.json
- yarn.lock
This PR is the start of the migration away from node 14 and to set node 18 as the primary node version of teralice. Node 18 tests failed due to the got library having a bug in streaming redirects (used in asset processes) so we updated the library to use the ESM version which forces the cut of node 14
> re-enable node 18 tests, remove node 14 tests

- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/test-runner/services.ts
I have followed the instructions and guidance of issue #3363 to hopefully fix the opensearch timeout problem. 
- Updated the default opensearch version to be  `v1.3.10`
> > This is to have access to an environment variable that can turn off the performance analyzer.
- Set DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI to 'true' for opensearch container
> > This will ideally stop opensearch from failing to startup randomly 
References to this solution [here](https://github.com/terascope/teraslice/issues/3363#issuecomment-1646317566)
> Fix ts scripts opensearch timeout

- e2e/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/xlucene-translator/package.json
- packages/xlucene-translator/src/query-access/query-access.ts
- packages/xlucene-translator/test/query-access-spec.ts
> add restriction for regexp queries when prevent_prefix_wildcard

- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- packages/scripts/src/cmds/publish.ts
- packages/scripts/src/cmds/test.ts
- packages/scripts/src/helpers/config.ts
I have replaced all node versions with the new base docker node versions
The new node versions are now:
- `node 16.20.2`
- `node 18.18.2`
This issue is referenced here #3459
> Update node versions

- package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice/package.json
I have fixed a bug that happens on node 18 that is addressed here #3457
The issue was that the execution client has a variable called ```serverShutdown``` that gets set to ```true``` when the masterpod is told to shutdown. But when the master pod is booted back up and reconnects with the client, the client can no longer send execution analytics to the master pod causing the following error.
```
[2023-11-27T17:49:38.468Z] ERROR: teraslice/10 on ts-exc-kafka-to-es-e052b800-fee7-6vwqv: Client ClusterMaster is not ready (assignment=execution_controller, module=messaging:client, worker_id=_Q15YZQ9, ex_id=c3c188b1-4884-4867-bf86-c126f7b24034, job_id=e052b800-fee7-4af6-994b-3f5a4f78fd31)
Error: Client ClusterMaster is not ready
at Client.waitForClientReady …
```
> Node 18 master pod restart fix

- e2e/test/config.js
- e2e/test/global.setup.js
- e2e/test/setup-config.js
- e2e/test/teraslice-harness.js
- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/k8s-env/interfaces.ts
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/scripts/src/helpers/scripts.ts
This PR includes the following changes:
- Add the `--rebuild` option to `ts-scripts k8s-env`
- Use `yarn k8s:rebuild` script from root of teraslice
- This allows you to build a new Teraslice docker image and restart Teraslice in your k8s cluster. Previously you had to delete the cluster and re-run `yarn k8s`. Now services and the cluster do not need to be rebuilt.
- Changes to how teraslice and elasticsearch ports are determined. 
- Elasticserach store data is preserved between rebuilds. We may need to add the option to reset the ES store.
> Add the --rebuild option to the k8s-env command

- packages/docker-compose-js/package.json
- packages/docker-compose-js/src/index.ts
- Updated docker-compose-js package to use `docker compose` by default instead of `docker-compose`
- This is because Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.
- NOTE: `docker-compose` is still backwards compatible if `docker compose` is not present.
- Bump **packages/docker-compose-js** from `v1.3.1` to `v1.3.2`
- Added user feedback in the event that `docker-compose` or `docker compose` is not installed.
ref to issue #3350
> update docker-compose-js to use newer 'docker compose' command

- packages/scripts/package.json
- packages/scripts/src/helpers/sync/configs.ts
- packages/teraslice/package.json
This PR fixes an issue listed here #3490
- Changed `terascope.main` in the teraslice `package.json` back to true. 
- This fixes an expectation in the code that relies on this to be true
- Removed check in the `generateTSConfig()` method that checks for `terascope.main` in every package.
- This conflicts with the change above and is believed to be unnecessary. It's also problematic now that the teraslice package has been converted to typescript. 
- Bumped @terascope/scripts from v0.63.0 to v0.63.1
> Ts-scripts publish fix

- .github/workflows/publish-master.yml
- packages/scripts/package.json
- packages/scripts/src/helpers/doc-builder/typedoc.ts
- packages/terafoundation/src/master.ts
- yarn.lock
Typedoc v0.23.28 was not compatible with typescript v5.2.2.
The following packages were upgraded:
- typedoc from v0.23.28 to v0.25.4
- typedoc-plugin-markdown from 3.14.0 to 3.17.1
The `typedoc.Application` class now requires a call to `bootstrapWithPlugins()` to initialize.
Ref: #3489
>  Update typedoc to be compatible with current typescript version.

- docs/management-apis/endpoints-json.md
- package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/index.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8s.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/native/index.ts
- packages/teraslice/src/lib/cluster/services/execution.ts
- packages/teraslice/src/lib/cluster/services/interfaces.ts
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8s-spec.ts
This PR adds a `force` option to the `POST /jobs/{jobId}/_stop` and `POST /ex/{exId}/_stop` endpoints
- include `force='true'` as a request parameter to forcefully stop all jobs, deployments, replicaSets and pods labeled with the execution ID in the url or the execution ID associated with the jobID in the url.
- This overrides the default behavior of not allowing a job with a status of `'completed', 'stopped', 'rejected', 'failed', 'terminated', or 'stopping'` to be stopped.
- Endpoint documentation updated.
- Adds a test for deleting with force set to true.
- Modifies `delete` job, service, and deployment tests to expect the complete response, not the response.body.
Ref: #2670
> Add force option to POST /jobs/jobId/_stop and POST /ex/exId/_stop endpoints

- docs/development/k8s.md
- e2e/k8s/kindConfigDefaultPorts.yaml
- e2e/k8s/kindConfigTestPorts.yaml
- e2e/k8s/masterDeployment.yaml
- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/scripts/src/cmds/test.ts
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/k8s-env/interfaces.ts
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/scripts/src/helpers/kind.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/interfaces.ts
- packages/scripts/src/helpers/test-runner/services.ts
- This PR allows for the setting of a `K8S_VERSION` env variable when running `yarn test:k8s` or `yarn k8s` (#3482)
- The env variable is converted to a command option which is used by the `Kind` class to create a kind cluster using that k8s version. 
- A map of `kind` versions to available images lives in the `Kind` class and will need to be updated with new kind versions.
- K8s images are limited to one minor version per kind version, with the patch level equal to the latest version at release time. For example:
- kind v0.20.0 --> kindest/node:v1.26.6
- kind v0.19.0 --> kindest/node:v1.26.4
- kind v0.19.0 --> kindest/node:v1.26.3
- Create Kind class
- add `clusterName` option to k8s
> Add K8s version parameter to kind cluster creation

- docs/management-apis/endpoints-json.md
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/index.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8s.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/native/index.ts
- packages/teraslice/src/lib/cluster/services/execution.ts
- packages/teraslice/src/lib/cluster/services/jobs.ts
- Add check for orphaned resources by job_id before starting job.
- Add listResourcesForJobId function to execution service.
- Add listResourcesForJobId function to k8s and native cluster backends.
- Improve messaging to user when using force option on the POST /jobs/{job_id}/_stop endpoint
- Remove check for native clustering when using force stop.
- Update docs for _stop endpoint to show an example using force
> Check for orphaned processes by job_id when starting a job

- packages/teraslice-cli/package.json
- packages/teraslice-cli/test/cmds/assets/init-spec.ts
- packages/teraslice-cli/test/generators/new-asset-spec.ts
- packages/teraslice-cli/test/generators/new-processor-spec.ts
- Changed tests inside `teraslice-cli` to use temp directories instead of sharing directories
- This separates state between tests and guarantee directories even when tests are ran in parallel 
This fixes an issue posted here #3494
> Change teraslice-cli tests to use temp dir

- packages/scripts/package.json
- packages/scripts/src/cmds/publish.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/interfaces.ts
- packages/scripts/src/helpers/test-runner/index.ts
- Added a `node-suffix` flag in `ts-scripts publish` to allow the ability to include or exclude a node version suffix in a docker image tag 
- By default it's set to `true` to maintain original functionality
> add nodeSuffix flag to scripts publish

- Dockerfile
- package.json
- packages/teraslice/package.json
- scripts/docker-pkg-fix.js
- scripts/wait-for-it.sh
- Rewrite docker file:
- Discontinue use of `base-docker-image`
- Create a multi-stage build:
- base stage:
- build image from `debian-bookworm`
- combine functionality from the `base-docker-image` with the yarn build step to create `/app` directory
- second stage:
- build image from `debian-bookworm-slim`
- copy `/app` artifact from base stage, minimizing dependencies
- Copy the following scripts from `base-docker-image` repo to `teraslice/scripts`:
- `docker-pkg-fix.sh` (this doesn't seem to be used anywhere)
- `wait-for-it.sh`
ref: #3518
> Create a multistage docker image from a debian-bookworm base

- e2e/test/config.js
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/test/publish-spec.ts
- Pass in the node version to `getDevDockerImage` - this fixes the undefined, but results in the node version being added to the tag twice.
- Automatically add node suffix to all tags.
- Create `removeNodeSuffixFromTag` function. This turns something like `v0.91.0-nodev18.18.2` into `v0.91.0`.
- Add checks for `options.nodeSuffix` and removes the tag if `false`.
I chose to add the node suffix by default to make the transition simple when we decide that having a tag without a node suffix will never be necessary. At that point we can update `formatDailyTag()` to take `nodeVersion` as a parameter and update its test.
```
with node suffix:
daily         terascope/teraslice:daily-2024.01.12-fe31c87bf9f-nodev16.20.2
dev …
```
> Fix Docker tag logic to prevent undefined in dev tag

- docs/development/k8s.md
- packages/scripts/package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/k8s-env/interfaces.ts
Add `--reset-store` option to `k8s-env` command.
- Issues the command `kubectl delete -n services-dev1 -f elasticsearchDeployment.yaml` to delete service, then `kubectl create -n services-dev1 -f elasticsearchDeployment.yaml` to restart it.
- Only works with `--rebuild` flag, otherwise ignored
- Use `k8s-env --rebuild -reset-store` to rebuild teraslice and reset elasticsearch. 
- Use `k8s-env --rebuild --skip-build -reset-store` to reset teraslice and elasticsearch without a rebuild.
ref: #3483
> K8s env reset es store option

- e2e/test/config.js
- e2e/test/docker-helpers.js
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/misc.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- Updates `getDevDockerImage()` to add node suffix to the image tag passed in by spaces. This allows the right image to be used in e2e tests. The suffix will be removed in the publish stage of spaces, where it is not needed.
- Add a check in e2e tests to ensure the teraslice node version matches the desired version.
> Add node version to spaces e2e image

- package.json
- packages/teraslice-cli/package.json
- yarn.lock
This will limit `isbinaryfile` to a version less than `5.0.1` across All dependency trees. The second resolution (`"yeoman-environment/isbinaryfile": "4.0.10"`) will ensure that major versions 4 and 5 are both present to meet the requirements of all packages.
> Resolution change ts cli

- e2e/package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/errors.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
Browsers like Chrome running off v8 can captureStackTrace, but browsers like Safari running off javascriptcore don't seem to have this function defined
Closes #3557
> fix Error.captureStackTrace if not defined

- Dockerfile
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/teraslice/package.json
Update default node version in `Dockerfile`and `config.ts` from `18.18.2` to `18.19.1`
Bump teraslice to `1.0.0`
> Update default node versions to 18.19.1 and release Teraslice 1.0.0

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/jobs.ts
- packages/teraslice-cli/test/helpers/jobs-spec.ts
* no longer errors if job finishes before status check
* updated language for job that doesn't have a stopped status on restarting
* minor consistency fixes in message properties
> fix error if job finishes before status check

- package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- yarn.lock
- Updates **@terascope/file-asset-apis** from `v0.12.0` to `v0.12.1`
- This fixes a TLS bug referenced here:
https://github.com/terascope/file-assets/issues/960
- Bumps **terafoundation** from `v0.58.0` to `v0.58.1`
- Bumps **teraslice** from `v1.1.0` to `v1.1.1`
> Update File Assets Api 

- e2e/test/cases/data/recovery-spec.ts
- e2e/test/download-assets.ts
- e2e/test/teraslice-harness.ts
- export the array of e2e autoloaded assets
- Use the array of autoloaded assets in `TerasliceHarness.getBaseAssetIds()` to get the IDs of autoloaded assets
- Use `TerasliceHarness.getBaseAssetIds()` in `recovery-spec` to set the `jobSpec.assets` array to only the autoloaded assets.
These changes prevent the `recovery-spec` from trying to use assets placed in the `teraslice.assets_directory` by other tests running in parallel, that have not finished uploading to ES.
Ref: #3567
> Fix recovery-spec test to use only the autoloaded assets in the jobSpec

- package.json
- packages/terafoundation/package.json
- packages/terafoundation/src/schema.ts
- packages/terafoundation/test/validate-configs-spec.ts
- packages/teraslice/package.json
- Fixes issue where `terafoundation` validation fails if `elasticsearch-next` is the connection_type without a default connection
- Added test that checks said scenario 
- Removed `elasticsearch`  from the list of valid asset storage connection types
Ref to issue #3578
> Asset storage connection validation bug fix

- config/docker-teraslice-master.yml
- config/docker-teraslice-worker.yml
- docs/configuration/clustering-k8s.md
- docs/configuration/clustering-native.md
- docs/configuration/overview.md
- docs/getting-started.md
- docs/packages/terafoundation/overview.md
- e2e/k8s/masterConfig/teraslice.yaml
- e2e/k8s/workerConfig/teraslice.yaml
- examples/config/teraslice-master-k8s.yaml
- examples/config/teraslice-master.yaml
- examples/config/teraslice-worker.yaml
- examples/es-to-s3/config/docker-teraslice-master.yml
- examples/es-to-s3/config/docker-teraslice-worker.yml
- examples/k8s/Makefile
- examples/k8s/teraslice-master.yaml
- examples/k8s/teraslice-master.yaml.tpl
- examples/k8s/teraslice-worker.yaml
- examples/k8s/teraslice-worker.yaml.tpl
- package.json
- packages/job-components/package.json
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/register-apis-spec.ts
- packages/scripts/package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/config/default-sysconfig.ts
Had a weird issue updating another PR w/master before merging where e2e tests failed that hadn't on the PR that changed  it so wanted to fix it here but CI failed so decided to just fix it in the range coercion PR instead.  Ci was retried the next morning and worked for these changes.
> remove old elasticsearch from more places

- e2e/package.json
- e2e/test/download-assets.ts
When e2e tests download the latest version of default assets to autoload, the `deleteOlderAssets` function would run. The node version was not being checked, resulting in all duplicate assets with the same version being erased, regardless of node version.
This function will now delete all autoload files that do not match the teraslice node version before checking for older asset versions.
Ref: #3566
> Consider node version when calling deleteOlderAssets() in e2e

- packages/teraslice/src/lib/storage/backends/s3_store.ts
- packages/teraslice/test/services/assets-spec.ts
- packages/teraslice/test/storage/assets_storage-spec.ts
- packages/teraslice/test/storage/s3_store-spec.ts
This PR refactors the s3 store backend in teraslice to use the proper terafoundation `createClient` function instead of using the `createClient` directly from `file-assets-apis`.
> Change s3 store to use terafoundation createClient

- packages/terafoundation/package.json
- packages/teraslice/test/storage/s3_store-spec.ts
- yarn.lock
- Updates `s3_store-spec` tests to import from `file-asset-apis` instead of `aws-sdk`
- Remove `aws-sdk` as a dependency in `terafoundation`
- Updates the following dependencies:
- **express** from `v4.18.2` to `v4.19.2`
- **gc-stats** from `v1.4.0` to `v1.4.1`
- **nanoid** from `v3.3.6` to `v3.3.7`
- **tmp** from `v0.2.1` to `v0.2.3`
- **yeoman-generator** from `v5.9.0` to `v5.10.0`
- **@types/semver** from `v7.5.6` to `v7.5.8`
- **nock** from `v13.5.1` to `v13.5.4`
> Bundled deps update  

- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/jobs.ts
- When marking a job as `_inactive` using the JSON API, job validation will be skipped. An old job may not have the needed connectors, assets, etc to pass validation, but we still want to be able to mark it as inactive.
- This will only skip validation when switching active from true or undefined to false.
- Bump teraslice from **1.2.0** to **1.2.1**
Ref: #3471
> add bypass option to skip validation for _inactive jobs

- package.json
- packages/teraslice/package.json
- Updates base image that updates `terafoundation_kafka_connector` from `0.11.1` to `0.12.0` and `node-rdkafka` to `3.0.1`
- Bump **teraslice** from `v1.2.1` to `v1.3.0`
> Release Teraslice v1.3.0

- e2e/test/cases/assets/simple-spec.ts
- e2e/test/fixtures/jobs/generator-large-asset.json
- e2e/test/teraslice-harness.ts
- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/storage/backends/s3_store.ts
- packages/teraslice/src/lib/workers/assets/loader.ts
- packages/teraslice/src/lib/workers/assets/spawn.ts
- packages/teraslice/test/storage/assets_storage-spec.ts
- packages/teraslice/test/storage/s3_store-spec.ts
This PR makes the following changes: 
- Improves the s3 backend get() requests to grab assets in a more memory efficient way
- This resolves and issue where pulling and decompressing large assets from s3 would cause and OOM on the execution controller on job startup 
- Add error message when asset loader would close with an error that advises what to do in the case of an OOM issue 
Ref to issue #3595
> Large asset Ex OOM fix when in s3 asset mode

- packages/job-components/package.json
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/test-helpers-spec.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice-test-harness/src/base-test-harness.ts
- packages/teraslice-test-harness/src/interfaces.ts
- packages/teraslice/package.json
- Adds the ability for `mockPromMetrics` in the `job-components` `TestContext` to properly gather metrics by labels. This was necessary to test `count_by_field` in `standard-assets`.
- Add `clusterManagerType` to `JobHarnessOptions` used by the `base-test-harness`. This will set `context.sysconfig.teraslice.cluster_manager_type`, which must be `kubernetes` for prom metrics to be enabled.
> Add proper label functionality to mockPromMetrics

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/generator-teraslice/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/types/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
Add `prom-metrics` dependency to `types` package
Bump `types` from 0.17.0 to 0.17.1
Bump `teraslice` from 1.5.0 to 1.5.1
> Add prom-client dependency to types

- docs/development/k8s.md
- package.json
- packages/job-components/package.json
- packages/job-components/src/interfaces/context.ts
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/test-helpers-spec.ts
- packages/terafoundation/package.json
- packages/terafoundation/test/apis/prom-metrics-spec.ts
- packages/terafoundation/test/test-context-spec.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/cluster_master.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
- add `teraslice_` prefix to `promMetrics.init()` for master so all metric names match what was in `teraslice-exporter` package.
- update `mockPrommetrics` to use `prom-client`. This allows `collect()` functions to be used in `TestContext`.
> Prom client in mock prom metrics

- docs/development/k8s.md
- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
This PR fixes a bug introduced in #3613, where the worker's `slicesProcessed` promMetric `collect()` function would throw an error when metrics were scraped, causing the pod to crash.
> fix broken promMetric collect callback

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/yargs-options.ts
- Adds `node22` to the bundle-target list in `teraslice-cli`
- Bumps **teraslice-cli** from `v1.6.0` to `v1.6.1`
> Add node22 to teraslice-cli

- package.json
- packages/teraslice/package.json
Build new teraslice image on top of `base-docker-image` with `terafoundation_kafka_connector@v0.13.0`.
> release: (minor) teraslice@1.7.0

- package.json
- packages/teraslice/package.json
This PR updates the `terafoundation_kafka-connector` which includes a fix that will allow older kafka assets to work on this release of Teraslice.
> release: (patch) teraslice@1.7.1

- docs/development/k8s.md
- package.json
- packages/job-components/package.json
- packages/job-components/src/execution-context/base.ts
- packages/terafoundation/package.json
- packages/terafoundation/src/api/index.ts
- packages/terafoundation/src/api/prom-metrics/prom-metrics-api.ts
- packages/terafoundation/test/apis/prom-metrics-spec.ts
- packages/teraslice-op-test-harness/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/cluster_master.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
This is a follow-up PR to #3629 which created a utility function to test if promMetrics are available, allowing assets to be backward compatible with teraslice before promMetrics were introduced (< 1.4.0). At the same time we decided to just make `isPromAvailable()` checks everywhere promMetrics was used, instead of using a proxy to catch calls to undefined functions. See #3625 for more details.
- Removes the `promMetricsAPI` Proxy from `terafoundation`
- Add checks using `isPromAvailable` before all calls to `promMetricsAPI` functions.
- Update `promMetrics docs`.
- Bump teraslice from 1.7.1 to 1.7.2
- Bump job-components from 0.75.0 to 0.75.1
- Bump terafoundation from 0.64.0 to 0.64.1
> Remove PromMetrics proxy, check for promMetrics with isPromAvailable()

- packages/teraslice/src/lib/cluster/services/execution.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- The `ExecutionController` `_verifyExecution()` function now marks the execution status as failed if the current status is a `running` status ('recovering', 'running', 'failing', 'paused', 'stopping'). We can't start from a running state so the job will be stopped, but we were not updating the status previously. The assumption is that one of these statuses means that the execution controller pod has crashed and k8s is restarting a new pod. We would never get in this situation in native clustering, as there are check before the execution controller process is forked.
- The `ExecutionService` `_finishExecution()` function also marks the execution status as failed if in a `running` status. It looks like this function is designed to run after an execution …
> mark running jobs as failed on exc k8s restart

- packages/job-components/src/test-helpers.ts
- packages/teraslice/src/lib/cluster/node_master.ts
- packages/teraslice/src/lib/workers/helpers/worker-shutdown.ts
- packages/types/src/terafoundation.ts
- Fixes issue where the `node_master` process  doesn't shutdown in the event that the `cluster_master` or the `asset_service` child process exits with an error 
- This will result in the master pod being left in the `running` state instead of `failed` with a `restartCrashLoop`
- #3596
> Add node_master child process shutdown logic

- docs/development/k8s.md
- packages/job-components/test/test-helpers-spec.ts
- packages/terafoundation/src/api/index.ts
- packages/terafoundation/src/api/prom-metrics/prom-metrics-api.ts
- packages/terafoundation/src/test-context.ts
- packages/terafoundation/test/apis/prom-metrics-spec.ts
- packages/terafoundation/test/test-context-spec.ts
- packages/teraslice/src/lib/cluster/cluster_master.ts
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
- packages/types/src/terafoundation.ts
The default label `name` was being set at `PromMetrics` class creation within `terafoundation` instead of being set at initialization. It previously was getting the value for `name` from `context.name`, but this doesn't always match with `teraslice.name` and would never be correct if used with `spaces`.
There is now a test in `prom-metrics-spec.ts` that checks the default labels for the correct values.
> Set default label 'name' at init, not when PromMetrics class is created.

- package.json
- yarn.lock
When upgrading `@swc/core` from v1.4.0 to v1.5.5 there was a change that results in source mappings failing. This would print thousands of lines of error messages in out e2e tests, but everything seems to compile okay. To cut down this noise until there is a fix, this PR reverts the `@swc/core` version back to 1.4.0.
More details and links here: #3655
> revert @swc/core to version 1.4.0

- packages/teraslice-test-harness/package.json
- packages/teraslice-test-harness/src/base-test-harness.ts
- packages/teraslice-test-harness/src/slicer-test-harness.ts
- packages/teraslice-test-harness/src/worker-test-harness.ts
- packages/teraslice-test-harness/test/slicer-test-harness-spec.ts
- packages/teraslice-test-harness/test/worker-test-harness-spec.ts
- the executionContext might not be set if shutdown is called before initialize, so we check for its existance
> Test harness shutdown fix

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/asset-src.ts
- packages/teraslice-cli/src/helpers/esm-shims.ts
- yarn.lock
- fix case to allow asset building of only esm-modules
- is backwards compatible, checks the top level `package.json` of the asset for `"type": "module"` to determine if its an esm-asset
> Esm asset build fix

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/asset-src.ts
Removing the `format: esm` argument to esbuild lets old assets build correctly.
> teraslice-cli - fix old asset build

- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8sResource.ts
- packages/teraslice/src/lib/cluster/services/jobs.ts
- packages/types/src/teraslice.ts
This PR makees the following changes:
- Creates an `addExternalPortsToJobSpec()` function that will add the `external_ports` field to a job if `promMetrics` are enabled and configure it to use the correct port.
- Adds a call to `addExternalPortsToJobSpec()` with the `submit()` and `update()` function within the `JobService` class.
ref: #3604
> Add external ports to job automatically when promMetrics are enabled

- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Updates `actions/checkout` and `actions/setup-node` from `v3` to `v4` 
- This resolves warmings to update actions in the actions panel on github
- Updates `actions/upload-pages-artifact` from `v1` to `v3`
- Updates `docker/login-action` from `v2` to `v3`
Ref to issue https://github.com/orgs/terascope/projects/2?pane=issue&itemId=68761752
> Update github actions to v4

- .github/workflows/publish-master.yml
- Updates `actions/deploy-pages` from `v2` to `v4`
- Updates `docker/login-action` to `v3`
This should resolve a broken pipeline where publishing docs fail. 
https://github.com/terascope/teraslice/actions/runs/9814144681/job/27101692541
This is most likely because we updated `upload-pages-artifact` to `v3` which requires `actions/deploy-pages@v4` or newer. Stated here: https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0
> Fix publish-master workflow

- Dockerfile.dev
- e2e/k8s/kindConfigDefaultPortsDev.yaml
- package.json
- packages/scripts/package.json
- packages/scripts/src/cmds/k8s-env.ts
- packages/scripts/src/helpers/interfaces.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/k8s-env/interfaces.ts
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/scripts/src/helpers/kind.ts
- packages/scripts/src/helpers/publish/interfaces.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8sResource.ts
- scripts/entrypoint-dev.sh
- yarn.lock
- Adds `--dev` option to k8s-env command
- This flag when enabled will add the entire `teraslice` repo as a volume to allow for fast build changes when running in kubernetes. 
- Adds dev compatibility to k8s master backend
- Fixes asset-storage setting in k8s-env
- This resolves a bug where launching k8s-env with `asset-storage` set to `s3` would not work correctly
> Add k8s-env --dev option

- Dockerfile
- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/publish/utils.ts
- packages/scripts/src/helpers/scripts.ts
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/types/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Adds these labels to the teraslice docker image:
- org.opencontainers.image.version="$TERASLICE_VERSION"
- org.opencontainers.image.created="$BUILD_TIMESTAMP"
- org.opencontainers.image.documentation="https://terascope.github.io/teraslice/docs/overview"
- org.opencontainers.image.licenses="Apache-2.0"
- org.opencontainers.image.revision="$GITHUB_SHA"
- org.opencontainers.image.source="https://github.com/terascope/teraslice"
- org.opencontainers.image.title="Teraslice"
- org.opencontainers.image.url="https://terascope.github.io/teraslice"
- org.opencontainers.image.vendor="Terascope"
- Updates the `dockerBuild` function to allow a `buildArgs` array.
- Updates `publishToDocker` function to pass the following `buildArgs`:
- `TERASLICE_VERSION`: equal to …
> Add labels to docker image

- .github/workflows/daily-docker-cache.yml
- Adds a new workflow action that runs once a day `Monday - Friday` at 5am to build a fresh docker cache
- This will allow all child branches to have access to this cache
> Add daily docker cache workflow to master

- .github/workflows/test.yml
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/images/index.ts
- packages/scripts/src/helpers/kind.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/services.ts
- packages/scripts/src/index.ts
- packages/scripts/test/images-spec.ts
- packages/scripts/test/service-spec.ts
- Run `verify-build` and `cache-docker-images` jobs in parallel in `test.yml` workflow. E2e tests now await both.
- Remove node 20 from e2e k8s jobs matrices
- Move `saveAndZip` function from `images` to `scripts`
- Add JSDoc style comments to functions
- Add tests for `images` command and `loadOrPullServiceImages` function
- Load kind image at proper time and load service images directly into kind correctly.
- Change error handling on `kindLoadImages` so errors aren't swallowed.
> Further improvements to CI test pipeline

- .github/workflows/daily-docker-cache.yml
- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile.dev
- docs/development/node.md
- e2e/test/docker-helpers.ts
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/images/index.ts
- scripts/check-latest-node-version.sh
- Changes node versions across `teraslice` to use major versions of node as a valid node version
- This is because the env variable `NODE_VERSION` used in e2e is tied to a valid tag in [terascope/node-base](https://hub.docker.com/r/terascope/node-base/tags)
- Added `workflow_dispatch` to the `daily-docker-cache.yml` to allow for manual workflow trigger
- Added `check-latest-node-version.sh` script for devs to find out which node version is currently used in the base image
- This is a convenience utility script that could be used somewhere else later to pop up a warning.
- Bumped ` @terascope/scripts` from `v0.81.2` to `v0.81.3` 
- Updated docs to explain how tagging works in the base image repo
Ref to issue #3683
> Unpin node versions in CI

- packages/terafoundation/package.json
- packages/terafoundation/src/validate-configs.ts
- packages/teraslice/package.json
Makes the function that gets the schema async  (i.e. awaiting imports of external plugins to add to the schema)
> make extract schema async

- packages/teraslice/src/lib/workers/assets/loader.ts
If an asset is deployed to teraslice with `teraslice.ASSET_STORAGE_CONNECTION_TYPE` set to `s3`, but then the connection type is switched to `elasticsearch`, job registration will fail. This PR improves the error message to tell the user to double check the connection type and then delete and redeploy assets.
ref: #3692
> Improve error message in Asset loader when asset blob is undefined

- packages/scripts/package.json
- packages/scripts/src/cmds/images.ts
- packages/scripts/src/helpers/images/index.ts
- packages/scripts/test/images-spec.ts
- Add ability to get the repo name out of the root `package.json`. This allows other repos that use ts-scripts to get a custom docker image list to use to create a cache specific to that repo. Valid repos are `elasticsearch-assets`, `kafka-asset-bundle`, `file-asssets-bundle`, and `teraslice-workspace`.
- Update tests 
- Bump scripts from version 0.81.4 to 0.82.0
> Create repo specific images lists

- packages/scripts/package.json
- packages/scripts/src/helpers/misc.ts
- packages/scripts/src/helpers/sync/configs.ts
The generateTSConfig writes to commonjs.
Ideas were to... 
A) check the package.json and adjust the compilerOptions to module/target/resolution to nodenext/esnext if it's a module
B) remove generateTSConfig completely
C) keep some options 
We looked at the git history and weren't completely clear why generating a tsconfig is needed since we already do what it's doing in the tsconfigs, so decided maybe keeping the references and just allow the original options for the rest.
> rework generateTSConfig

- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile.dev
- package.json
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/scripts.ts
- Moves `teraslice` images to be published in the `ghcr.io` registry instead of `docker.hub`
- Teraslice images are now built off the `node-base` image in the `ghcr.io` registry 
- Unpins node 22
> Migrate teraslice image from docker.hub to ghcr.io registry

- .github/workflows/publish-master.yml
- Resolves issue where CI can't publish docker images because of unauthorized credentials
> Fix failed docker publish in CI workflow

- packages/scripts/src/helpers/images/index.ts
- allows empty lists to be created in `scripts images list`
- prevents `scripts images save` from failing on an empty string.
This allows any repo that doesn't require images to use workflows using these commands without failing
Waiting on #3701 so I can bump scripts again
> Allow for empty lists in /images/images-list.txt

- packages/scripts/package.json
- packages/scripts/src/helpers/k8s-env/index.ts
- Fixes bug when running `ts-scripts k8s --dev` that will fail when env variable `NODE_VERSION` is a major version
- Before, this check only expected full semver versions
- Added kind cleanup in error scenarios
- Bumps **@terascope/scripts** from `v0.83.0` to `v0.83.1`
> Fix node version check in k8s --dev mode

- e2e/test/download-assets.ts
- packages/teraslice-cli/package.json
- packages/teraslice-test-harness/package.json
- yarn.lock
- In e2e tests, adds retry functionality within each promise that is attempting to download an asset. 
- Parses any `got.HTTPError` from `downloadRelease()` and determines the delay between retries based on the response headers from github.
- Updates `fetch-github-release` from 0.8.10 to 1.0.0
See: https://github.com/terascope/fetch-github-release/issues/300
> add retry to asset downloads

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/cmds/tjm/view.ts
- packages/teraslice-cli/src/helpers/jobs.ts
- packages/teraslice-cli/src/helpers/yargs-options.ts
- yarn.lock
This PR makes the following changes: 
- Adds `--diff` option to `teraslice cli view` that will compare the local `json` job file with what teraslice has on the state cluster
- Bumps `teraslice-cli` from `v2.1.0` to `v2.2.0`
Ref to issue #3694
> Add --diff option teraslice-cli

- e2e/package.json
- packages/data-mate/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
This PR adds `scripts/fix-deps.js` to the `files` array within `xlucene-parser/package.json` so that the script is included in the NPM package.
Bumps xlucene-parser from 1.0.0 to 1.0.1
> Include fix deps script in npm package

- .github/workflows/test.yml
- e2e/package.json
- packages/data-mate/package.json
- packages/data-mate/src/index.ts
- packages/data-mate/src/interfaces.ts
- packages/data-mate/src/transforms/field-transform.ts
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- Modify `packages/data-mate/src/index.ts` to copy each property from the `FTransform` and `RTransform` imports to a new object instead of using `cloneDeep`. This avoids a type error that occurs when `teraslice-cli assets build` tries to build an ESM asset that imports `data-mate` 
- Bump data-mate from 1.0.2 to 1.0.3, elasticsearch-store from 1.0.2 to 1.0.3, terafoundation from 1.2.2 to 1.2.3, ts-transforms from 1.0.2 to 1.0.3 
See here for details: #3725
> Fix data mate import copy

- packages/elasticsearch-api/package.json
- packages/elasticsearch-api/types/index.d.ts
- packages/teraslice-state-storage/package.json
- packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts
- packages/teraslice/package.json
- Update `index.d.ts` within `elasticsearch-api` to have a default export.
- Bump elasticsearch-api from 4.0.0 to 4.0.1
- Bump teraslice-state-storage from 1.0.0 to 1.0.1
> create default import for elasticsearch-api

- packages/scripts/package.json
- packages/scripts/src/helpers/scripts.ts
- Changes the `runJest` script to call `yarn` with `jest` as the first argument rather than calling `jest` on its own. This allows the test runner to run tests in a package using `yarn3 PnP` and ESM modules without getting module not found errors.
- Bump scripts from 1.0.0 to 1.0.1
> Add yarn to run jest command

- docs/management-apis/endpoints-json.md
- docs/management-apis/endpoints-txt.md
- docs/packages/data-mate/overview.md
- docs/packages/teraslice-state-storage/overview.md
- docs/packages/xlucene-parser/overview.md
- Update `docs/packages/xlucene-parser/overview.md` to explain how to use package with yarn Pnp
- Fix .md files to escape curly braces instead of using unicode decimal code
> [docs] update docs to remove escape characters

- docs/packages/teraslice-cli/overview.md
- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/cmds/jobs/export.ts
- packages/teraslice-cli/src/cmds/jobs/index.ts
- packages/teraslice-cli/src/helpers/config.ts
- packages/teraslice-cli/src/helpers/jobs.ts
- packages/teraslice-cli/src/helpers/tjm-util.ts
- packages/teraslice-cli/src/helpers/yargs-options.ts
- packages/teraslice-cli/test/cmds/jobs/export-spec.ts
- packages/teraslice-cli/test/fixtures/job_saves/aliases.yaml
- packages/teraslice-cli/test/helpers/config-spec.ts
- packages/teraslice-cli/test/helpers/jobs-spec.ts
- packages/teraslice-client-js/test/jobs-spec.ts
- Add `jobs export` command to teraslice-cli
- Creates a `Jobs` class using the provided jobIds, extracts the jobConfig for each job, and saves each config to the local file system. 
- Each job is saved to `./<job.name>.json` by default. If a file name already exists `-N` will be appended to the file name.
- `--outdir` flag will set a custom directory where job files are saved.
- A job-id of `all` will export all jobs. This can be combined with `--status` to export all jobs with executions of a specific status.
Ref: #3695
> [teraslice-cli] add earl jobs export command

- e2e/package.json
- e2e/test/docker-helpers.ts
- Wrap node version check in a pRetry and throw if undefined. Occasionally e2e tests will fail because using docker compose to exec into the teraslice master and checking the node version will return undefined. It is most likely a timing issue, so we will now attempt this 3 times and then throw if we still get undefined.
- Bump scripts from 0.7.0 to 0.7.1
> [e2e] Prevent the dockerUp function from failing by retrying when node version check returns undefined

- packages/job-components/src/operations/core/slicer-core.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/k8sResource.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/helpers/worker-shutdown.ts
- Teraslice running  in `KubernetesV2`  will have the ability to restart in a new pod automatically under certain conditions
- These conditions include receiving a `SIGTERM` signal not associated with a job shutdown, and the slicer being restartable.
- Added new function `isRestartable()` to the base slicer 
- `isRestartable()` will return a `boolean` to tell wether the slicer is compatible with the restartable feature or not. This allows for an initial implementation for `kafka` slicers without having to worry about the complexity of other slicers.
refs: #1007
> [teraslice] - Add execution controller restart logic in kubernetesV2

- docs/packages/teraslice-cli/overview.md
A few special characters were added a documentation change in my recent PR: #3717
After merging the docs build failed because docusuarus could not parse the .md file properly.
This PR escapes those characters properly.
> [docs] Escape special characters in md file

- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/workers/helpers/worker-shutdown.ts
- Changes execution controller exit logic to allow non-zero exit codes when in `kubernetesV2` and to **NOT** allow non-zero exit codes when in `kubernetes`
- This resolves an issue introduced in teraslice `v2.3.0` where the kubernetes V1 execution controller exit process is unintentionally changed. This PR restores it's original functionality while allowing `kubernetesV2` to gain its intended functionality.
#3755
> [teraslice] Fix ex controller non-zero exit code bug in k8s backend 

- e2e/k8s/kafkaDeployment.yaml
- e2e/k8s/kindConfigDefaultPorts.yaml
- e2e/k8s/kindConfigDefaultPortsDev.yaml
- e2e/k8s/kindConfigTestPorts.yaml
- e2e/k8s/minioDeployment.yaml
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/test-runner/services.ts
- Adds `localhost` kafka broker to `ts-scripts k8s` kafka service
- This allows for easy connection to kafka from within the host machine
- Adds port to minio k8s deployment and e2e to allow the connection to minio-ui
- Useful for debugging minio related issues in e2e and k8s 
Ref to issue #3759
> [ts-scripts] Add support for kafka and minio tools/brokers in k8s and e2e

- docs/configuration/overview.md
- docs/development/k8s.md
- docs/management-apis/endpoints-json.md
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/test-helpers-spec.ts
- packages/terafoundation/src/api/prom-metrics/exporter.ts
- packages/terafoundation/src/api/prom-metrics/prom-metrics-api.ts
- packages/terafoundation/src/schema.ts
- packages/terafoundation/test/apis/exporter-spec.ts
- packages/terafoundation/test/apis/prom-metrics-spec.ts
- packages/terafoundation/test/test-context-spec.ts
- packages/teraslice/src/lib/cluster/cluster_master.ts
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
- packages/types/src/terafoundation.ts
- The `PromMetrics` class needs to reset it's list of metrics on each scrape. If it doesn't do this, then all the executions are listed, not just the active ones. `resetMetrics()` functions were added to `PromMetrics` and `Exporter` to reset the `prom-client` register.
- Add `prom_metrics_display_url` field to terafoundation. This value will be used as the `url` default label added to all prom metrics. Defaults to an empty string, making it more obvious that this field is missing from the config.
- Include cluster analytics metrics (GET '/cluster/stats' endpoint results) in the cluster master
ref: #3743
> [terafoundation] Prom metrics exporter doesn't reset metrics between updates

- packages/job-components/src/operations/core/slicer-core.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- Renames the  `isRestartable()` function in the core slicer to `isRelocatable()` for better clarity on what this function is meant to return
> [teraslice] Rename isRestartable to is isRelocatable

- e2e/k8s/kindConfigDefaultPorts.yaml
- e2e/k8s/kindConfigDefaultPortsDev.yaml
- e2e/k8s/kindConfigTestPorts.yaml
- package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/index.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8s.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/index.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/k8s.ts
- packages/teraslice/src/lib/cluster/services/jobs.ts
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/k8s-spec.ts
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/v2/k8s-v2-spec.ts
- Ensure that `K8s._deleteObjByExId()` contains an object in `objList.items[]` before calling `K8s.deleted()`.
- Throw if `K8s.delete()` receives a `name` argument that is undefined or an empty string.
- Refactor `K8s._deleteObjByExId()` to delete multiple objects and not handle `force logic`
- Refactor `k8s.deleteExecution() to handle `force` logic by calling `K8s._deleteObjByExId()` on multiple resources.
- bump teraslice from version 2.3.1 to 2.3.2
- pin the kind image used by k8s to: `kindest/node:v1.28.12@sha256:fa0e48b1e83bb8688a5724aa7eebffbd6337abd7909ad089a2700bf08c30c6ea`. Note that the version in the image tag refers to the kubernetes server version that will be used. We should keep this in sync with prod.
ref: #3750
> [teraslice] fix multi-job deletion bug in force job stop

- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile.dev
- docs/development/node.md
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/asset-src.ts
- packages/teraslice/package.json
- website/sidebars.json
- `test.yml` - set `NODE_VERSION_MAIN` and `NODE_VERSION_EXT_STORAGE` to 22 (used by verify-build, lint-and-sync , and e2e-external-storage-tests jobs)
- `publish-master.yml` - node-version to 22
- `publish-tag.yml` - node-version to 22
- `Dockerfile` and `Dockerfile.dev` - NODE_VERSION to 22
- scripts `config.ts` - DEFAULT_NODE_VERSION to 22
- teraslice-cli `asset-src.ts` - bundleTarget defaults to node22
ref: #3771
> [workspace, scripts, teraslice-cli] Update default node version to 22

- packages/data-mate/package.json
- packages/data-mate/src/transforms/field-transform.ts
- packages/data-mate/src/validations/field-validator.ts
- packages/ts-transforms/package.json
- packages/ts-transforms/src/operations/lib/validations/isdn.ts
- packages/utils/package.json
- packages/utils/src/phone-number.ts
- yarn.lock
- update `awesome-phonenumber` from 2.70.0 to 7.1.0
- import `parsePhoneNumber` instead of default import. This is now a function that returns an object, not a class with functions to call. `valid() and getNumber() are replaced with accessing the data on the return object.
> [data-mate, ts-transforms, utils] update awesome-phonenumber from 2.70.0 to 7.1.0

- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- Updates default rabbitmq image to `3.13.7-management`
- Bump from `v1.3.2` to `v1.3.3`
> [scripts] Change rabbitmq image to 3.13.7-management

- e2e/package.json
- e2e/test/cases/assets/simple-spec.ts
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/cmds/assets/deploy.ts
- packages/teraslice-cli/test/servers/teraslice-server.ts
- packages/teraslice-client-js/package.json
- packages/teraslice-client-js/src/assets.ts
- packages/teraslice-client-js/test/assets-spec.ts
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/assets.ts
- packages/ts-transforms/package.json
- packages/types/package.json
- packages/types/src/teraslice.ts
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- make the response consistent with our other api responses
- `_id` => `asset_id`
- this change is backwards compatible but `_id` is marked as deprecated.
> Asset upload response

- package.json
- packages/data-mate/scripts/docs.js
- packages/data-mate/src/data-frame/utils.ts
- packages/eslint-config/package.json
- packages/teraslice/src/lib/cluster/services/cluster/backends/native/index.ts
- yarn.lock
- bump eslint from 9.10.0 to 9.12.0
- bump @eslint/js from 9.10.0 to 9.12.0
- bump @eslint/compat from 1.1.1 to 1.2.0
- bump @stylistic/eslint-plugin from 2.8.0 to 2.9.0
- bump @typescript-eslint/eslint-plugin from 8.5.0 to 8.9.0
- bump @typescript-eslint/parserfrom 8.5.0 to 8.9.0
- bump eslint-plugin-import from 2.30.0 to 2.31.0
- bump eslint-plugin-react-hooks from 4.4.0 to 5.0.0
- bump typescript-eslint from 8.5.0 to 8.9.0
- fix stylistic lint errors
> [eslint-config, data-mate, teraslice] Eslint updates

- docs/management-apis/endpoints-json.md
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/cluster/services/jobs.ts
- packages/types/src/teraslice.ts
- Adds `ex` query parameter to the `v1/jobs/:job_id` api endpoint
- It's now possible to to get a job with specific information about the current execution in one request
- Adds docs on how to use new `ex` query parameter in v1 jobs api endpoint
> Add execution info query to job api

- docs/development/k8s.md
- e2e/k8s/masterConfig/teraslice.yaml
- e2e/k8s/workerConfig/teraslice.yaml
- package.json
- packages/job-components/package.json
- packages/job-components/src/test-helpers.ts
- packages/job-components/test/test-helpers-spec.ts
- packages/terafoundation/package.json
- packages/terafoundation/src/api/prom-metrics/prom-metrics-api.ts
- packages/terafoundation/test/apis/prom-metrics-spec.ts
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
- Remove prom metrics `assignment` default label. This should never have been included.
- Exclude master pod from active execution list. We didn't realize this was included in the `cluster/state` endpoint `active` array for the node that had the master.
- bump teraslice from 2.6.0 to 2.6.1
- bump terafoundation from 1.5.1 to 1.5.2
- bump job-components from 1.5.1 to 1.5.2
Ref: #3743
> [job-components, terafoundation, teraslice] Remove prom metrics assignment default label, exclude master pod from active execution list

- docs/management-apis/endpoints-json.md
- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/cluster/services/jobs.ts
- Adds a feature introduced on #3792 into the `v1/jobs` endpoint
- Now you can list several jobs with their associated ex information in one api call
- Updated `management api` docs to reflect changes to `v1/jobs` endpoint
- **teraslice** from `v2.6.1` to `v2.6.2`
Ref to issue #3770
> [teraslice] Add ex info option to teraslice v1 jobs api

- package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/storage/assets.ts
- packages/teraslice/src/lib/utils/file_utils.ts
- packages/teraslice/test/storage/assets_storage-spec.ts
- Add `isZipFile()` to `file_utils` which checks the magic numbers at the beginning of a buffer to see if they match those of a zip file.
- `AssetStorage.save()` uses `isZipFile()` to check if the uploaded asset is a zip and throws an error if it isn't.
- Add `fake_zip.zip` and add a test that calls `AssetStorage.save()` on it.
> [terasclice] Ensure asset uploads are zip files

- packages/scripts/test/images-spec.ts
The `saveImages()` function can't be tested without mocking because it uses `docker pull` and `docker save`, which we don't want to do in CI. That would defeat the purpose of creating a cache of docker images. This is only used for CI caching purposes, so loss of test coverage is acceptable.
Ref: #3728
> [ts-scripts] remove saveImages() test.

- packages/scripts/package.json
- packages/scripts/src/cmds/test.ts
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/k8s-env/index.ts
- packages/scripts/src/helpers/kind.ts
- packages/scripts/src/helpers/scripts.ts
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/interfaces.ts
- packages/scripts/src/helpers/test-runner/services.ts
- packages/scripts/test/service-spec.ts
- packages/scripts/test/test-runner-spec.ts
- Add a new flag to ts-scripts test command called `skip-image-deletion` which will skip any command to delete the docker cache or a docker image within the docker cache.
- Add SKIP_IMAGE_DELETION variable to `scripts/src/helpers/config.ts`
-bump scripts from v1.4.2 to v1.5.0
ref: #3811
> [ts-scripts] add skip-image-deletion option to test-runner

- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/worker/index.ts
This PR makes the following changes to match the external prom-metrics exporter exactly:
- The `teraslice_version` label value should start with a `v`
- The `version` label should be the complete docker image tag unless there is an `_`. In that case the tag will be everything before the underscore.
ref: #3743
> [teraslice] fix 'teraslice_version' and 'version' prom metrics labels

- docs/configuration/clustering-k8s.md
- e2e/k8s/masterDeployment.yaml
- e2e/k8s/masterServiceAccount.yaml
- e2e/k8s/role.yaml
- e2e/k8s/roleBinding.yaml
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/k8s.ts
- Assigns a new, dedicated and restricted kubernetes `role` to the Teraslice `master` pod, enhancing secure access control
- Removes the default `ServiceAccount` usage, which granted all pods in the namespace full access to the Kubernetes API
- Updated documentation to reflect changes
Ref to issue #3251
> [teraslice, e2e] Add Kubernetes role restrictions to teraslice master 

- e2e/package.json
- package.json
- packages/data-types/package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- yarn.lock
This PR makes the following dependency updates: 
- **@types/lodash** from `v4.17.7` to `v4.17.13`
- **nanoid** from `v5.0.7` to `v5.0.8`
- **@types/lodash** from `v4.17.7` to `v4.17.13`
- **@eslint/compat** from `v1.2.0` to `v1.2.2`
- **eslint-plugin-jsx-a11y** from `v6.10.0` to `v6.10.2`
- **eslint-plugin-react** from `v7.37.1` to `v7.37.2`
- **@types/lodash** from `v4.17.7` to `v4.17.13`
- **nanoid** from `v5.0.7` to `v5.0.8`
- **nock** from `v13.5.5` to `v13.5.6`
- **nock** from `v13.5.5` to `v13.5.6`
- **nanoid** from `v5.0.7` to `v5.0.8`
- **nanoid** from `v5.0.7` to `v5.0.8`
- **nock** from `v13.5.5` to `v13.5.6`
- **nanoid** from `v5.0.7` to `v5.0.8`
> Dependency update 2024-11-13

- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/execution-controller/client.ts
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice-messaging/src/messenger/core.ts
- packages/teraslice-messaging/src/messenger/interfaces.ts
- packages/teraslice/package.json
- packages/teraslice/src/lib/workers/worker/index.ts
- The execution-controller `Client` now creates an `abortController`. Every call to `Client.sendSliceComplete()` now includes a reference to `abortController.signal` allowing for the `pEvent` in the messenger `Core.onceWithTimeout()` to be aborted.
- A new listener is added for the `server:shutdown` event that calls `abortController.abort()`. This prevents a worker from still waiting for a response to `sendSliceComplete()` after the server is shutdown.
- bump teraslice-messaging from 1.7.0 to 1.7.1
ref: #2106
> [teraslice-messaging, teraslice] Add abortController for use with sendSliceComplete()

- package.json
- packages/teraslice/package.json
- yarn.lock
- This version will be built on `base-docker-image v1.2.0` which includes `terafoundation_kafka_connector v1.2.0`
- bump cross-spawn nested dependency to use only v7.0.6
> [teraslice] Bump teraslice to version 2.9.0

- package.json
- packages/teraslice/package.json
- Bumps Teraslice from `v2.9.0` to `v2.9.1`
- This release is issued because of an update to the base image that bumped `terafoundation-kafka-connector`
> release: (patch) Teraslice v2.9.1

- .github/workflows/test.yml
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/scripts/test/test-runner-spec.ts
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Migrates all unit tests from `unit-esm` back to `unit`
- Removes `linux-unit-esm-tests` from ci
- This is no longer needed because all tests have been migrated to `linux-unit-tests` 
Ref to issue #3858
> [ci, scripts] Remove duplicate unused unit tests in CI

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/docker-compose-js/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/index.ts
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Remove the call to `k8s.waitForSelectedPod()` in `allocateWorkers()`, which was waiting for the executionController readiness probe to be ready before creating a worker deployment.
- Remove all code related to getting the `podIP` from `allocateSlicer()` as it is not needed since we now connect to the executionController using a kubernetes service.
- Bump teraslice from v2.9.1 to v2.9.2
ref: #3868
> [teraslice] fix serial job starts in kubernetesV2

- packages/scripts/package.json
- packages/scripts/src/helpers/test-runner/services.ts
- Adds `tmpfs` option to opensearch testing in `ts-scripts`
- Bumps `@terascope/scripts` from `v1.7.0` to `v1.7.1`
> [scripts] Add tmpfs option to opensearch testing

- packages/teraslice/src/lib/workers/execution-controller/index.ts
- packages/teraslice/src/lib/workers/execution-controller/scheduler.ts
This PR adds additional logging to the `ExecutionController` class that will help debugging a shutdown failure. See the issue here: #3856
> [teraslice] add logs to debug shutdown failures in execution controller

- packages/docker-compose-js/package.json
- packages/docker-compose-js/src/index.ts
- packages/docker-compose-js/test/docker-compose-spec.ts
- packages/docker-compose-js/test/fixtures/example.yaml
- packages/types/package.json
- bump docker-compose-js from v1.4.2 to v1.4.3
- re-enable unit tests for docker-compose-js and types packages
- update docker-compose-js tests to account for changes to package since the tests were disabled
> Re-enable docker-compose-js and types unit tests

- .github/workflows/publish-master.yml
- e2e/package.json
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/publish/index.ts
- packages/scripts/src/helpers/scripts.ts
- scripts/build-documentation.sh
- yarn.lock
- Fixes broken ci piplines that publish npm packages after a merge to master
- This is caused by scripts using the old yarn 1 sub-command to publish npm packages which yarn 4 doesn't support
- bump: (minor) @terascope/scripts@1.9.0
> Fix CI issues after yarn 4 update

- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- .yarnrc.yml
- Fixes issue where yarn wasn't getting an npm auth token when publishing packages.
> fix npm auth token for yarn 4

- e2e/package.json
- packages/data-mate/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/terafoundation/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- yarn.lock
- Fixes the package.json in `xlucene-parser` to specify the post install script to be executable when packaged for npm
- bump: (patch) **xlucene-parser**@1.7.2, 
- bump: (patch) **@terascope/data-mate**@1.7.2
- bump: (patch) **elasticsearch-store**@1.7.2, 
- bump: (patch) **terafoundation**@1.9.2
- bump: (patch) **ts-transforms**@1.7.2, 
- bump: (patch) **xlucene-translator**@1.7.2
Ref to issue #3900
> [xlucene-parser] Fix xlucene-parser postinstall permissions for npm

- .github/workflows/publish-master.yml
- e2e/test/cases/validation/version-sync-spec.ts
- packages/scripts/src/helpers/bump/index.ts
- Add a new job to the `publish-master.yml` workflow called `create-release-on-teraslice-bump`. It first uses `semver-compare-cli` to check if the version of Teraslice in the root `package.json` is greater than it was in the previous master branch. If it has then the `softprops/action-gh-release@v2` action creates a release. As with a manual release, the publish-tag.yml workflow will automatically run when the release is created.
- Add a test to ensure the teraslice version and root package.json version stay in sync. 
TODO: Should we bump teraslice just to make the new workflow job run?
ref: #1502
> [workspace] add workflow job to automate Teraslice releases

- e2e/package.json
- package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/teraslice/package.json
- yarn.lock
This PR updates the following dependencies:
- typescript from 5.7.2 to 5.7.3
- body-parser from 1.20.2 to 1.20.3
- The default depth of a body object is now limited to 32 by default
- bump teraslice from 2.12.0 to 2.12.1
> [teraslice, workspace] Update typescript to 5.7.3, body-parser to 1.20.3

- helm/teraslice/templates/_helpers.tpl
- Adds feature to helm chart template to support dynamic configuration of `prom_metrics_display_url`
- If the user explicitly sets `prom_metrics_display_url` in the terafoundation config, the provided value is used without modification (except making sure a trailing slash is appended if missing). Ex: `http://teraslice.local` will end up as `http://teraslice.local/` in the configmap.
- When `prom_metrics_display_url` is not set, the URL is dynamically constructed based on if the `ingress.enabled` configuration is `true` or `false`
- If `true`, it will make a url based off of the value in `.Values.ingress.hosts`.
- It will also add a `https://` prefix if `ingress.tls` is defined and non-empty. Otherwise will use `http://` prefix
- If `false` it will …
> [Chart] Set prom_metrics_display_url automatically

- .github/workflows/publish-master.yml
- Update `publish-master.yml` workflow to use the github Terascope Release App with `actions/create-github-app-token@v1` to create an access token. The previous token used cannot trigger a secondary workflow.
- Log slack API failures for debugging purposes.
> [workspace] fix release automation - use personal access token, log slack api failures

- .github/workflows/publish-master.yml
- .github/workflows/publish-tag.yml
- move the slack release notification to the end of the `publish-tag.yml` workflow.
- add links to the npm release and the teraslice docker container list
> [workspace] Improve slack release message

- .github/workflows/publish-master.yml
- Adds a GitHub App token to the `build-and-publish-helm-charts` ci job with the correct permissions
- This fixes an issue where the job would fail because it couldn't push the `index.yaml` into the master branch
- Adds ignore path to the `merge to master` pipeline because Github Apps can trigger other ci pipelines
- This specifically ignores re-triggering the pipeline in the event `index.yaml` is merged with master
- Makes change to `build-docs` ci job that will checkout the latest changes from the master branch
- This resolves an issue where in a previous pipeline we push to the master branch and don't receive the expected changes that are necessary for the `build-docs` job
> [CI] Helm chart workflow fix

- .github/workflows/publish-master.yml
- helm/helm-repo-site/index.tpl
- helm/teraslice/Chart.yaml
> [CI] fix chart publish from overwriting teraslice registry

- e2e/package.json
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/doc-builder/typedoc.ts
- packages/teraslice/package.json
- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
- yarn.lock
- bump teraslice from 2.12.2 to 2.12.3
- bump scripts from 1.9.1 to 1.9.2
- Add typedoc config options to display properties of enums, interfaces and classes as tables
- dependency updates 
- scripts
- `typedoc` from 0.25.13 to 0.27.6
- `typedoc-plugin-markdown from 4.0.3 to 4.4.1
- website
- @docusaurus/core from 3.0.0 to 3.7.0
- @docusaurus/mdx-loader from 3.4.0 to 3.7.0
- @docusaurus/preset-classic from 3.0.0 to 3.7.0
- @docusaurus/theme-mermaid from 3.4.0 to 3.7.0
- @mdx-js/react from 3.0.0 to 3.1.0
- clsx from 1.1.1 to 2.1.1
- react from 18.2.0 to 19.0.0
- react-dom from 18.2.0 to 19.0.0
- react-markdown from 8.0.7 to 9.0.3
> Update typedoc (0.27.6) and docusaurus (3.7.0)

- helm/helm-repo-site/index.tpl
- helm/teraslice/README.md
- website/docusaurus.config.js
- Adds an icon to the teraslice chart web docs page
- Adds chart link in the navigation bar of the teraslice web docs
- Miscellaneous link fixes on the chart web docs
- Add kindConfig copy paste to the helm chart docs.
- Add config docs to the helm chart 
Ref to issue #3920
> [docs] Helm docs improvements

- packages/teraslice-cli/package.json
- packages/teraslice-cli/src/helpers/jobs.ts
When running `teraslice-cli jobs export`, remove the pMap wrapper from the call to `exportOne()` as it is useless if we set concurrency to 1.
Bump teraslice-cli from `2.10.1` to `2.10.2`
ref: #3844
> [teraslice-cli] clean up 'jobs export' command to run serially without pMap

- e2e/k8s/kindConfigDefaultPorts.yaml
- e2e/k8s/kindConfigDefaultPortsDev.yaml
A change in #3929 required a change in the kind configs for the `k8s-env` command, but I forgot to make that change.
> [e2e] update kind Configs used in k8s-env to put teraslice port mapping first.

- e2e/package.json
- package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/teraslice-cli/package.json
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/utils.ts
- packages/utils/package.json
- yarn.lock
This PR updates the following dependencies:
- @chainsafe/is-ip from 2.0.2 to 2.1.0
- @eslint/compat from 1.2.5 to 1.2.6
- @stylistic/eslint-plugin from2.13.0 to 3.0.1
- @swc/core from 1.10.9 to 1.10.12
- @types/diff from 7.0.0 to 7.0.1
- @types/geojson form 7946.0.15 to 7946.0.16
- @types/lodash from 4.17.14 to 4.17.15
- @types/node from 22.10.10 to 22.13.0
- geo-tz from 8.1.2 to 8.1.3
- semver from 7.6.3 to 7.7.0
- typescript-eslint from 8.21.0 to 8.22.0
> bundled dependency updates

- .github/workflows/test.yml
- Dockerfile
- package.json
- packages/teraslice/package.json
- bump teraslice from 2.12.3 to 2.12.4-rc0
- pin the base docker image to node-base:22.9.0 in the Dockerfile
- terafoundation_kafka_connector v1.0.0
- node-rdkafka v3.1.1
- librdkafka v2.5.3
- node v22.9.0
- temporarily disable node 18 e2e tests, as the Dockerfile only creates a node 22 image
** NOTE: ** When testing is finished the Dockerfile and test workflow changes must be reverted
> [teraslice 2.12.4-rc0] Revert to base docker image using terafoundation_kafka_connector 1.0.0 and node 22.9.0 for testing

- .github/workflows/test.yml
- Dockerfile
- package.json
- packages/teraslice/package.json
- bump version to 2.12.4-rc.1
- Build a teralice image off base docker image v1.0.0-test release
- Revert changes to `Dockerfile` and `test.yml` needed to create teraslice 2.12.4-rc.0 
** NOTE: ** This version of teraslice is for testing only. The base docker image needs to be reverted when testing is complete.
> [Teraslice 2.12.4-rc.1] Build teraslice docker image from base image with node 22.12.0 and terafoundation_kafka_connector 1.0.0

- packages/teraslice-messaging/package.json
- packages/teraslice-messaging/src/execution-controller/client.ts
- packages/teraslice-messaging/src/messenger/client.ts
- packages/teraslice-messaging/src/messenger/core.ts
- packages/teraslice-messaging/src/messenger/interfaces.ts
- packages/teraslice/package.json
- yarn.lock
-bump teraslice-messaging from 1.10.3 to 1.10.4
- Remove the `abortController` from the execution-controller client
- Create an `abortController` in the core client `handleSendResponse` function if `sendAbortSignal` is set to true. This is only the case for when the execution-controller client sends the `worker:slice:complete` event. On a `server:shutdown` event the `abortController` will abort awaiting a server response so it can shutdown properly.  
ref: #3945
> [teraslice-messaging] fix memory leak caused by abortController

- package.json
- packages/teraslice/package.json
This PR bumps teraslice from 2.12.4 to 2.12.5 in order to build docker images on the newest base docker image.
> [teraslice] Build teraslice 2.12.5 on the newest base-docker-image

- e2e/package.json
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/bump/index.ts
- yarn.lock
- run `yarn setup` after the `ts-scripts bump` command modifies all `package.json` dependency versions. This ensures that the `yarn.lock` will be synced when the branch is pushed.
- bump scripts from 1.10.0 to 1.10.1
> run yarn setup at end of bump commands

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-mate/src/core/WritableData.ts
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/packages.ts
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/big-lru-map.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
- update mnemonist from 0.39.8 to 0.40.1
- update imports since ESM is now supported.
- bump package versions
- bump: (patch) @terascope/data-mate@1.7.5, elasticsearch-store@1.8.2
- bump: (patch) terafoundation@1.10.2, ts-transforms@1.7.5
- bump: (patch) @terascope/scripts@1.10.3, @terascope/utils@1.7.4
- bump: (patch) @terascope/data-types@1.7.4, xlucene-parser@1.7.5
- bump: (patch) xlucene-translator@1.7.5, @terascope/elasticsearch-api@4.8.2
- bump: (patch) @terascope/teraslice-state-storage@1.8.2, @terascope/job-components@1.9.5
- [bump teraslice from 2.12.5 to 2.12.6](release: (patch) teraslice@2.12.6)
Needs: #3960 merged first
> [data-mate, scripts, teraslice, utils] update mnemonist to 0.40.1

- .github/workflows/daily-docker-cache.yml
This PR makes the following change:
- Add `inputs` to the `workflow_dispatch`. This allows us to have a custom `run-name` for the workflow. If the workflow is triggered by a cron job the run-name will include `Scheduled Weekly Run`, if triggered manually it will include `Manually Triggered`, and if triggered by the `base-docker-image` release workflow it will include `New Base Images Released`.
ref: #3955
> [CI] Add inputs to workflow_dispatch of daily-docker-cache.yml

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
This PR bumps the following packages:
- release: (patch) teraslice@2.12.7
- bump: (patch) @terascope/data-mate@1.7.6, elasticsearch-store@1.8.3
- bump: (patch) terafoundation@1.10.3, ts-transforms@1.7.6
- bump: (patch) @terascope/eslint-config@1.1.7, @terascope/scripts@1.10.4
- bump: (patch) teraslice-cli@2.10.3, @terascope/teraslice-messaging@1.10.6
- bump: (patch) @terascope/utils@1.7.5, @terascope/data-types@1.7.5
- bump: (patch) xlucene-parser@1.7.6, xlucene-translator@1.7.6
PR that bumps deps #3970
> Bump teraslice to v2.12.7

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/types/src/elasticsearch-client/elasticsearch-params.ts
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
This PR updates the following dependencies:
- @eslint/compat from 1.2.6 to 1.2.7
- @eslint/js from 9.20.0 to 9.21.0
- @stylistic/eslint-plugin from 3.1.0 to 4.0.1
- @swc/core from 1.10.15 to 1.10.18
- @types/node from 22.13.4 to 22.13.5
- eslint from 9.20.1 to 9.21.0
- globals from 15.15.0 to 16.0.0
- mnemonist from 0.40.2 to 0.40.3
- nanoid from 5.1.0 to 5.1.2
- ts-jest from 29.2.5 to 29.2.6
- typedoc from 0.27.7 to 0.27.8
- uuid from 11.0.5 to 11.1.0
The following terascope packages have been bumped:
- teraslice from 2.12.7 to 2.12.8
- data-mate from 1.7.6 to 1.7.7
- data-types from 1.7.5 to 1.7.6
- elasticsearch-api from 4.8.3 to 4.8.4
- elasticsearch-store from 1.8.3 to 1.8.4
- eslint-config from 1.1.7 to 1.1.8
- job-components from 1.9.6 to 1.9.7
- scripts from 1.10.4 to 1.10.5
- …
> Bundled dep updates for 2-24-2025

- helm/teraslice/Chart.yaml
- helm/teraslice/values.yaml
- package.json
- packages/teraslice/package.json
This PR bumps teraslice from 2.12.8 to 2.13.0
- This version will be built on `base-docker-image` version 1.4.0
- terafoundation_kafka_connector v1.4.0
- node-rdkafka v3.2.1
- librdkafka v2.8.0
> release: (minor) teraslice@2.13.0

- e2e/package.json
- helm/teraslice/Chart.yaml
- package.json
- packages/data-mate/package.json
- packages/data-mate/src/column/Column.ts
- packages/data-mate/src/data-frame/DataFrame.ts
- packages/data-mate/src/vector/Vector.ts
- packages/data-mate/test/function-configs/function-configs-spec.ts
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/arrays.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
- update the terascope chart
- version from 2.2.0 to 2.3.0
- appVersion from 2.14.0 to 2.14.1 
- updates the following dependencies:
- @terascope/scripts from 1.12.0 to 1.12.1
- @terascope/utils from 1.7.6 to 1.7.7
- elasticsearch-store from 1.9.0 to 1.9.1
- nanoid from 5.1.2 to 5.1.3
- @eslint/js from 9.21.0 to 9.22.0
- @swc/core from 1.11.5 to 1.11.8
- @terascope/scripts from 1.12.0 to 1.12.1
- @types/node from 22.13.8 to 22.13.10
- eslint from 9.21.0 to 9.22.0
- dependencies
- @terascope/data-types from 1.7.6 to 1.7.7
- @terascope/utils from 1.7.6 to 1.7.7
- awesome-phonenumber from 7.3.0 to 7.4.0
- xlucene-parser from 1.7.7 to 1.7.8
- dependencies
- @terascope/utils from 1.7.6 to 1.7.7
- dependencies
- …
> bundled dependency updates for 2025-3-10

- .github/workflows/test.yml
- Dockerfile
- Dockerfile.dev
- e2e/test/cases/kafka/kafka-spec.ts
- helm/helm-repo-site/index.tpl
- packages/scripts/src/helpers/scripts.ts
This PR makes the following updates:
- Remove unneeded `unpkg/clipboardJS` import from helm repo `index.html`
- fix order of checks for the `kafka-spec` encryption test
- fix dockerfile warnings when declaring ENVs
- `dockerNetworkExists()` function was using `execaCommand()` with a `|`, so it needs to set the `shell` option to true
- pin mkcert version within test.yaml
> [e2e, scripts, helm, dockerfile] Small fixes

- .github/workflows/publish-master.yml
This PR adds a new job to the `publish-master` workflow. It will run only if the teraslice helm-chart has been updated. The job triggers the `update-gh-pages` workflow in the `terascope/helm-charts` repository, which will merge the new teraslice-chart [index.yaml](https://terascope.github.io/teraslice/charts/index.yaml) with the helm-charts [index.yaml](https://terascope.github.io/helm-charts/index.yaml), allowing all public terascope charts to be accessible using `helm repo add terascope https://terascope.github.io/helm-charts.
ref: #3999
> [CI] trigger helm-charts update-gh-pages workflow when teraslice chart updates

- e2e/helm/templates/teraslice.yaml.gotmpl
- helm/teraslice/Chart.yaml
- helm/teraslice/values.yaml
This PR fixes a mistake that added `autoload_directory` to the default teraslice helm `values.yaml`. This setting is only needed for e2e, so is now set in `e2e/helm/templates/teraslice.yaml.gotmpl`.
The chart is bumped to version 2.3.1
I also added `icon` and `home` links to the chart.
> [e2e, helm] autoload_directory should be created in e2e helm, not be default in helm chart

- .github/codecov.yml
- .github/workflows/test.yml
- jest.config.base.js
- jest.config.js
- packages/scripts/package.json
- packages/scripts/src/helpers/test-runner/index.ts
- packages/scripts/src/helpers/test-runner/utils.ts
- packages/teraslice/test/storage/s3_store-spec.ts
- yarn.lock
- Adds code coverage and uploads coverage to `codecov` 
- Coverage targets all `unit`, `elasticsearch-store-integration`, `teraslice-integration`, and `elasticsearch-api-integration` tests
- Excludes `e2e` test coverage for now 
- #4011
- Adds more tests to `s3Store` class in teraslice
- Removes deprecated [codecov](https://www.npmjs.com/package/codecov) npm package in favor of using the `codecov` Github action for uploading coverage data
- Removes related `codecov` upload functionality out of scripts
NOTE: Unit tests no longer run in parallel because jest will miss significant code coverage
https://github.com/jestjs/jest/issues/4255
Ref to issue #4004
> [CI, scripts] Reintroduce code coverage metrics

- e2e/k8s/kindConfigTestPorts.yaml
- e2e/package.json
- e2e/test/cases/kafka/kafka-spec.ts
- e2e/test/config.ts
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/bin/ts-scripts.js
- packages/scripts/package.json
- packages/scripts/src/helpers/config.ts
- packages/scripts/src/helpers/kind.ts
- packages/scripts/test/service-spec.ts
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/ip.ts
- packages/utils/test/ip-spec.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
- Adds port validation to all tests that need services
- If a service port is in use, scripts will now find a random port that isn't in use and assign the new port to said service
Ref to issue #3898
> [E2e, utils] Validate service ports when running ci tests

- e2e/package.json
- helm/teraslice/Chart.yaml
- package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/k8s-env/k8s.ts
- packages/teraslice/package.json
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/interfaces.ts
- packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/k8s.ts
- packages/teraslice/test/lib/cluster/services/cluster/backends/kubernetes/v2/k8s-v2-spec.ts
- yarn.lock
- Update @kubernetes/client-node from v0.22.3 to v1.1.1
- fix API breaking changes
- bump teraslice to v2.14.4
- bump @terascope/scripts to v1.15.2
- bump teraslice helm chart to v2.7.0
> [teraslice, scripts] update @kubernetes/client-node to v1.1.1

- e2e/package.json
- helm/teraslice/Chart.yaml
- package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/teraslice/package.json
- yarn.lock
- bump teraslice from v2.14.4 to v2.14.5
- bump teraslice helm chart from v2.7.0 to 2.8.0
updates the following packages:
- @terascope/scripts from 1.15.2 to 1.15.3
- ts-jest from 29.3.0 to 29.3.2
- typescript from 5.8.2 to 5.8.3
- @eslint/js from 9.23.0 to 9.24.0
- @swc/core from 1.11.13 to 1.11.21
- @terascope/scripts from 1.15.2 to 1.15.3
- @types/node from 22.13.14 to 22.14.1
- eslint from 9.23.0 to 9.24.0
- ts-jest from 29.3.0 to 29.3.2
- typescript from 5.8.2 to 5.8.3
- dependencies
- @eslint/compat from 1.2.7 to 1.2.8
- @eslint/js from 9.23.0 to 9.24.0
- @typescript-eslint/eslint-plugin from 8.28.0 to 8.29.1
- @typescript-eslint/parser from 8.28.0 to 8.29.1
- eslint from 9.23.0 to 9.24.0
- eslint-plugin-react …
> Dependency updates for 04-14-2025

- e2e/package.json
- package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/scripts/src/helpers/doc-builder/typedoc.ts
- yarn.lock
- Updates the following dependencies
- **typescript-eslint** from `v8.29.1` to `v8.30.1`
- **typedoc** from `v0.27.9` to `v0.28.2`
- **typedoc-plugin-markdown** from `v4.4.2` to `v4.6.2`
- Adjust typedoc configuration to be compliant with the current version of typedoc and the markdown plugin
- Bump: (**patch**) @terascope/scripts to `v1.15.4`
- Bump: (**patch**) @terascope/eslint-config to `v1.1.13`
Ref to issue #4021
> [docs, scripts, eslint-config] Update typedoc and markdown plugin

- .github/workflows/test.yml
- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
This PR updates the following packages:
- @eslint/js from 9.25.1 to 9.26.0
- @swc/core from 1.11.22 to 1.11.24
- eslint from 9.25.1 to 9.26.0
- dependencies
- awesome-phonenumber from 7.4.0 to 7.5.0
- dependencies
- @eslint/compat from 1.2.8 to 1.2.9
- @eslint/js from 9.25.1 to 9.26.0
- @typescript-eslint/eslint-plugin from 8.31.0 to 8.31.1
- @typescript-eslint/parser from 8.31.0 to 8.31.1
- eslint from 9.25.1 to 9.26.0
- typescript-eslint from 8.31.0 to 8.31.1
- dependencies
- typedoc from 0.28.3 to 0.28.4
- dependencies
- awesome-phonenumber from 7.4.0 to 7.5.0
- dependencies
- awesome-phonenumber from 7.4.0 to 7.5.0
The github workflow `test.yml` now pins the version of helmfile used in k8sV2 e2e tests to 0.171.0 as helmfile v1.0.0 requires the renaming of files that …
> bundled dependency updates for 5-5-2025, CI fix

- helm/teraslice/Chart.yaml
- helm/teraslice/values.yaml
- package.json
- packages/teraslice/package.json
- bump teraslice from 2.14.5 to 2.15.0
- this release will build on the teraslice base-docker-image containing:
- `terafoundation_kafka_connector v1.5.0`
- `node-rdkafka v3.4.0`
- `librdkafka v2.10.0`
> [teraslice] bump version to 2.15.0, build with terafoundation_kafka_connector v1.5.0

- packages/data-mate/package.json
- packages/data-types/package.json
- packages/docker-compose-js/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/job-components/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/types/package.json
- packages/utils/package.json
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- Changes the way ts-scripts is called in all packages in the monorepo
- This fixes a bug where the developer can't pass `ts-scripts` flags when executing tests
Ref to issue #4043
> [tests] use scripts bin instead of yarn workspace

- examples/helm/README.md
- examples/helm/helmfile.yaml.gotmpl
- examples/helm/kindConfig.yaml
- examples/helm/values.yaml
- Fixes configuration error within example helm that breaks teraslice
- Adds kafka-ui and teraslice utility pod to the example helm environment 
- Adds quick start guide to example helm docs with links and docs to exposed services
> [development] Update example helm environment

- e2e/package.json
- package.json
- packages/data-mate/package.json
- packages/data-types/package.json
- packages/elasticsearch-api/package.json
- packages/elasticsearch-store/package.json
- packages/job-components/package.json
- packages/scripts/package.json
- packages/terafoundation/package.json
- packages/teraslice-cli/package.json
- packages/teraslice-client-js/package.json
- packages/teraslice-messaging/package.json
- packages/teraslice-state-storage/package.json
- packages/teraslice-test-harness/package.json
- packages/teraslice/package.json
- packages/ts-transforms/package.json
- packages/utils/package.json
- packages/utils/src/deps.ts
- packages/utils/src/errors.ts
- packages/utils/test/deps-spec.ts
- packages/utils/test/errors-spec.ts
- packages/xlucene-parser/package.json
- packages/xlucene-translator/package.json
- packages/xpressions/package.json
- yarn.lock
- Adds new helper function `formatAggregateError` that takes an Error and if it's an aggregate Error will parse it out into one error.
- This will show a maximum of 5 errors 
ref to issues: #4076 
https://github.com/terascope/standard-assets/issues/1114
> [utils] Add formatAggregateError helper function

- e2e/package.json
- package.json
- packages/elasticsearch-store/package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/teraslice-cli/package.json
- website/package.json
- website/yarn.lock
- yarn.lock
This PR updates the following packages:
- @swc/core from 1.12.14 to 1.13.1
- @types/node from 24.0.13 to 24.0.15
- dependencies
- add @terascope/opensearch-client v1.1.0 
- dependencies
- @stylistic/eslint-plugin from 5.1.0 to 5.2.1
- @typescript-eslint/eslint-plugin from 8.36.0 to 8.37.0
- @typescript-eslint/parser from 8.36.0 to 8.37.0
- typescript-eslint from 8.36.0 to 8.37.0
- dependencies
- typedoc-plugin-markdown from 4.7.0 to 4.7.1
- dependencies
- esbuild from 0.25.6 to 0.25.8
- dependencies
- @docusaurus/core from 3.7.0 to 3.8.1
- @docusaurus/mdx-loader from 3.7.0 to 3.8.1
- @docusaurus/preset-classic from 3.7.0 to 3.8.1
- @docusaurus/theme-mermaid from 3.7.0 to 3.8.1
- react from 19.0.0 to 19.1.0
- react-dom from 19.0.0 to 19.1.0
- react-markdown from 9.0.3 to …
> Dependency updates 2025 7 21

- e2e/package.json
- package.json
- packages/eslint-config/package.json
- packages/scripts/package.json
- packages/teraslice-cli/package.json
- website/yarn.lock
- yarn.lock
This PR updates the following packages:
- @terascope/scripts from 1.21.4 to 1.21.5
- @eslint/js from 9.33.0 to 9.34.0
- @swc/core from 1.13.3 to 1.13.5
- @terascope/scripts from 1.21.4 to 1.21.5
- @types/node from 24.2.1 to 24.3.0
- eslint from 9.33.0 to 9.34.0
- dependencies
- @eslint/js from 9.33.0 to 9.34.0
- @typescript-eslint/eslint-plugin from 8.39.0 to 8.40.0
- @typescript-eslint/parser from 8.39.0 to 8.40.0
- eslint from 9.33.0 to 9.34.0
- eslint-plugin-testing-library from 7.6.4 to 7.6.6
- typescript-eslint from 8.39.0 to 8.40.0
- dependencies
- typedoc from 0.28.10 to 0.28.11
- typedoc-plugin-markdown from 4.8.0 to 4.8.1
- dependencies
- esbuild from 0.25.8 to 0.25.9
- chalk from 5.5.0 to 5.6.0
- pretty-bytes from 7.0.0 to …
> Bundled dependency updates for 8-25-2025

- helm/teraslice/Chart.yaml
- helm/teraslice/values.yaml
- package.json
- packages/teraslice/package.json
- bump teraslice from 2.17.2 to 2.17.3
- this release will build on the teraslice base-docker-image containing:
- `terafoundation_kafka_connector v1.6.0`
- `node-rdkafka v3.5.0`
- `librdkafka v2.11.1`
- bump helmchart from 2.17.0 to 2.18.0
> release: (patch) teraslice@2.17.3 

- docs/management-apis/endpoints-json.md
- packages/teraslice/src/lib/cluster/services/api.ts
- packages/teraslice/src/lib/utils/api_utils.ts
- packages/teraslice/test/utils/api_utils-spec.ts
- Removes the ability of the `cluster/stats` endpoint to return stats in a prom metrics compatible format
- Updates docs
Ref: #4159
TODO: ensure this functionality is not used anywhere before merging
> remove prometheus format from cluster/stats

- .github/workflows/test.yml
- add build-dev-docker-images job to `test.yml` workflow. This builds a docker image per node version and saves it as an artifact using the workflow ID
- add steps to e2e test jobs that download docker image artifact and load into docker
- update `yarn test` commands to `SKIP_DOCKER_BUILD_IN_E2E` and set `DEV_DOCKER_IMAGE` to our workflow ID
> build docker images once per workflow
